package com.tencent.mobileqq.app;

import com.tencent.aelight.camera.constants.AECameraConstants;
import com.tencent.aelight.camera.constants.AEEditorConstants;
import com.tencent.biz.pubaccount.api.IPublicAccountArticleHandler;
import com.tencent.mobileqq.app.face.FaceConstant;
import com.tencent.mobileqq.emosm.favroaming.FavEmoConstant;
import com.tencent.mobileqq.mini.api.MiniConst;
import com.tencent.mobileqq.profilecard.api.ProfileContants;
import com.tencent.mobileqq.profilecard.bussiness.anonymous.handler.AnonymousHandler;
import com.tencent.mobileqq.profilecard.bussiness.photowall.constant.PhotoWallConstant;
import com.tencent.mobileqq.profilecard.servlet.ProfileCardServlet;
import com.tencent.mobileqq.pushdialog.SafeBlowHandler;
import com.tencent.mobileqq.qfix.redirect.IPatchRedirector;
import com.tencent.mobileqq.qfix.redirect.PatchRedirectCenter;
import com.tencent.mobileqq.teamwork.api.IGroupTeamWorkHandler;
import com.tencent.mobileqq.teamwork.api.ITeamWorkHandler;
import com.tencent.mobileqq.theme.ThemeConstants;
import com.tencent.mobileqq.tianshu.data.RedTouchConst;
import com.tencent.mobileqq.transfile.protohandler.NearbyPeoplePicUpHandler;
import com.tencent.mobileqq.vas.vipav.api.VipFunCallConstants;
import com.tencent.qphone.base.BaseConstants;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import mqq.app.MobileQQ;

/* compiled from: P */
/* loaded from: classes11.dex */
public class f {
    static IPatchRedirector $redirector_;

    /* renamed from: a, reason: collision with root package name */
    public static final String f195513a;

    /* renamed from: b, reason: collision with root package name */
    private static Map<String, String[]> f195514b;

    /* renamed from: c, reason: collision with root package name */
    private static Map<String, String[]> f195515c;

    /* renamed from: d, reason: collision with root package name */
    private static Object f195516d;

    static {
        IPatchRedirector redirector = PatchRedirectCenter.getRedirector(69612);
        $redirector_ = redirector;
        if (redirector != null && redirector.hasPatch((short) 2)) {
            redirector.redirect((short) 2);
        } else {
            f195513a = f.class.getName();
            f195516d = new Object();
        }
    }

    public f() {
        IPatchRedirector iPatchRedirector = $redirector_;
        if (iPatchRedirector != null && iPatchRedirector.hasPatch((short) 1)) {
            iPatchRedirector.redirect((short) 1, (Object) this);
        }
    }

    public static Map<String, String[]> a() {
        if (f195514b == null) {
            synchronized (f195516d) {
                if (f195514b == null) {
                    f195514b = new ConcurrentHashMap();
                    int i3 = MobileQQ.sProcessId;
                    if (i3 != 5 && i3 != 7) {
                        e();
                    }
                    f();
                    c();
                    d();
                }
            }
        }
        return f195514b;
    }

    public static Map<String, String[]> b() {
        if (f195515c == null) {
            synchronized (f195516d) {
                if (f195515c == null) {
                    f195515c = new ConcurrentHashMap();
                    g();
                }
            }
        }
        return f195515c;
    }

    private static void c() {
        f195514b.put("OidbSvc.0x95a", new String[]{com.tencent.mobileqq.armap.a.f199721a});
        f195514b.put("OidbSvc.0xb49", new String[]{com.tencent.mobileqq.armap.a.f199722b});
    }

    private static void d() {
        f195514b.put(IPublicAccountArticleHandler.CMD_CHECK_ARTICLE_LIKE, new String[]{"PublicAccountArticleHandler"});
        f195514b.put(IPublicAccountArticleHandler.CMD_GET_ARTICLE_LIKE_COUNT, new String[]{"PublicAccountArticleHandler"});
    }

    private static void e() {
        f195514b.put(AECameraConstants.CMD_COMPRESSED_MATERIAL_CATEGORY, new String[]{BusinessHandlerFactory.CAMERA_HANDLER});
        f195514b.put("ShadowBackendSvc.GetPlayShowCatMatTree", new String[]{BusinessHandlerFactory.CAMERA_HANDLER});
        f195514b.put(AECameraConstants.CMD_CAMERA_CONFIG, new String[]{BusinessHandlerFactory.CAMERA_HANDLER});
        f195514b.put(AECameraConstants.CMD_TAB_AB_TEST, new String[]{BusinessHandlerFactory.CAMERA_HANDLER});
        f195514b.put(AECameraConstants.CMD_MATERIAL_RACE, new String[]{BusinessHandlerFactory.CAMERA_HANDLER});
        Map<String, String[]> map = f195514b;
        String str = BusinessHandlerFactory.MESSAGE_HANDLER;
        String str2 = BusinessHandlerFactory.CARD_HANLDER;
        map.put("AccostSvc.SvrMsg", new String[]{str, str2});
        f195514b.put("AccostSvc.ClientMsg", new String[]{str, str2});
        f195514b.put("AccostSvc.ReqDeleteBlackList", new String[]{str});
        f195514b.put("AccostSvc.ReqInsertBlackList", new String[]{str});
        f195514b.put("OidbSvc.0x9db", new String[]{str});
        f195514b.put("AccostSvc.ReqGetBlackList", new String[]{str});
        f195514b.put("OidbSvc.0x4ff_42024", new String[]{str});
        f195514b.put("TransService.ReqGetSign", new String[]{str});
        f195514b.put("SharpSvr.s2c", new String[]{str});
        f195514b.put("MessageSvc.PbGetRoamMsg", new String[]{str});
        f195514b.put("MessageSvc.DelRoamMsg", new String[]{str});
        f195514b.put("PbMessageSvc.PbSearchRoamMsgInCloud", new String[]{str});
        f195514b.put("SharpSvr.c2sack", new String[]{str});
        f195514b.put("ADMsgSvc.PushMsg", new String[]{str});
        f195514b.put("StreamSvr.PushStreamMsg", new String[]{str});
        f195514b.put(MiniConst.Spark.CMD_PUSH_SPARK_REWARD, new String[]{str});
        f195514b.put("OnlinePush.PbPushTransMsg", new String[]{str});
        f195514b.put("OnlinePush.PbC2CMsgSync", new String[]{str});
        f195514b.put("MessageSvc.PbBindUinGetMsg", new String[]{str});
        f195514b.put("PbMessageSvc.PbBindUinMsgReadedConfirm", new String[]{str});
        f195514b.put("OidbSvc.0x5d0_1", new String[]{str});
        f195514b.put("OnlinePush.PbPushDisMsg", new String[]{str});
        f195514b.put("MessageSvc.PullGroupMsgSeq", new String[]{str});
        f195514b.put(BaseConstants.CMD_MSG_UNREAD_MSG_SEQ, new String[]{str});
        f195514b.put("MessageSvc.PbGetOneDayRoamMsg", new String[]{str});
        f195514b.put("StreamSvr.RespUploadStreamMsg", new String[]{str});
        f195514b.put("TransService.ReqOffFilePack", new String[]{str});
        f195514b.put(BaseConstants.CMD_NT_REGPRXYSVC_SSO_GET_GROUP_SHARE_MSG, new String[]{str});
        f195514b.put("MessageSvc.PbGetDiscussMsg", new String[]{str});
        f195514b.put("MessageSvc.DelMsgV2", new String[]{str});
        f195514b.put("MessageSvc.SetRoamMsgAllUser", new String[]{str});
        f195514b.put("OnlinePush.PbPushGroupMsg", new String[]{str});
        f195514b.put("OnlinePush.PbPushBindUinGroupMsg", new String[]{str});
        f195514b.put("OnlinePush.PbPushC2CMsg", new String[]{str});
        f195514b.put("VideoCCSvc.Adaptation", new String[]{str});
        f195514b.put("StreamSvr.UploadStreamMsg", new String[]{str});
        f195514b.put("MultiVideo.s2c", new String[]{str});
        f195514b.put("NearFieldTranFileSvr.NotifyList", new String[]{str});
        f195514b.put(BaseConstants.CMD_MSG_PBSENDMSG, new String[]{str, BusinessHandlerFactory.DATALINE_HANDLER});
        f195514b.put("OidbSvc.0xa89", new String[]{str});
        f195514b.put("MessageSvc.PbMultiMsgSend", new String[]{str});
        f195514b.put("SecSvcBlessingHelper.blessing_helper", new String[]{str});
        f195514b.put("MessageSvc.PushReaded", new String[]{str});
        f195514b.put(BaseConstants.CMD_RESPPUSH, new String[]{str});
        f195514b.put("TransService.ReqTmpChatPicDownload", new String[]{str});
        f195514b.put("MessageSvc.PbGetMsg", new String[]{str});
        f195514b.put("MultiVideo.c2sack", new String[]{str});
        f195514b.put("PbMessageSvc.PbDelOneRoamMsg", new String[]{str});
        f195514b.put("PbMessageSvc.PbMsgWithDraw", new String[]{str});
        f195514b.put("MessageSvc.PushNotify", new String[]{str});
        f195514b.put("MessageSvc.GetMsgV4", new String[]{str});
        f195514b.put(BaseConstants.CMD_REGPRXYSVC_INFOLOGIN, new String[]{str});
        f195514b.put("ProfileService.Pb.ReqSystemMsgRead", new String[]{str});
        f195514b.put("ProfileService.Pb.ReqSystemMsgNew", new String[]{str});
        f195514b.put("ProfileService.Pb.ReqSystemMsgNew.Friend", new String[]{str});
        f195514b.put("ProfileService.Pb.ReqSystemMsgNew.Group", new String[]{str});
        f195514b.put("ProfileService.Pb.ReqSystemMsgAction", new String[]{str});
        f195514b.put("PbMessageSvc.PbMsgReadedReport", new String[]{str});
        f195514b.put("MessageSvc.PbReceiptRead", new String[]{str});
        f195514b.put("OidbSvc.0xb31", new String[]{str});
        Map<String, String[]> map2 = f195514b;
        String str3 = BusinessHandlerFactory.QAV_HANDLER;
        map2.put("QQRTCSvc.group_video_create_share_url", new String[]{str3});
        f195514b.put("QQRTCSvc.push_share_ark", new String[]{str3});
        f195514b.put("QQRTCSvc.share_backflow_check_group_can_join", new String[]{str3});
        f195514b.put("QQRTCSvc.group_video_share_backflow_verify", new String[]{str3});
        f195514b.put("QQRTCSvc.group_video_terminate_msg", new String[]{str3});
        Map<String, String[]> map3 = f195514b;
        String str4 = BusinessHandlerFactory.FRIENDLIST_HANDLER;
        map3.put("friendlist.delFriend", new String[]{str4});
        f195514b.put("friendlist.SetGroupReq", new String[]{str4});
        f195514b.put("friendlist.GetLastLoginInfoReq", new String[]{str4});
        f195514b.put("friendlist.getFriendGroupList", new String[]{str4});
        f195514b.put("OidbSvc.0xaed_0", new String[]{str4});
        f195514b.put("friendlist.MovGroupMemReq", new String[]{str4});
        f195514b.put("friendlist.GetSimpleOnlineFriendInfoReq", new String[]{str4});
        f195514b.put("BumpSvc.ReqComfirmContactFriend", new String[]{str4});
        f195514b.put("OidbSvc.0x777", new String[]{str4});
        f195514b.put("OidbSvc.0xc83", new String[]{str4});
        f195514b.put("OidbSvc.0xc85", new String[]{str4});
        f195514b.put(ProfileContants.CMD_GETSIMPLEINFO, new String[]{str4, BusinessHandlerFactory.WEREWOLVES_HANDLER});
        f195514b.put("OidbSvc.0x5d1_0", new String[]{str4});
        f195514b.put("OidbSvc.0x4fc_30", new String[]{str4});
        f195514b.put("DevLockAuthSvc.RecommendAuth", new String[]{str4});
        f195514b.put("DevLockAuthSvc.ConfirmAuth", new String[]{str4});
        f195514b.put("OidbSvc.0xcf0_0", new String[]{str4});
        f195514b.put("SummaryCard.ReqSearch", new String[]{str4});
        f195514b.put("SummaryCard.ReqCondSearch", new String[]{str4});
        f195514b.put("OidbSvc.0x972_5", new String[]{str4});
        f195514b.put(FaceConstant.AvatarHandlerCmd.CMD_GETQQHEAD, new String[]{FaceConstant.AVATAR_HANDLER});
        f195514b.put("StatSvc.register", new String[]{str4});
        f195514b.put(ProfileContants.CMD_GETSIGNATURE, new String[]{str4});
        f195514b.put(ProfileContants.CMD_REQ_RES_DEL_DEVLOGININFO, new String[]{str4});
        f195514b.put(ProfileContants.CMD_REQ_BINDUIN_STATE, new String[]{str4});
        f195514b.put(ProfileContants.CMD_REQ_KICKOUT_DEV, new String[]{str4});
        f195514b.put(ProfileContants.CMD_CHECK_UPDATE_REQ, new String[]{str4});
        f195514b.put(ProfileContants.CMD_SETCOMMENT, new String[]{str4});
        f195514b.put(ProfileContants.CMD_SETSIGNATURE, new String[]{str4});
        Map<String, String[]> map4 = f195514b;
        String str5 = BusinessHandlerFactory.AVATAR_HANDLER;
        map4.put(FaceConstant.AvatarHandlerCmd.CMD_GETQQHEAD_NEW, new String[]{str5, BusinessHandlerFactory.QCIRCLE_HANDLER});
        f195514b.put("MultibusidURLSvr.HeadUrlReq", new String[]{str5});
        f195514b.put("MultibusidURLSvr.HeadUrlReq", new String[]{str5});
        f195514b.put(FaceConstant.AvatarHandlerCmd.CMD_GET_APOLLO_HEAD, new String[]{str5});
        f195514b.put(FaceConstant.AvatarHandlerCmd.CMD_GET_QQ_HEAD_NT, new String[]{str5});
        f195514b.put(ProfileContants.CMD_REQ_RES_GET_DEVLOGININFO, new String[]{str4});
        f195514b.put("friendlist.GetOnlineInfoReq", new String[]{str4});
        f195514b.put("OidbSvc.0x49d_107", new String[]{str4});
        f195514b.put("OidbSvc.0x476_146", new String[]{str4});
        f195514b.put("OidbSvc.0x491_107", new String[]{str4});
        f195514b.put("OidbSvc.0x490_107", new String[]{str4});
        f195514b.put("OidbSvc.0x7c4_0", new String[]{str4});
        f195514b.put("OidbSvc.0x4f4_5", new String[]{str4});
        f195514b.put("OidbSvc.0x7c6_0", new String[]{str4});
        f195514b.put("OidbSvc.0x7c7_0", new String[]{str4});
        f195514b.put("OidbSvc.0x847_3", new String[]{str4});
        f195514b.put("OidbSvc.0x53b_0", new String[]{str4});
        f195514b.put("OidbSvc.0x7df_3", new String[]{str4});
        f195514b.put("OidbSvc.0x5d6_7", new String[]{str4});
        f195514b.put("OidbSvc.0x5d6_18", new String[]{str4});
        f195514b.put("OidbSvc.0x5d6_19", new String[]{str4});
        f195514b.put("OidbSvc.0x77c", new String[]{str4});
        f195514b.put("OidbSvc.0x5d6_21", new String[]{str4});
        f195514b.put("OidbSvc.0xc26_0", new String[]{str4});
        f195514b.put("OidbSvc.0xc36_0", new String[]{str4});
        f195514b.put("OidbSvc.0x5d6_21", new String[]{str4});
        Map<String, String[]> map5 = f195514b;
        String str6 = BusinessHandlerFactory.NEARBY_CARD_HANDLER;
        map5.put("VisitorSvc.ReqFavorite", new String[]{str2, str6});
        f195514b.put("OidbSvc.0x8e6_1", new String[]{str6});
        f195514b.put("OidbSvc.0x8e7_1", new String[]{str6});
        f195514b.put("OidbSvc.0x491_100", new String[]{str2});
        f195514b.put("VisitorSvc.ReqGetVoterList", new String[]{str2});
        f195514b.put("VisitorSvc.ReqGetFavoriteList", new String[]{str2});
        f195514b.put(ProfileCardServlet.CMD_REQ_SUMMARY_CARD, new String[]{str6});
        f195514b.put("MCardSvc.ReqDelFace", new String[]{str2});
        f195514b.put("MCardSvc.ReqGetCardSwitch", new String[]{str2});
        f195514b.put("MCardSvc.ReqPicSafetyCheck", new String[]{str2});
        f195514b.put("MCardSvc.ReqSetCard", new String[]{str2});
        f195514b.put("MCardSvc.ReqSetCardSwitch", new String[]{str2});
        f195514b.put("OidbSvc.0x490_100", new String[]{str2});
        f195514b.put("SummaryCard.SetLabel", new String[]{str2});
        f195514b.put("SummaryCard.LikeIt", new String[]{str2});
        f195514b.put("SQQzoneSvc.getCover", new String[]{str2, str6});
        Map<String, String[]> map6 = f195514b;
        String str7 = BusinessHandlerFactory.NEARBY_RELEVANT_HANDLER;
        map6.put(ProfileContants.CMD_SET_DETAIL_INFO, new String[]{str2, str7, BusinessHandlerFactory.FLASH_CHAT_HANDLER});
        f195514b.put(ProfileContants.CMD_UPLOAD_QZONE_PHOTO, new String[]{str2});
        Map<String, String[]> map7 = f195514b;
        String str8 = BusinessHandlerFactory.CONFIG_HANDLER;
        map7.put("OidbSvc.0x82f_0", new String[]{str8});
        f195514b.put("OidbSvc.0x82f_0", new String[]{str8});
        f195514b.put("OidbSvc.0x9ae_2", new String[]{str8});
        f195514b.put(ProfileContants.CMD_GET_NOTIFY_ON_LIKE_RANKING_LIST, new String[]{str2});
        f195514b.put(ProfileContants.CMD_GET_PARTAKE_LIKE_RANKING_LIST, new String[]{str2});
        f195514b.put(ProfileContants.CMD_GET_LIKE_RANKING_LIST, new String[]{str2});
        f195514b.put("VisitorSvc.ReqDeleteVisitorRecord", new String[]{str2});
        f195514b.put("OidbSvc.0xd2d", new String[]{str2});
        f195514b.put(ProfileContants.CMD_GET_PRETTY_TROOP_OWNER_FLAG, new String[]{str2});
        f195514b.put("MusicSongInfoMatchSvc.songquery", new String[]{BusinessHandlerFactory.MUSIC_PLAYER_HANDLER});
        Map<String, String[]> map8 = f195514b;
        String str9 = BusinessHandlerFactory.EXTEND_FRIEND_HANDLER;
        map8.put("OidbSvc.0xb4b", new String[]{str9});
        f195514b.put("OidbSvc.0xb4b_6", new String[]{str9});
        f195514b.put("OidbSvc.0xb4c", new String[]{str9});
        f195514b.put("OidbSvc.0xb51", new String[]{str9});
        f195514b.put("OidbSvc.0xcb5", new String[]{str9});
        f195514b.put("OidbSvc.0xdb1_2", new String[]{str9});
        f195514b.put("OidbSvc.0xe52_3", new String[]{str9});
        f195514b.put("OidbSvc.0xe03", new String[]{str9});
        f195514b.put("OidbSvc.0xe09", new String[]{str9});
        f195514b.put("OidbSvc.0xe51", new String[]{str9});
        f195514b.put("OidbSvc.0xe67", new String[]{str9});
        f195514b.put("OidbSvc.0xeae", new String[]{str9});
        f195514b.put("OidbSvc.0xeaf", new String[]{str9});
        f195514b.put("OidbSvc.0x1004", new String[]{str9});
        Map<String, String[]> map9 = f195514b;
        String str10 = BusinessHandlerFactory.ANONYMOUS_ANSWER_HANDLER;
        map9.put(AnonymousHandler.CMD_LIKE_ANONYMOUS_ANSWER, new String[]{str10});
        f195514b.put(AnonymousHandler.CMD_BROWSE_ASK_ANONYMOUSLY_REPORT, new String[]{str10});
        f195514b.put(AnonymousHandler.CMD_GET_LATEST_ANONYMOUS_INFO, new String[]{str10});
        f195514b.put(AnonymousHandler.CMD_REPLY_TROOP_ASK_ANONYMOUSLY, new String[]{str10});
        Map<String, String[]> map10 = f195514b;
        String str11 = BusinessHandlerFactory.LBS_HANDLER;
        map10.put("NeighborSvc.ReqGetSwitches", new String[]{str11});
        f195514b.put("NeighborSvc.ReqSetStateSwitch", new String[]{str11});
        f195514b.put("NeighborSvc.ReqGetPoint", new String[]{str11});
        f195514b.put("OidbSvc.0x7f5_1", new String[]{str11});
        f195514b.put("LbsShareSvr.nearby_shops", new String[]{str11});
        f195514b.put("LbsShareSvr.location", new String[]{str11});
        f195514b.put("LbsShareSvr.get_shops_by_ids", new String[]{str11});
        f195514b.put("OidbSvc.0x9c0_0", new String[]{str11});
        f195514b.put("OidbSvc.0x9c1_0", new String[]{str11});
        f195514b.put("ConfigService.ClientReq", new String[]{str8});
        f195514b.put("ResourceConfig.GetResourceReq", new String[]{str8});
        f195514b.put("MobileTipsSvc.TipsReport", new String[]{str8});
        f195514b.put("MAAControl.CheckSinglePkgSig", new String[]{str8});
        f195514b.put("MAAControl.GetSinglePkgSig", new String[]{str8});
        Map<String, String[]> map11 = f195514b;
        String str12 = BusinessHandlerFactory.DISCUSSION_HANDLER;
        map11.put("QQServiceDiscussSvc.ReqGetDiscussInteRemark", new String[]{str12});
        f195514b.put("QRCodeSvc.discuss_geturl", new String[]{str12});
        f195514b.put("OidbSvc.0x58a", new String[]{str12});
        f195514b.put("QQServiceDiscussSvc.ReqCreateDiscuss", new String[]{str12});
        f195514b.put("QRCodeSvc.discuss_decode", new String[]{str12});
        f195514b.put("QQServiceDiscussSvc.ReqJoinDiscuss", new String[]{str12});
        f195514b.put("QQServiceDiscussSvc.ReqSetDiscussFlag", new String[]{str12});
        f195514b.put("QQServiceDiscussSvc.ReqChangeDiscussName", new String[]{str12});
        f195514b.put("QQServiceDiscussSvc.ReqAddDiscussMember", new String[]{str12});
        f195514b.put("QQServiceDiscussSvc.ReqSetDiscussAttr", new String[]{str12});
        f195514b.put("QQServiceDiscussSvc.ReqGetDiscussInfo", new String[]{str12});
        f195514b.put("OidbSvc.0x58b_0", new String[]{str12});
        f195514b.put("QQServiceDiscussSvc.ReqQuitDiscuss", new String[]{str12});
        f195514b.put("OidbSvc.0x865_3", new String[]{str12});
        f195514b.put("OidbSvc.0x870_4", new String[]{str12});
        f195514b.put("OidbSvc.0x870_5", new String[]{str12});
        f195514b.put("OidbSvc.0x921_0", new String[]{str12});
        f195514b.put("OidbSvc.0x44c", new String[]{str12});
        f195514b.put("QzoneService.GetNewAndUnread", new String[]{BusinessHandlerFactory.QZONENOTIFY_HANDLER});
        Map<String, String[]> map12 = f195514b;
        String str13 = BusinessHandlerFactory.REGPRXYSVCPACK_HANDLER;
        map12.put("RegPrxySvc.infoAndroid", new String[]{str13});
        f195514b.put("StatSvc.GetOnlineStatus", new String[]{str13});
        f195514b.put("RegPrxySvc.QueryIpwdStat", new String[]{str13});
        f195514b.put("StatSvc.SetMute", new String[]{str13});
        f195514b.put("PubAccountSvc.ReportLbs", new String[]{BusinessHandlerFactory.HANDLER_PUBLIC_ACCOUNT});
        Map<String, String[]> map13 = f195514b;
        String str14 = BusinessHandlerFactory.HANDLER_EMOSM;
        map13.put("BQMallSvc.TabOpReq", new String[]{str14});
        f195514b.put("OidbSvc.0x490_92", new String[]{str14});
        f195514b.put("OidbSvc.0x5eb_99", new String[]{str14});
        f195514b.put("OidbSvcTrpcTcp.0x127c_0", new String[]{str14});
        f195514b.put("gxzbIpsit.ipsite", new String[]{str14});
        Map<String, String[]> map14 = f195514b;
        String str15 = BusinessHandlerFactory.SVIP_HANDLER;
        map14.put(ProfileContants.CMD_REQ_RES_UPDATE_NEW, new String[]{str15});
        f195514b.put(ProfileContants.CMD_REQ_RES_VIP_FONT_FRESH, new String[]{str15});
        f195514b.put("FriendClone.CloneAuthStatus", new String[]{str15});
        f195514b.put("groupnick.readitem", new String[]{str15});
        f195514b.put("profilelogic.readUserInfo", new String[]{str15});
        f195514b.put("profilelogic.setUserFlag", new String[]{str15});
        f195514b.put("profilelogic.setUserProfile", new String[]{str15});
        f195514b.put("FontBubbleRecommend.getFontRecommend", new String[]{str15});
        f195514b.put("FontBubbleRecommend.getBubbleRecommend", new String[]{str15});
        f195514b.put("GroupCare.getMessageRemindInfo", new String[]{str15});
        f195514b.put("FontBubbleRecommend.setFontBubble", new String[]{str15});
        f195514b.put("RoamWrap.GetRoamToast", new String[]{str15});
        f195514b.put("Face.setFace", new String[]{str15});
        f195514b.put("QCUniBusinessLogin.check", new String[]{str15});
        f195514b.put("ProfileMusicBox.getMusicList", new String[]{str15});
        f195514b.put("ProfileMusicBox.getQzoneMusicInfo", new String[]{str15});
        f195514b.put(VipFunCallConstants.CMD_FUN_CALL_SVR, new String[]{BusinessHandlerFactory.FUN_CALL_HANDLER});
        f195514b.put("voiceChange.Auth", new String[]{BusinessHandlerFactory.CHANGE_VOICE_HANDLER});
        Map<String, String[]> map15 = f195514b;
        String str16 = BusinessHandlerFactory.THEME_HANDLER;
        map15.put(ThemeConstants.CMD_THEME_AUTH, new String[]{str16});
        f195514b.put(ThemeConstants.CMD_REQ_GET_0X5EB_FOR_THEME, new String[]{str16});
        f195514b.put("SpecialRemind.Service", new String[]{BusinessHandlerFactory.SPECIAL_CARE_HANDLER});
        f195514b.put("ClubContentUpdate.Req", new String[]{BusinessHandlerFactory.CLUBCONTENTUPDATE_HANDLER});
        Map<String, String[]> map16 = f195514b;
        String str17 = BusinessHandlerFactory.SHIELD_LIST_HANDLER;
        map16.put("SsoSnsSession.Cmd0x3_SubCmd0x3_FuncDelBlockList", new String[]{str17});
        f195514b.put("SsoSnsSession.Cmd0x3_SubCmd0x1_FuncGetBlockList", new String[]{str17});
        f195514b.put("SsoSnsSession.Cmd0x3_SubCmd0x2_FuncAddBlockList", new String[]{str17});
        Map<String, String[]> map17 = f195514b;
        String str18 = BusinessHandlerFactory.ENTERPRISEQQ_HANDLER;
        map17.put("mq_crm.get_menu", new String[]{str18});
        f195514b.put("mq_crm.send_key", new String[]{str18});
        f195514b.put("EqqAccountSvc.get_eqq_list", new String[]{str18});
        f195514b.put("CrmSvcEx.ReportLbs", new String[]{str18});
        Map<String, String[]> map18 = f195514b;
        String str19 = BusinessHandlerFactory.TROOP_FILE_HANDLER;
        map18.put("GroupFileAppSvr.DelFile", new String[]{str19});
        f195514b.put("GroupFileAppSvr.GetFileInfo", new String[]{str19});
        f195514b.put("GroupFileAppSvr.GetFileSearch", new String[]{str19});
        f195514b.put("GroupFileAppSvr.GetFileList", new String[]{str19});
        f195514b.put("GroupFileAppSvr.GetFileListV2", new String[]{str19});
        Map<String, String[]> map19 = f195514b;
        String str20 = BusinessHandlerFactory.VIPINFO_HANDLER;
        map19.put("ClubInfoSvc.queryPrivExt", new String[]{str20});
        f195514b.put("ClubInfoSvc.guanjiaReport", new String[]{str20});
        f195514b.put("VipCustom.GetCustomOnlineStatus", new String[]{str20});
        f195514b.put("QCUniBusinessLogic.uniSet", new String[]{str20});
        f195514b.put("QCUniBusinessLogic.uniGet", new String[]{str20});
        f195514b.put(RedTouchConst.Cmd.CMD_RED_TOUCH_ENTRANCE_SETTING, new String[]{BusinessHandlerFactory.LEBA_SETTING_HANDLER});
        Map<String, String[]> map20 = f195514b;
        String str21 = BusinessHandlerFactory.SEC_SVC_HANDLER;
        map20.put("SecuritySvc.GetConfig", new String[]{str21});
        f195514b.put("DevLockAuthSvc.WxMsgOpt", new String[]{str21});
        f195514b.put("DevLockSecSvc.DevLockQuery", new String[]{str21});
        f195514b.put("OidbSvc.0x614_1", new String[]{str21});
        f195514b.put("OidbSvc.0xa13", new String[]{str21});
        f195514b.put("OidbSvc.0x4ad", new String[]{str21});
        f195514b.put("SecuritySvc.AlertReport", new String[]{str21});
        f195514b.put("OidbSvc.0xeb8", new String[]{str21});
        f195514b.put("OidbSvc.0xebd", new String[]{str21});
        f195514b.put("OidbSvc.0xec0", new String[]{str21});
        Map<String, String[]> map21 = f195514b;
        String str22 = BusinessHandlerFactory.MSF_NET_TRANSPORT_PROVIDER_HANDLER;
        map21.put("SecCheckSigSvc.UploadReq", new String[]{BusinessHandlerFactory.STARTAPPCHECK_HANDLER, str22});
        f195514b.put("SecSafeChkSvc.MainCmd", new String[]{str22});
        f195514b.put("SecIntChkSvc.MainCmd", new String[]{str22});
        Map<String, String[]> map22 = f195514b;
        String str23 = BusinessHandlerFactory.NEARFIELD_DISCUSS_HANDLER;
        map22.put("NearFieldDiscussSvr.ReqJoinDiscuss", new String[]{str23});
        f195514b.put("NearFieldDiscussSvr.ReqGetList", new String[]{str23});
        f195514b.put("NearFieldDiscussSvr.ReqExit", new String[]{str23});
        f195514b.put("NearFieldDiscussSvr.NotifyList", new String[]{str23});
        f195514b.put("hrtxformqq.getUsrSimpleInfo", new String[]{BusinessHandlerFactory.BMQQ_BUSINESS_HANDLER});
        Map<String, String[]> map23 = f195514b;
        String str24 = BusinessHandlerFactory.QWALLET_AUTH_HANDLER;
        map23.put("QQWalletPayAuthServer.checkChangePwdAuth", new String[]{str24});
        f195514b.put("WalletGestureSvc.GetPassword", new String[]{str24});
        f195514b.put("VacThirdCodeSvc.fetchCodes", new String[]{str24});
        f195514b.put("QWalletPfa.RecFriend", new String[]{str24});
        f195514b.put("VipSTCheckServer.UinPay", new String[]{BusinessHandlerFactory.UNI_PAY_HANDLER});
        f195514b.put("ComicProtoConvSvr.tunnel", new String[]{BusinessHandlerFactory.MQQ_COMIC_HANDLER});
        f195514b.put("QcallOidbSvc.0x5e3_1", new String[]{BusinessHandlerFactory.QCALLCARD_HANDLER});
        f195514b.put("Background.checkAuth", new String[]{BusinessHandlerFactory.CHATBG_AUTH});
        f195514b.put("red_touch_num_svr.get_num_msg", new String[]{BusinessHandlerFactory.NUMREDMSG_HANDLER});
        f195514b.put(com.tencent.mobileqq.service.message.i.D, new String[]{BusinessHandlerFactory.REDPOINT_HANDER});
        f195514b.put("VipPayLogicServer.getCommPayInfo ", new String[]{BusinessHandlerFactory.VIPRECOMMENDPAY_HANDLER});
        f195514b.put("QPayReminderSvc.query_over_due_info", new String[]{BusinessHandlerFactory.QPAY_HANDLER});
        Map<String, String[]> map24 = f195514b;
        String str25 = BusinessHandlerFactory.NEARFIELD_TROOP_HANDLER;
        map24.put("NearfieldGroupSvr.ReqGetGroupList", new String[]{str25});
        f195514b.put("NearfieldGroupSvr.ReqExit", new String[]{str25});
        f195514b.put("NearfieldGroupSvr.ReqJoinGroup", new String[]{str25});
        f195514b.put("Loginauth.1", new String[]{BusinessHandlerFactory.PPC_LOGIN_AUTH});
        f195514b.put("OidbSvc.0x5cf_0", new String[]{str});
        f195514b.put("OidbSvc.0x5cf_1", new String[]{str});
        f195514b.put("OidbSvc.0x9c9_0", new String[]{str6});
        f195514b.put("OidbSvc.0x9c9_1", new String[]{str6});
        f195514b.put("OidbSvc.0xb5b", new String[]{str6});
        f195514b.put("OidbSvc.0x9c5_0", new String[]{str6});
        f195514b.put("OidbSvc.0x9c8_0", new String[]{str6});
        f195514b.put("OidbSvc.0x9c7_0", new String[]{str6});
        f195514b.put("OidbSvc.0x9e4_22", new String[]{str7});
        f195514b.put("OidbSvc.0x682", new String[]{str6});
        Map<String, String[]> map25 = f195514b;
        String str26 = BusinessHandlerFactory.SUBSCRIPT_HANDLER;
        map25.put("OidbSvc.1081", new String[]{str26});
        f195514b.put("OidbSvc.0x472", new String[]{str26});
        f195514b.put("OidbSvc.0x4ff_41993", new String[]{str7});
        f195514b.put("bubble.1", new String[]{BusinessHandlerFactory.BUBBLE_DIYTEXT_HANDLER});
        Map<String, String[]> map26 = f195514b;
        String str27 = BusinessHandlerFactory.FAVEMO_ROAMING_HANDLER;
        map26.put(FavEmoConstant.CMD_FAV_ROAMING, new String[]{str27});
        f195514b.put(FavEmoConstant.CMD_FAV_OCR, new String[]{str27});
        f195514b.put(FavEmoConstant.CMD_FAV_MOVE, new String[]{str27});
        f195514b.put("SelfGif.Op", new String[]{BusinessHandlerFactory.CAMERA_EMOTICON_HANDLER});
        f195514b.put("OidbSvc.0x66b", new String[]{str2, str6});
        f195514b.put("OidbSvc.0x682", new String[]{str6});
        f195514b.put(ProfileContants.CMD_REQ_NEARBY_CHARM_EVENT, new String[]{str6});
        f195514b.put(ProfileContants.CMD_UPDATE_NEARBY_PEOPLE_PHOTO_LIST, new String[]{str6});
        f195514b.put(ProfileContants.CMD_IMPORT_QZONE_PHOTOES, new String[]{str6});
        f195514b.put(ProfileContants.CMD_QUERY_IMPORT_QZONE_PHOTOES_STATUS, new String[]{str6});
        f195514b.put(ProfileContants.CMD_SET_NEARBY_PEOPLE_VIDEO_ID, new String[]{str6});
        f195514b.put(ProfileContants.CMD_DELETE_NEARBY_PEOPLE_VIDEO_ID, new String[]{str6});
        Map<String, String[]> map27 = f195514b;
        String str28 = VIPAioSendHandler.f195181f;
        String str29 = BusinessHandlerFactory.VIP_AIO_SEND_HANDLER;
        map27.put(str28, new String[]{str29});
        f195514b.put(VIPAioSendHandler.f195182h, new String[]{str29});
        f195514b.put("OidbSvc.0x59f", new String[]{BusinessHandlerFactory.LOGIN_WELCOME_HANDLER});
        Map<String, String[]> map28 = f195514b;
        String str30 = BusinessHandlerFactory.QIDIAN_HANDLER;
        map28.put("QidianSsoProto.WpaAssignKfext", new String[]{str30});
        f195514b.put("QidianSsoProto.clickReplyCmd", new String[]{str30});
        f195514b.put("QidianSsoProto.getUserDetailInfo", new String[]{str30});
        f195514b.put("QidianSsoProto.verifyWpaAndKey", new String[]{str30});
        f195514b.put("QidianSsoProto.getShieldStatus", new String[]{str30});
        f195514b.put("trpc.b2b.wpa.Wpa.SsoGetUID", new String[]{str30});
        f195514b.put("QidianSsoProto.blockBulkMsg", new String[]{str30});
        f195514b.put("QidianSsoProto.getCustomerTransferInfo", new String[]{str30});
        f195514b.put("QidianSsoProto.getNavigationConfig", new String[]{str30});
        f195514b.put("QidianSsoProto.corpUinWpaReport", new String[]{str30});
        f195514b.put("QidianSsoProto.fetchCorpDetailInfo", new String[]{str30});
        f195514b.put("OidbSvc.0x7e7_0", new String[]{str30});
        f195514b.put("QidianSsoProto.emanClickReport", new String[]{str30});
        f195514b.put("QidianSsoProto.closeAIOSessionReport", new String[]{str30});
        f195514b.put("QidianSsoProto.WpaGenSigMsg", new String[]{str30});
        f195514b.put("QidianSsoProto.webimAddFriend", new String[]{str30});
        f195514b.put("QidianSsoProto.getQidianGroupInfo", new String[]{str30});
        f195514b.put("OidbSvc.0x782", new String[]{str30});
        Map<String, String[]> map29 = f195514b;
        String str31 = BusinessHandlerFactory.EC_SHOP_REPORT_HANDLER;
        map29.put("SQQShopCliLog.RtReport", new String[]{str31});
        f195514b.put("SQQShopMsgSvc.GetRichMsgInfo", new String[]{str31});
        f195514b.put("SQQShopCliLog.AdFeedback", new String[]{str31});
        f195514b.put("OidbSvc.0x8dd", new String[]{BusinessHandlerFactory.NEARBY_HANDLER});
        Map<String, String[]> map30 = f195514b;
        String str32 = BusinessHandlerFactory.PUBLIC_ACCOUNT_VIDEO_HANDLER;
        map30.put(IPublicAccountArticleHandler.CMD_ARTICLE_LIKE, new String[]{str32});
        f195514b.put(IPublicAccountArticleHandler.CMD_CHECK_ARTICLE_LIKE, new String[]{str32});
        f195514b.put(IPublicAccountArticleHandler.CMD_GET_ARTICLE_LIKE_COUNT, new String[]{str32});
        f195514b.put(IPublicAccountArticleHandler.CMD_CREATE_ARTICLE_COMMENT, new String[]{str32});
        f195514b.put(IPublicAccountArticleHandler.CMD_GET_ARTICLE_COMMENT_COUNT, new String[]{str32});
        f195514b.put(IPublicAccountArticleHandler.CMD_GET_PHOTO_COLLECTION_INFO, new String[]{str32});
        f195514b.put(IPublicAccountArticleHandler.CMD_GET_RECOMMEND_INFO, new String[]{str32});
        f195514b.put(IPublicAccountArticleHandler.CMD_REPORT_READ_PHOTO_COLLECTION, new String[]{str32});
        Map<String, String[]> map31 = f195514b;
        String str33 = BusinessHandlerFactory.REDTOUCH_HANDLER;
        map31.put("OidbSvc.cmd0x6cd", new String[]{str33});
        f195514b.put("OidbSvc.cmd0x6ce", new String[]{str33});
        f195514b.put("OidbSvc.cmd0x6f5", new String[]{str33});
        f195514b.put("OidbSvc.0x74b", new String[]{BusinessHandlerFactory.DYNAMIC_AVATAR_HANDLER});
        Map<String, String[]> map32 = f195514b;
        String str34 = BusinessHandlerFactory.PROFILE_PERSONALITY_LABEL;
        map32.put("OidbSvc.0x8f0", new String[]{str34});
        f195514b.put("OidbSvc.0x91d", new String[]{str34});
        f195514b.put("OidbSvc.0x909", new String[]{str34});
        f195514b.put("OidbSvc.0x90c", new String[]{str34});
        f195514b.put("OidbSvc.0x8f3", new String[]{str34});
        f195514b.put("OidbSvc.0x8f1", new String[]{str34});
        f195514b.put("OidbSvc.0x4ff_42073", new String[]{str8});
        f195514b.put("OidbSvc.0x5eb_42073", new String[]{str8});
        f195514b.put(NearbyPeoplePicUpHandler.CMD_GET_IP_LIST, new String[]{BusinessHandlerFactory.BIG_DATA_GET_IP_HANDLER});
        f195514b.put(ProfileContants.CMD_GET_SIGNIN_RED_TOUCH, new String[]{str2});
        f195514b.put(ProfileContants.CMD_GET_SIGNIN_OPRATION_CONTENT, new String[]{str2});
        f195514b.put(ProfileContants.CMD_GET_KPL_INFO, new String[]{str2});
        f195514b.put(ProfileContants.CMD_REPORT_MEDALWALL_READ, new String[]{str2});
        f195514b.put(ProfileContants.CMD_GET_MEDALWALL_INFO, new String[]{str2});
        f195514b.put("trpc.qqshop.adpush.PushService.GetAd", new String[]{BusinessHandlerFactory.ESHOP_AD_HANDLER});
        Map<String, String[]> map33 = f195514b;
        String str35 = BusinessHandlerFactory.UNIFY_SEARCH_UNITE_HANDLER;
        map33.put("UnifySearch.Tab", new String[]{str35});
        f195514b.put("UnifySearch.GroupDiscovery", new String[]{str35});
        f195514b.put("dynamic_tab_search.1", new String[]{BusinessHandlerFactory.UNITE_SEARCH_HANDLER});
        f195514b.put("ReadDiyAddonInfo.1", new String[]{BusinessHandlerFactory.DIY_PENDANT_HANDLER});
        Map<String, String[]> map34 = f195514b;
        String str36 = BusinessHandlerFactory.TEAM_WORK_HANDLER;
        map34.put(ITeamWorkHandler.CMD_GET_PAD_RIGHT_INFO, new String[]{str36});
        f195514b.put(ITeamWorkHandler.CMD_SET_PAD_RIGHT_INFO, new String[]{str36});
        f195514b.put(ITeamWorkHandler.CMD_GET_SHARED_LIST, new String[]{str36});
        f195514b.put(ITeamWorkHandler.CMD_GET_USER_AUTH_DOCS_TIPS_INFO, new String[]{str36});
        f195514b.put(ITeamWorkHandler.CMD_SET_USER_AUTH_DOCS_TIPS_INFO, new String[]{str36});
        f195514b.put(ITeamWorkHandler.CMD_GET_GROUP_AUTH_DOCS_TIPS_INFO, new String[]{str36});
        f195514b.put(ITeamWorkHandler.CMD_SET_GROUP_AUTH_DOCS_TIPS_INFO, new String[]{str36});
        Map<String, String[]> map35 = f195514b;
        String str37 = BusinessHandlerFactory.CONFESS_HANDLER;
        map35.put("OidbSvc.cmd0xb67", new String[]{str37});
        f195514b.put("NowGetRecordInfoSvr.get_record_info", new String[]{BusinessHandlerFactory.NOW_PROXY_HANDLER});
        f195514b.put("OidbSvc.cmd0xbc3", new String[]{str37});
        Map<String, String[]> map36 = f195514b;
        String str38 = BusinessHandlerFactory.CONTACT_BIND_HANDLER;
        map36.put("OidbSvc.0xbe8", new String[]{str38});
        f195514b.put("OidbSvc.0xbf2", new String[]{str38});
        f195514b.put(ProfileContants.CMD_GET_BIND_PHONE_SWITCH_INFO, new String[]{str2});
        Map<String, String[]> map37 = f195514b;
        String str39 = BusinessHandlerFactory.CARD_SETTING_HANDLER;
        map37.put("OidbSvc.0x5eb_22", new String[]{str2, str39});
        f195514b.put("OidbSvc.0x5eb_15", new String[]{str2});
        Map<String, String[]> map38 = f195514b;
        String str40 = BusinessHandlerFactory.GROUP_TEAM_WORK_HANDLER;
        map38.put(IGroupTeamWorkHandler.CMD_GET_GROUP_TEAM_WORK_LIST, new String[]{str40});
        f195514b.put(IGroupTeamWorkHandler.CMD_SEARCH_FOR_GROUP_TEAM_WORK_LIST, new String[]{str40});
        f195514b.put(IGroupTeamWorkHandler.CMD_GET_GROUP_PAD_TEMPLATE_LIST, new String[]{str40});
        f195514b.put(IGroupTeamWorkHandler.CMD_DELETE_GROUP_TEAM_WORK_FILE, new String[]{str40});
        f195514b.put(IGroupTeamWorkHandler.CMD_ADD_GROUP_TEAM_WORK_LINK, new String[]{str40});
        f195514b.put(IGroupTeamWorkHandler.CMD_ADD_GROUP_TEAM_WORK_COPY, new String[]{str40});
        f195514b.put(IGroupTeamWorkHandler.CMD_GET_GOURP_TEAM_WORK_LAST_ADD_TIME, new String[]{str40});
        Map<String, String[]> map39 = f195514b;
        String str41 = BusinessHandlerFactory.APPLET_PUSH_HANDLER;
        map39.put("OidbSvc.0xc7a", new String[]{str41});
        f195514b.put("OidbSvc.0xc76", new String[]{str41});
        f195514b.put("OidbSvc.0xc96", new String[]{str41});
        Map<String, String[]> map40 = f195514b;
        String str42 = BusinessHandlerFactory.INPUT_STATUS_HANDLER;
        map40.put("OidbSvc.0x5eb_42261", new String[]{str42});
        f195514b.put("OidbSvc.0x4ff_42261", new String[]{str42});
        f195514b.put(ProfileContants.CMD_AUTO_REPLY, new String[]{str2});
        Map<String, String[]> map41 = f195514b;
        String str43 = BusinessHandlerFactory.OPEN_AGENT_HANDLER;
        map41.put("OidbSvc.0xc05", new String[]{str43});
        f195514b.put("OidbSvc.0xccd", new String[]{str43});
        f195514b.put("OidbSvc.0xf26", new String[]{str43});
        Map<String, String[]> map42 = f195514b;
        String str44 = BusinessHandlerFactory.INTIMATE_INFO_HANDLER;
        map42.put("OidbSvc.0xcf3", new String[]{str44});
        f195514b.put("OidbSvc.0xcf4", new String[]{str44});
        f195514b.put("OidbSvcTrpcTcp.0x1250_0", new String[]{str44});
        f195514b.put("OidbSvcTrpcTcp.0x1254_0", new String[]{str44});
        f195514b.put("OidbSvcTrpcTcp.0x127b_1", new String[]{str44});
        f195514b.put("OidbSvc.0xe3e", new String[]{str44});
        Map<String, String[]> map43 = f195514b;
        String str45 = BusinessHandlerFactory.COMMPLGUGIN_HANDLER;
        map43.put("PluginConfig.dynamic_plugin", new String[]{str45});
        f195514b.put("OidbSvc.0xd8a", new String[]{str2});
        f195514b.put("OidbSvc.0x4ff_42315", new String[]{str2});
        Map<String, String[]> map44 = f195514b;
        String str46 = BusinessHandlerFactory.SIMPLE_UI_HANDLER;
        map44.put("OidbSvc.0x5eb_SimpleUI", new String[]{str46});
        f195514b.put("OidbSvc.0xed1_SimpleUI", new String[]{str46});
        f195514b.put("OidbSvc.0x5eb_ExpLebaFrameMode", new String[]{str46});
        f195514b.put("OidbSvc.0xd45", new String[]{str44});
        f195514b.put("OidbSvc.0xcf4_1", new String[]{str44});
        f195514b.put("OidbSvc.0xd4a", new String[]{str44});
        Map<String, String[]> map45 = f195514b;
        String str47 = BusinessHandlerFactory.LISTEN_TOGETHER_HANDLER;
        String str48 = BusinessHandlerFactory.TOGETHER_OPERATOR_HANDLER;
        map45.put("QQAIOMediaSvc.get_latest_playing_state", new String[]{str47, str48});
        f195514b.put("QQAIOMediaSvc.create_room", new String[]{str47, str48});
        f195514b.put("QQAIOMediaSvc.heartbeat", new String[]{str47, str48});
        f195514b.put("QQAIOMediaSvc.get_song_extended_info", new String[]{str47});
        f195514b.put("QQAIOMediaSvc.media_operation", new String[]{str47});
        f195514b.put("QQAIOMediaSvc.room_operation", new String[]{str47});
        f195514b.put("QQAIOMediaSvc.get_play_show_info", new String[]{str47});
        f195514b.put("QQAIOMediaSvc.share_trans_check", new String[]{str47});
        f195514b.put("QQAIOMediaSvc.share_trans", new String[]{str47});
        f195514b.put("QQAIOMediaSvc.report_download_fail", new String[]{str47});
        Map<String, String[]> map46 = f195514b;
        String str49 = BusinessHandlerFactory.LOCATION_HANDLER;
        map46.put("QQLBSShareSvc.room_operation", new String[]{str49});
        f195514b.put("QQLBSShareSvc.report_location", new String[]{str49});
        f195514b.put("QQLBSShareSvc.assembly_point_operation", new String[]{str49});
        f195514b.put("QQLBSShareSvc.room_query", new String[]{str49});
        f195514b.put(AECameraConstants.CMD_PARTICIPLE, new String[]{BusinessHandlerFactory.PARTICIPLE_HANDLER});
        f195514b.put("OidbSvc.0xd69", new String[]{str4});
        f195514b.put("OidbSvc.0xd72", new String[]{str4});
        Map<String, String[]> map47 = f195514b;
        String str50 = BusinessHandlerFactory.MSG_BACK_UP_HANDLER;
        map47.put("OidbSvc.0xcdd", new String[]{str50});
        f195514b.put("OidbSvc.0xcde", new String[]{str50});
        f195514b.put("OidbSvc.0xdc9", new String[]{BusinessHandlerFactory.TROOP_HONOR_HANDLER});
        f195514b.put("QQAIOMediaSvc.get_dynamic_info", new String[]{str48});
        f195514b.put("QQAIOMediaSvc.VideoWrite", new String[]{str48});
        Map<String, String[]> map48 = f195514b;
        String str51 = BusinessHandlerFactory.COLOR_NOTE_HANDLER;
        map48.put("OidbSvc.0x5eb_cn_switch", new String[]{str51});
        f195514b.put("OidbSvc.0x4ff_cn_switch", new String[]{str51});
        f195514b.put("OidbSvc.0x5eb_for_cold_start", new String[]{str51});
        Map<String, String[]> map49 = f195514b;
        String str52 = BusinessHandlerFactory.FACE2FACE_ADD_FRIEND_HANDLER;
        map49.put("NearFieldFriendSvr.ReqEnter", new String[]{str52});
        f195514b.put("NearFieldFriendSvr.ReqExit", new String[]{str52});
        f195514b.put("NearFieldFriendSvr.ReqHeartBeat", new String[]{str52});
        Map<String, String[]> map50 = f195514b;
        String str53 = BusinessHandlerFactory.TROOP_SHORTCUTBAR_HANDLE;
        map50.put("OidbSvc.0xe82", new String[]{str53});
        f195514b.put("OidbSvc.0xe0e", new String[]{str53});
        f195514b.put("OidbSvc.0xd68", new String[]{BusinessHandlerFactory.FAV_ONLINE_FILE_FORWARD_HANDLER});
        f195514b.put("trpc.qq_config.user_dynamic_plugin.UserDynamicPluginService.GetList", new String[]{str45});
        f195514b.put("trpc.qq_config.user_dynamic_plugin.UserDynamicPluginService.SetList", new String[]{str45});
        f195514b.put("OidbSvc.0x6e1_1", new String[]{BusinessHandlerFactory.TOFUMSG_HANDLER});
        f195514b.put("OidbSvc.0x587_74", new String[]{str39});
        f195514b.put("OidbSvc.0xe8c", new String[]{BusinessHandlerFactory.ONE_WAY_FRIEND_HANDLER});
        f195514b.put("OidbSvc.0x484_15", new String[]{BusinessHandlerFactory.QUICK_LOGIN});
        f195514b.put("OidbSvcTcp.0xea3", new String[]{str53});
        Map<String, String[]> map51 = f195514b;
        String str54 = BusinessHandlerFactory.C2C_SHORTCUT_BAR_HANDLER;
        map51.put("OidbSvc.oidb_0xeb5", new String[]{str54});
        f195514b.put("OidbSvc.oidb_0xd51", new String[]{str54});
        f195514b.put("OidbSvc.oidb_0x587", new String[]{str54});
        Map<String, String[]> map52 = f195514b;
        String str55 = BusinessHandlerFactory.TEENS_MODE_ALPHABETIC_FONT_HANDLER;
        map52.put("OidbSvc.0x5eb_42483", new String[]{str55});
        f195514b.put("OidbSvc.0x4ff_42483", new String[]{str55});
        f195514b.put("OidbSvc.0x5eb_42482", new String[]{str45});
        f195514b.put("OidbSvc.0x4ff_42482", new String[]{str45});
        f195514b.put("RedTouchSvc.BatchSetSetting", new String[]{str45});
        Map<String, String[]> map53 = f195514b;
        String str56 = BusinessHandlerFactory.TROOP_NOTIFICATION_HANDLER;
        map53.put("OidbSvc.0x5eb_troopnotifycation", new String[]{str56});
        f195514b.put("OidbSvc.0x668", new String[]{str56});
        Map<String, String[]> map54 = f195514b;
        String str57 = BusinessHandlerFactory.PAI_YI_PAI_HANDLER;
        map54.put("OidbSvc.0xed3", new String[]{str57});
        f195514b.put("OidbSvc.0xf51", new String[]{str57});
        Map<String, String[]> map55 = f195514b;
        String str58 = BusinessHandlerFactory.FILE_ASSIST_TOP;
        map55.put("OidbSvc.0x5eb_fst", new String[]{str58});
        f195514b.put("OidbSvc.oidb_0x587_fst", new String[]{str58});
        f195514b.put("OidbSvc.0xecc_0", new String[]{BusinessHandlerFactory.SECURITY_TOP_BAR});
        f195514b.put("OidbSvc.0x59f_newer_guide_banner", new String[]{BusinessHandlerFactory.NEWER_GUIDE_BANNER_HANDLER});
        f195514b.put("QQLive.GetLiveGroupTips", new String[]{BusinessHandlerFactory.ILIVE_COMMON_HANDLER});
        f195514b.put("OidbSvc.0xefe", new String[]{BusinessHandlerFactory.FILTER_MSG_BOX_HANDLER, SafeBlowHandler.f261333d});
        Map<String, String[]> map56 = f195514b;
        String str59 = BusinessHandlerFactory.TROOP_ROAMSETTING_HANDLER;
        map56.put("ProfileService.ReqGetSettings", new String[]{str59});
        f195514b.put("ProfileService.ReqSetSettings", new String[]{str59});
        f195514b.put("trpc.qq_new_tech.status_svc.StatusService.SsoChangeLockStatus", new String[]{BusinessHandlerFactory.LOCK_PC});
    }

    private static void f() {
        Map<String, String[]> map = f195514b;
        String str = com.tencent.mobileqq.nearby.e.f252574a;
        map.put("OidbSvc.0x8dd", new String[]{str});
        f195514b.put("RoamClientSvr.GetQualify", new String[]{str});
        f195514b.put("OidbSvc.0x66b", new String[]{str});
        f195514b.put("NeighborSvc.ReqGetPoint", new String[]{str});
        f195514b.put(ProfileContants.CMD_REQ_NEARBY_CHARM_EVENT, new String[]{str});
        f195514b.put("OidbSvc.0x9c7_0", new String[]{str});
        f195514b.put("OidbSvc.0x4f0_0", new String[]{str});
        f195514b.put("OidbSvc.0x6be", new String[]{str});
        f195514b.put("OidbSvc.0xafc_1", new String[]{str});
        f195514b.put("OidbSvc.0xafc_2", new String[]{str});
        f195514b.put("OidbSvc.0xafc_3", new String[]{str});
        f195514b.put("OidbSvc.0xada_0", new String[]{str});
        f195514b.put("MQ_nearby_sso_proxy.0x3e8_1", new String[]{str});
        f195514b.put("MultibusidURLSvr.HeadUrlReq", new String[]{com.tencent.mobileqq.nearby.e.f252575b});
        f195514b.put("OidbSvc.0x74b", new String[]{BusinessHandlerFactory.DYNAMIC_AVATAR_HANDLER});
    }

    private static void g() {
        Map<String, String[]> map = f195515c;
        String str = PeakAppInterface.I;
        map.put(AECameraConstants.CMD_EMOTION, new String[]{str});
        f195515c.put(AECameraConstants.CMD_TEXT_VALID, new String[]{str});
        f195515c.put(AECameraConstants.CMD_COMPRESSED_MATERIAL_CATEGORY, new String[]{str});
        f195515c.put("ShadowBackendSvc.GetPlayShowCatMatTree", new String[]{str});
        f195515c.put(AECameraConstants.CMD_CAMERA_CONFIG, new String[]{str});
        f195515c.put(AECameraConstants.CMD_QQ_ONLINE_NUMBER, new String[]{str});
        f195515c.put(AECameraConstants.CMD_GET_FONT_DATA, new String[]{str});
        f195515c.put(AECameraConstants.CMD_FACE_DETECT, new String[]{str});
        f195515c.put(AECameraConstants.CMD_SMART_FILTER, new String[]{str});
        f195515c.put(AECameraConstants.CMD_TAB_AB_TEST, new String[]{str});
        Map<String, String[]> map2 = f195515c;
        String str2 = PeakAppInterface.K;
        map2.put(AEEditorConstants.CMD_EDITOR_MATERIAL_CATEGORY, new String[]{str2});
        f195515c.put(AEEditorConstants.CMD_AUTO_TEMPLATE_RECOMMEND, new String[]{str2});
        f195515c.put(AECameraConstants.CMD_MATERIAL_RACE, new String[]{str});
        f195515c.put(AEEditorConstants.CMD_SUBTITLE_SUBMIT, new String[]{str});
        f195515c.put(AEEditorConstants.CMD_SUBTITLE_QUERY, new String[]{str});
        f195515c.put(AECameraConstants.CMD_WATERMARK_LOCATION, new String[]{str});
        f195515c.put(AECameraConstants.CMD_CAMERA_PROPERTY_AI, new String[]{str});
        f195515c.put(PhotoWallConstant.CMD_GET_PHOTO_WALL, new String[]{PeakAppInterface.L});
    }
}
