package com.tencent.superplayer.player;

/* compiled from: P */
/* loaded from: classes26.dex */
public class a {
    public static String a(int i3) {
        if (i3 == 193) {
            return "kTPCodecIdVVC";
        }
        switch (i3) {
            case 0:
                return "kTPCodecIdMPEG1VIDEO";
            case 1:
                return "kTPCodecIdMPEG2VIDEO";
            case 2:
                return "kTPCodecIdH261";
            case 3:
                return "kTPCodecIdH263";
            case 4:
                return "kTPCodecIdRV10";
            case 5:
                return "kTPCodecIdRV20";
            case 6:
                return "kTPCodecIdMJPEG";
            case 7:
                return "kTPCodecIdMJPEGB";
            case 8:
                return "kTPCodecIdLJPEG";
            case 9:
                return "kTPCodecIdSP5X";
            case 10:
                return "kTPCodecIdJPEGLS";
            case 11:
                return "kTPCodecIdMPEG4";
            case 12:
                return "kTPCodecIdRAWVIDEO";
            case 13:
                return "kTPCodecIdMSMPEG4V1";
            case 14:
                return "kTPCodecIdMSMPEG4V2";
            case 15:
                return "kTPCodecIdMSMPEG4V3";
            case 16:
                return "kTPCodecIdWMV1";
            case 17:
                return "kTPCodecIdWMV2";
            case 18:
                return "kTPCodecIdH263P";
            case 19:
                return "kTPCodecIdH263I";
            case 20:
                return "kTPCodecIdFLV1";
            case 21:
                return "kTPCodecIdSVQ1";
            case 22:
                return "kTPCodecIdSVQ3";
            case 23:
                return "kTPCodecIdDVVIDEO";
            case 24:
                return "kTPCodecIdHUFFYUV";
            case 25:
                return "kTPCodecIdCYUV";
            case 26:
                return "kTPCodecIdH264";
            case 27:
                return "kTPCodecIdINDEO3";
            case 28:
                return "kTPCodecIdVP3";
            case 29:
                return "kTPCodecIdTHEORA";
            case 30:
                return "kTPCodecIdASV1";
            case 31:
                return "kTPCodecIdASV2";
            case 32:
                return "kTPCodecIdFFV1";
            case 33:
                return "kTPCodecId4XM";
            case 34:
                return "kTPCodecIdVCR1";
            case 35:
                return "kTPCodecIdCLJR";
            case 36:
                return "kTPCodecIdMDEC";
            case 37:
                return "kTPCodecIdROQ";
            case 38:
                return "kTPCodecIdINTERPLAY_VIDEO";
            case 39:
                return "kTPCodecIdXAN_WC3";
            case 40:
                return "kTPCodecIdXAN_WC4";
            case 41:
                return "kTPCodecIdRPZA";
            case 42:
                return "kTPCodecIdCINEPAK";
            case 43:
                return "kTPCodecIdWS_VQA";
            case 44:
                return "kTPCodecIdMSRLE";
            case 45:
                return "kTPCodecIdMSVIDEO1";
            case 46:
                return "kTPCodecIdIDCIN";
            case 47:
                return "kTPCodecId8BPS";
            case 48:
                return "kTPCodecIdSMC";
            case 49:
                return "kTPCodecIdFLIC";
            case 50:
                return "kTPCodecIdTRUEMOTION1";
            case 51:
                return "kTPCodecIdVMDVIDEO";
            case 52:
                return "kTPCodecIdMSZH";
            case 53:
                return "kTPCodecIdZLIB";
            case 54:
                return "kTPCodecIdQTRLE";
            case 55:
                return "kTPCodecIdTSCC";
            case 56:
                return "kTPCodecIdULTI";
            case 57:
                return "kTPCodecIdQDRAW";
            case 58:
                return "kTPCodecIdVIXL";
            case 59:
                return "kTPCodecIdQPEG";
            case 60:
                return "kTPCodecIdPNG";
            case 61:
                return "kTPCodecIdPPM";
            case 62:
                return "kTPCodecIdPBM";
            case 63:
                return "kTPCodecIdPGM";
            case 64:
                return "kTPCodecIdPGMYUV";
            case 65:
                return "kTPCodecIdPAM";
            case 66:
                return "kTPCodecIdFFVHUFF";
            case 67:
                return "kTPCodecIdRV30";
            case 68:
                return "kTPCodecIdRV40";
            case 69:
                return "kTPCodecIdVC1";
            case 70:
                return "kTPCodecIdWMV3";
            case 71:
                return "kTPCodecIdLOCO";
            case 72:
                return "kTPCodecIdWNV1";
            case 73:
                return "kTPCodecIdAASC";
            case 74:
                return "kTPCodecIdINDEO2";
            case 75:
                return "kTPCodecIdFRAPS";
            case 76:
                return "kTPCodecIdTRUEMOTION2";
            case 77:
                return "kTPCodecIdBMP";
            case 78:
                return "kTPCodecIdCSCD";
            case 79:
                return "kTPCodecIdMMVIDEO";
            case 80:
                return "kTPCodecIdZMBV";
            case 81:
                return "kTPCodecIdAVS";
            case 82:
                return "kTPCodecIdSMACKVIDEO";
            case 83:
                return "kTPCodecIdNUV";
            case 84:
                return "kTPCodecIdKMVC";
            case 85:
                return "kTPCodecIdFLASHSV";
            default:
                switch (i3) {
                    case 87:
                        return "kTPCodecIdJPEG2000";
                    case 88:
                        return "kTPCodecIdVMNC";
                    case 89:
                        return "kTPCodecIdVP5";
                    case 90:
                        return "kTPCodecIdVP6";
                    case 91:
                        return "kTPCodecIdVP6F";
                    case 92:
                        return "kTPCodecIdTARGA";
                    case 93:
                        return "kTPCodecIdDSICINVIDEO";
                    case 94:
                        return "kTPCodecIdTIERTEXSEQVIDEO";
                    case 95:
                        return "kTPCodecIdTIFF";
                    case 96:
                        return "kTPCodecIdGIF";
                    case 97:
                        return "kTPCodecIdDXA";
                    case 98:
                        return "kTPCodecIdDNXHD";
                    case 99:
                        return "kTPCodecIdTHP";
                    case 100:
                        return "kTPCodecIdSGI";
                    case 101:
                        return "kTPCodecIdC93";
                    case 102:
                        return "kTPCodecIdBETHSOFTVID";
                    case 103:
                        return "kTPCodecIdPTX";
                    case 104:
                        return "kTPCodecIdTXD";
                    case 105:
                        return "kTPCodecIdVP6A";
                    case 106:
                        return "kTPCodecIdAMV";
                    case 107:
                        return "kTPCodecIdVB";
                    case 108:
                        return "kTPCodecIdPCX";
                    case 109:
                        return "kTPCodecIdSUNRAST";
                    case 110:
                        return "kTPCodecIdINDEO4";
                    case 111:
                        return "kTPCodecIdINDEO5";
                    case 112:
                        return "kTPCodecIdMIMIC";
                    case 113:
                        return "kTPCodecIdRL2";
                    case 114:
                        return "kTPCodecIdESCAPE124";
                    case 115:
                        return "kTPCodecIdDIRAC";
                    case 116:
                        return "kTPCodecIdBFI";
                    case 117:
                        return "kTPCodecIdCMV";
                    case 118:
                        return "kTPCodecIdMOTIONPIXELS";
                    case 119:
                        return "kTPCodecIdTGV";
                    case 120:
                        return "kTPCodecIdTGQ";
                    case 121:
                        return "kTPCodecIdTQI";
                    case 122:
                        return "kTPCodecIdAURA";
                    case 123:
                        return "kTPCodecIdAURA2";
                    case 124:
                        return "kTPCodecIdV210X";
                    case 125:
                        return "kTPCodecIdTMV";
                    case 126:
                        return "kTPCodecIdV210";
                    case 127:
                        return "kTPCodecIdDPX";
                    case 128:
                        return "kTPCodecIdMAD";
                    case 129:
                        return "kTPCodecIdFRWU";
                    case 130:
                        return "kTPCodecIdFLASHSV2";
                    case 131:
                        return "kTPCodecIdCDGRAPHICS";
                    case 132:
                        return "kTPCodecIdR210";
                    case 133:
                        return "kTPCodecIdANM";
                    case 134:
                        return "kTPCodecIdBINKVIDEO";
                    case 135:
                        return "kTPCodecIdIFF_ILBM";
                    case 136:
                        return "kTPCodecIdKGV1";
                    case 137:
                        return "kTPCodecIdYOP";
                    case 138:
                        return "kTPCodecIdVP8";
                    case 139:
                        return "kTPCodecIdPICTOR";
                    case 140:
                        return "kTPCodecIdANSI";
                    case 141:
                        return "kTPCodecIdA64_MULTI";
                    case 142:
                        return "kTPCodecIdA64_MULTI5";
                    case 143:
                        return "kTPCodecIdR10K";
                    case 144:
                        return "kTPCodecIdMXPEG";
                    case 145:
                        return "kTPCodecIdLAGARITH";
                    case 146:
                        return "kTPCodecIdPRORES";
                    case 147:
                        return "kTPCodecIdJV";
                    case 148:
                        return "kTPCodecIdDFA";
                    case 149:
                        return "kTPCodecIdWMV3IMAGE";
                    case 150:
                        return "kTPCodecIdVC1IMAGE";
                    case 151:
                        return "kTPCodecIdUTVIDEO";
                    case 152:
                        return "kTPCodecIdBMV_VIDEO";
                    case 153:
                        return "kTPCodecIdVBLE";
                    case 154:
                        return "kTPCodecIdDXTORY";
                    case 155:
                        return "kTPCodecIdV410";
                    case 156:
                        return "kTPCodecIdXWD";
                    case 157:
                        return "kTPCodecIdCDXL";
                    case 158:
                        return "kTPCodecIdXBM";
                    case 159:
                        return "kTPCodecIdZEROCODEC";
                    case 160:
                        return "kTPCodecIdMSS1";
                    case 161:
                        return "kTPCodecIdMSA1";
                    case 162:
                        return "kTPCodecIdTSCC2";
                    case 163:
                        return "kTPCodecIdMTS2";
                    case 164:
                        return "kTPCodecIdCLLC";
                    case 165:
                        return "kTPCodecIdMSS2";
                    case 166:
                        return "kTPCodecIdVP9";
                    case 167:
                        return "kTPCodecIdAIC";
                    case 168:
                        return "kTPCodecIdESCAPE130";
                    case 169:
                        return "kTPCodecIdG2M";
                    case 170:
                        return "kTPCodecIdWEBP";
                    case 171:
                        return "kTPCodecIdHNM4_VIDEO";
                    case 172:
                        return "kTPCodecIdHEVC";
                    case 173:
                        return "kTPCodecIdFIC";
                    case 174:
                        return "kTPCodecIdALIAS_PIX";
                    case 175:
                        return "kTPCodecIdBRENDER_PIX";
                    case 176:
                        return "kTPCodecIdPAF_VIDEO";
                    case 177:
                        return "kTPCodecIdEXR";
                    case 178:
                        return "kTPCodecIdVP7";
                    case 179:
                        return "kTPCodecIdSANM";
                    case 180:
                        return "kTPCodecIdSGIRLE";
                    case 181:
                        return "kTPCodecIdMVC1";
                    case 182:
                        return "kTPCodecIdMVC2";
                    case 183:
                        return "kTPCodecIdHQX";
                    case 184:
                        return "kTPCodecIdTDSC";
                    case 185:
                        return "kTPCodecIdHQ_HQA";
                    case 186:
                        return "kTPCodecIdHAP";
                    case 187:
                        return "kTPCodecIdDDS";
                    case 188:
                        return "kTPCodecIdDXV";
                    case 189:
                        return "kTPCodecIdSCREENPRESSO";
                    case 190:
                        return "kTPCodecIdRSCC";
                    case 191:
                        return "kTPCodecIdCAVS";
                    default:
                        switch (i3) {
                            case 1000:
                                return "kTPCodecIdY41P";
                            case 1001:
                                return "kTPCodecIdAVRP";
                            case 1002:
                                return "kTPCodecId012V";
                            case 1003:
                                return "kTPCodecIdAVUI";
                            case 1004:
                                return "kTPCodecIdAYUV";
                            case 1005:
                                return "kTPCodecIdTARGA_Y216";
                            case 1006:
                                return "kTPCodecIdV308";
                            case 1007:
                                return "kTPCodecIdV408";
                            case 1008:
                                return "kTPCodecIdYUV4";
                            case 1009:
                                return "kTPCodecIdAVRN";
                            case 1010:
                                return "kTPCodecIdCPIA";
                            case 1011:
                                return "kTPCodecIdXFACE";
                            case 1012:
                                return "kTPCodecIdSNOW";
                            case 1013:
                                return "kTPCodecIdSMVJPEG";
                            case 1014:
                                return "kTPCodecIdAPNG";
                            case 1015:
                                return "kTPCodecIdDAALA";
                            case 1016:
                                return "kTPCodecIdCFHD";
                            case 1017:
                                return "kTPCodecIdTRUEMOTION2RT";
                            case 1018:
                                return "kTPCodecIdM101";
                            case 1019:
                                return "kTPCodecIdMAGICYUV";
                            case 1020:
                                return "kTPCodecIdSHEERVIDEO";
                            case 1021:
                                return "kTPCodecIdYLC";
                            case 1022:
                                return "kTPCodecIdPSD";
                            case 1023:
                                return "kTPCodecIdPIXLET";
                            case 1024:
                                return "kTPCodecIdSPEEDHQ";
                            case 1025:
                                return "kTPCodecIdFMVC";
                            case 1026:
                                return "kTPCodecIdSCPR";
                            case 1027:
                                return "kTPCodecIdCLEARVIDEO";
                            case 1028:
                                return "kTPCodecIdXPM";
                            case 1029:
                                return "kTPCodecIdAV1";
                            case 1030:
                                return "kTPCodecIdBITPACKED";
                            case 1031:
                                return "kTPCodecIdMSCC";
                            case 1032:
                                return "kTPCodecIdSRGC";
                            case 1033:
                                return "kTPCodecIdSVG";
                            case 1034:
                                return "kTPCodecIdGDV";
                            case 1035:
                                return "kTPCodecIdFITS";
                            case 1036:
                                return "kTPCodecIdIMM4";
                            case 1037:
                                return "kTPCodecIdPROSUMER";
                            case 1038:
                                return "kTPCodecIdMWSC";
                            case 1039:
                                return "kTPCodecIdWCMV";
                            case 1040:
                                return "kTPCodecIdRASC";
                            default:
                                return "kTPCodecIdUnknown";
                        }
                }
        }
    }
}
