package r03;

import kotlin.Metadata;
import org.jetbrains.annotations.NotNull;

/* compiled from: P */
@Metadata(d1 = {"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\u0010\u000e\n\u0002\b\u0004\u0018\u00002\u00020\u0001B\u0007\u00a2\u0006\u0004\b\u0004\u0010\u0005J\u0006\u0010\u0003\u001a\u00020\u0002\u00a8\u0006\u0006"}, d2 = {"Lr03/a;", "", "", "a", "<init>", "()V", "AQQLiteModule_release"}, k = 1, mv = {1, 7, 1})
/* loaded from: classes20.dex */
public final class a {
    @NotNull
    public final String a() {
        return "{\n    \"VasGuideQqgxhRecall\":{\n        \"enableDomain\":[\n            \"vip.qq.com\",\n            \"qun.qq.com\"\n        ]\n    },\n    \"VasGuideQqgxhProfileDisplay\":{\n        \"enableDomain\":[\n            \"vip.qq.com\",\n            \"qun.qq.com\"\n        ]\n    },\n    \"VasGuideClmFloating\":{\n        \"enableDomain\":[\n            \"vip.qq.com\",\n            \"qun.qq.com\"\n        ]\n    },\n    \"QQVipSSR\":{\n        \"enableDomain\":[\n            \"vip.qq.com\",\n            \"qzone.qq.com\"\n        ]\n    },\n    \"QQVip\":{\n        \"enableDomain\":[\n            \"vip.qq.com\",\n            \"qzone.qq.com\"\n        ],\n        \"openParams\":{\n            \"url\":\"https://club.vip.qq.com/index?_wv=16778247&_wwv=68&_wvx=10&_proxy=1&page_from=qqchouti\",\n            \"errorUrl\":\"https://club.vip.qq.com/index?_wv=16778247&_wwv=68&_wvx=10&_proxy=1&from=hippy_error\",\n            \"isCustomNightMode\":true,\n            \"isPreload\":true,\n            \"isPreloadWhenClosed\":true,\n            \"isPredraw\":true,\n            \"isPredrawWhenClosed\":true,\n            \"isAnimated\":true,\n            \"bundleName\":\"QQVip\",\n            \"domain\":\"vip.qq.com\"\n        }\n    },\n    \"QQVipAggregation\":{\n        \"enableDomain\":[\n            \"vip.qq.com\",\n            \"qzone.qq.com\"\n        ],\n        \"openParams\":{\n            \"url\":\"https://club.vip.qq.com/card?_wv=16778247&_wwv=68&_wvx=10\",\n            \"errorUrl\":\"https://club.vip.qq.com/card\uff1f_wv=16778247&_wwv=68&_wvx=10\",\n            \"isCustomNightMode\":true,\n            \"isPreload\":true,\n            \"isPreloadWhenClosed\":true,\n            \"isPredraw\":true,\n            \"isPredrawWhenClosed\":true,\n            \"isAnimated\":true,\n            \"bundleName\":\"QQVipAggregation\",\n            \"domain\":\"vip.qq.com\"\n        }\n    },\n    \"qqgxh\":{\n        \"enableDomain\":[\n            \"vip.qq.com\"\n        ],\n        \"openParams\":{\n            \"url\":\"https://zb.vip.qq.com/v2/home?_wv=5123&_wwv=128&_proxy=1&ADTAG=mobileqq.drawer&trace_detail=base64-eyJhcHBpZCI6Im91dHNpZGUiLCJwYWdlX2lkIjoiMyJ9\",\n            \"errorUrl\":\"https://zb.vip.qq.com/v2/home?_wv=5123&_wwv=128&_proxy=1&ADTAG=mobileqq.drawer&trace_detail=base64-eyJhcHBpZCI6Im91dHNpZGUiLCJwYWdlX2lkIjoiMyJ9\",\n            \"isCustomNightMode\":true,\n            \"isPreloadWhenClosed\":true,\n            \"isPredraw\":true,\n            \"isPredrawWhenClosed\":true,\n            \"isAnimated\":true,\n            \"bundleName\":\"qqgxh\",\n            \"domain\":\"vip.qq.com\"\n        }\n    },\n    \"QQVipPay\":{\n        \"enableDomain\":[\n            \"vip.qq.com\"\n        ]\n    }\n}";
    }
}
