package com.tencent.qcircle.cooperation.config.debug;

/* compiled from: P */
/* loaded from: classes22.dex */
public enum QCircleDebugKey$MultipleStateKey {
    QCIRCLE_LBS_SERVER_CONTROLLER,
    QCIRCLE_MSF_SERVER_CONTROLLER,
    QCIRCLE_REC_EXPT_ENV_CONTROLLER,
    QCIRCLE_SCHEME_CONTROLLER,
    QCIRCLE_STICK_CONTROLLER,
    QCIRCLE_PAGE_SCROLL_SETTING_CONTROLLER,
    QCIRCLE_MEMORY_JAVA_DUMP_CONTROLLER,
    QCIRCLE_MEMORY_NATIVE_DUMP_CONTROLLER,
    QCIRCLE_PUBLISHED_USER_CONTROLLER,
    QCIRCLE_QIMEI_CONTROLLER,
    QCIRCLE_FACE_GET_CONTROLLER,
    QCIRCLE_FACE_CHECK_CONTROLLER
}
