package cooperation.qzone.model;

import android.os.Parcel;
import android.os.Parcelable;
import androidx.annotation.NonNull;
import java.util.HashMap;
import java.util.Map;

/* loaded from: classes28.dex */
public class PhotoParam implements Parcelable {
    public static final int APP_ID = 4;
    public static final Parcelable.Creator<PhotoParam> CREATOR = new Parcelable.Creator<PhotoParam>() { // from class: cooperation.qzone.model.PhotoParam.1
        /* JADX WARN: Can't rename method to resolve collision */
        @Override // android.os.Parcelable.Creator
        public PhotoParam[] newArray(int i3) {
            return null;
        }

        /* JADX WARN: Can't rename method to resolve collision */
        @Override // android.os.Parcelable.Creator
        public PhotoParam createFromParcel(Parcel parcel) {
            PhotoParam photoParam = new PhotoParam();
            photoParam.loginUin = parcel.readLong();
            photoParam.feedUin = parcel.readLong();
            photoParam.ownerUin = parcel.readLong();
            photoParam.realOwnerUin = parcel.readLong();
            photoParam.albumanswer = parcel.readString();
            photoParam.albumid = parcel.readString();
            photoParam.sortType = parcel.readInt();
            photoParam.albumPriv = parcel.readInt();
            photoParam.albumnum = parcel.readInt();
            photoParam.uploadnum = parcel.readInt();
            photoParam.albumType = parcel.readInt();
            photoParam.businessPhotoFeedIndex = parcel.readInt();
            photoParam.qunid = parcel.readString();
            photoParam.isLike = parcel.readInt() == 1;
            photoParam.likeNum = parcel.readInt();
            photoParam.commentNum = parcel.readInt();
            photoParam.curKey = parcel.readString();
            photoParam.orgKey = parcel.readString();
            photoParam.feedId = parcel.readString();
            photoParam.cell_id = parcel.readString();
            photoParam.cell_subId = parcel.readString();
            photoParam.appid = parcel.readInt();
            photoParam.busi_param = parcel.readHashMap(getClass().getClassLoader());
            photoParam.ugcKey = parcel.readString();
            photoParam.canAddFavor = parcel.readInt() == 1;
            photoParam.subid = parcel.readInt();
            photoParam.isOnePictureFeed = parcel.readInt() == 1;
            photoParam.oneFeedPictruePath = parcel.readString();
            photoParam.mFromRecent = parcel.readInt() == 1;
            photoParam.isTihFeed = parcel.readInt() == 1;
            photoParam.isOnlyPreView = parcel.readInt() == 1;
            photoParam.isFriendPhotoBizFeed = parcel.readInt() == 1;
            photoParam.isShareAlbum = parcel.readInt() == 1;
            photoParam.isVideoPicMix = parcel.readInt() == 1;
            photoParam.getPhotoExType = parcel.readInt();
            photoParam.sharer = parcel.readLong();
            photoParam.loginNickName = parcel.readString();
            photoParam.qzoneUserType = parcel.readLong();
            photoParam.isSharedFeeds = parcel.readInt() == 1;
            photoParam.videoUgcRight = parcel.readInt();
            photoParam.noNeedToFetchPhotoList = parcel.readInt() == 1;
            photoParam.notAllowShareOutside = parcel.readInt() == 1;
            photoParam.singleVideoQCircleSchema = parcel.readString();
            return photoParam;
        }
    };
    public int albumPriv;
    public int albumType;
    public String albumanswer;
    public String albumid;
    public int albumnum;
    public int businessPhotoFeedIndex;
    public int commentNum;
    public long feedUin;
    public boolean isTihFeed;
    public boolean isVideoPicMix;
    public int likeNum;
    public long loginUin;
    public boolean noNeedToFetchPhotoList;
    public boolean notAllowShareOutside;
    public long ownerUin;
    public String qunid;
    public long realOwnerUin;
    public int sortType;
    public int uploadnum;
    public int videoUgcRight;
    public boolean isLike = false;
    public String curKey = "";
    public String orgKey = "";
    public String feedId = "";
    public String cell_id = "";
    public String cell_subId = "";
    public int appid = 4;
    public String ugcKey = "";
    public boolean canAddFavor = true;
    public int subid = -1;
    public boolean isOnePictureFeed = false;
    public String oneFeedPictruePath = "";
    public boolean mFromRecent = false;
    public Map<Integer, String> busi_param = new HashMap();
    public boolean isOnlyPreView = false;
    public boolean isFriendPhotoBizFeed = false;
    public boolean isShareAlbum = false;
    public int getPhotoExType = 0;
    public long sharer = 0;
    public String loginNickName = "";
    public long qzoneUserType = 0;
    public boolean isSharedFeeds = false;
    public String singleVideoQCircleSchema = "";

    public static PhotoParam getClonePhotoParam(@NonNull PhotoParam photoParam) {
        PhotoParam photoParam2 = new PhotoParam();
        photoParam2.loginUin = photoParam.loginUin;
        photoParam2.feedUin = photoParam.feedUin;
        photoParam2.ownerUin = photoParam.ownerUin;
        photoParam2.realOwnerUin = photoParam.realOwnerUin;
        photoParam2.albumanswer = photoParam.albumanswer;
        photoParam2.albumid = photoParam.albumid;
        photoParam2.sortType = photoParam.sortType;
        photoParam2.albumPriv = photoParam.albumPriv;
        photoParam2.albumnum = photoParam.albumnum;
        photoParam2.uploadnum = photoParam.uploadnum;
        photoParam2.albumType = photoParam.albumType;
        photoParam2.businessPhotoFeedIndex = photoParam.businessPhotoFeedIndex;
        photoParam2.qunid = photoParam.qunid;
        photoParam2.isLike = photoParam.isLike;
        photoParam2.likeNum = photoParam.likeNum;
        photoParam2.commentNum = photoParam.commentNum;
        photoParam2.curKey = photoParam.curKey;
        photoParam2.orgKey = photoParam.orgKey;
        photoParam2.feedId = photoParam.feedId;
        photoParam2.cell_id = photoParam.cell_id;
        photoParam2.cell_subId = photoParam.cell_subId;
        photoParam2.appid = photoParam.appid;
        photoParam2.busi_param = photoParam.busi_param;
        photoParam2.ugcKey = photoParam.ugcKey;
        photoParam2.canAddFavor = photoParam.canAddFavor;
        photoParam2.subid = photoParam.subid;
        photoParam2.isOnePictureFeed = photoParam.isOnePictureFeed;
        photoParam2.oneFeedPictruePath = photoParam.oneFeedPictruePath;
        photoParam2.mFromRecent = photoParam.mFromRecent;
        photoParam2.isTihFeed = photoParam.isTihFeed;
        photoParam2.isOnlyPreView = photoParam.isOnlyPreView;
        photoParam2.isFriendPhotoBizFeed = photoParam.isFriendPhotoBizFeed;
        photoParam2.isShareAlbum = photoParam.isShareAlbum;
        photoParam2.isVideoPicMix = photoParam.isVideoPicMix;
        photoParam2.getPhotoExType = photoParam.getPhotoExType;
        photoParam2.sharer = photoParam.sharer;
        photoParam2.loginNickName = photoParam.loginNickName;
        photoParam2.qzoneUserType = photoParam.qzoneUserType;
        photoParam2.isSharedFeeds = photoParam.isSharedFeeds;
        photoParam2.noNeedToFetchPhotoList = photoParam.noNeedToFetchPhotoList;
        photoParam2.notAllowShareOutside = photoParam.notAllowShareOutside;
        photoParam2.singleVideoQCircleSchema = photoParam.singleVideoQCircleSchema;
        return photoParam2;
    }

    @Override // android.os.Parcelable
    public int describeContents() {
        return 0;
    }

    public String toString() {
        StringBuffer stringBuffer = new StringBuffer("PhotoParam{");
        stringBuffer.append("loginUin=");
        stringBuffer.append(this.loginUin);
        stringBuffer.append(", feedUin=");
        stringBuffer.append(this.feedUin);
        stringBuffer.append(", ownerUin=");
        stringBuffer.append(this.ownerUin);
        stringBuffer.append(", realOwnerUin=");
        stringBuffer.append(this.realOwnerUin);
        stringBuffer.append(", albumanswer='");
        stringBuffer.append(this.albumanswer);
        stringBuffer.append('\'');
        stringBuffer.append(", albumid='");
        stringBuffer.append(this.albumid);
        stringBuffer.append('\'');
        stringBuffer.append(", sortType=");
        stringBuffer.append(this.sortType);
        stringBuffer.append(", albumPriv=");
        stringBuffer.append(this.albumPriv);
        stringBuffer.append(", albumnum=");
        stringBuffer.append(this.albumnum);
        stringBuffer.append(", uploadnum=");
        stringBuffer.append(this.uploadnum);
        stringBuffer.append(", albumType=");
        stringBuffer.append(this.albumType);
        stringBuffer.append(", businessPhotoFeedIndex=");
        stringBuffer.append(this.businessPhotoFeedIndex);
        stringBuffer.append(", qunid='");
        stringBuffer.append(this.qunid);
        stringBuffer.append('\'');
        stringBuffer.append(", isLike=");
        stringBuffer.append(this.isLike);
        stringBuffer.append(", likeNum=");
        stringBuffer.append(this.likeNum);
        stringBuffer.append(", commentNum=");
        stringBuffer.append(this.commentNum);
        stringBuffer.append(", curKey='");
        stringBuffer.append(this.curKey);
        stringBuffer.append('\'');
        stringBuffer.append(", orgKey='");
        stringBuffer.append(this.orgKey);
        stringBuffer.append('\'');
        stringBuffer.append(", feedId='");
        stringBuffer.append(this.feedId);
        stringBuffer.append('\'');
        stringBuffer.append(", cell_id='");
        stringBuffer.append(this.cell_id);
        stringBuffer.append('\'');
        stringBuffer.append(", cell_subId='");
        stringBuffer.append(this.cell_subId);
        stringBuffer.append('\'');
        stringBuffer.append(", appid=");
        stringBuffer.append(this.appid);
        stringBuffer.append(", ugcKey='");
        stringBuffer.append(this.ugcKey);
        stringBuffer.append('\'');
        stringBuffer.append(", canAddFavor=");
        stringBuffer.append(this.canAddFavor);
        stringBuffer.append(", subid=");
        stringBuffer.append(this.subid);
        stringBuffer.append(", isOnePictureFeed=");
        stringBuffer.append(this.isOnePictureFeed);
        stringBuffer.append(", oneFeedPictruePath='");
        stringBuffer.append(this.oneFeedPictruePath);
        stringBuffer.append('\'');
        stringBuffer.append(", mFromRecent=");
        stringBuffer.append(this.mFromRecent);
        stringBuffer.append(", busi_param=");
        stringBuffer.append(this.busi_param);
        stringBuffer.append(", isTihFeed=");
        stringBuffer.append(this.isTihFeed);
        stringBuffer.append(", isOnlyPreView=");
        stringBuffer.append(this.isOnlyPreView);
        stringBuffer.append(", isFriendPhotoBizFeed=");
        stringBuffer.append(this.isFriendPhotoBizFeed);
        stringBuffer.append(", isShareAlbum=");
        stringBuffer.append(this.isShareAlbum);
        stringBuffer.append(", isVideoPicMix=");
        stringBuffer.append(this.isVideoPicMix);
        stringBuffer.append(", getPhotoExType=");
        stringBuffer.append(this.getPhotoExType);
        stringBuffer.append(", sharer=");
        stringBuffer.append(this.sharer);
        stringBuffer.append(", loginNickName='");
        stringBuffer.append(this.loginNickName);
        stringBuffer.append('\'');
        stringBuffer.append(", qzoneUserType=");
        stringBuffer.append(this.qzoneUserType);
        stringBuffer.append(", isSharedFeeds=");
        stringBuffer.append(this.isSharedFeeds);
        stringBuffer.append(", videoUgcRight=");
        stringBuffer.append(this.videoUgcRight);
        stringBuffer.append(", isForwardAlbumFeed=");
        stringBuffer.append(this.noNeedToFetchPhotoList);
        stringBuffer.append(", notAllowShareOutside=");
        stringBuffer.append(this.notAllowShareOutside);
        stringBuffer.append(", singleVideoQCircleSchema=");
        stringBuffer.append(this.singleVideoQCircleSchema);
        stringBuffer.append('}');
        return stringBuffer.toString();
    }

    @Override // android.os.Parcelable
    public void writeToParcel(Parcel parcel, int i3) {
        parcel.writeLong(this.loginUin);
        parcel.writeLong(this.feedUin);
        parcel.writeLong(this.ownerUin);
        parcel.writeLong(this.realOwnerUin);
        parcel.writeString(this.albumanswer);
        parcel.writeString(this.albumid);
        parcel.writeInt(this.sortType);
        parcel.writeInt(this.albumPriv);
        parcel.writeInt(this.albumnum);
        parcel.writeInt(this.uploadnum);
        parcel.writeInt(this.albumType);
        parcel.writeInt(this.businessPhotoFeedIndex);
        parcel.writeString(this.qunid);
        parcel.writeInt(this.isLike ? 1 : 0);
        parcel.writeInt(this.likeNum);
        parcel.writeInt(this.commentNum);
        parcel.writeString(this.curKey);
        parcel.writeString(this.orgKey);
        parcel.writeString(this.feedId);
        parcel.writeString(this.cell_id);
        parcel.writeString(this.cell_subId);
        parcel.writeInt(this.appid);
        parcel.writeMap(this.busi_param);
        parcel.writeString(this.ugcKey);
        parcel.writeInt(this.canAddFavor ? 1 : 0);
        parcel.writeInt(this.subid);
        parcel.writeInt(this.isOnePictureFeed ? 1 : 0);
        parcel.writeString(this.oneFeedPictruePath);
        parcel.writeInt(this.mFromRecent ? 1 : 0);
        parcel.writeInt(this.isTihFeed ? 1 : 0);
        parcel.writeInt(this.isOnlyPreView ? 1 : 0);
        parcel.writeInt(this.isFriendPhotoBizFeed ? 1 : 0);
        parcel.writeInt(this.isShareAlbum ? 1 : 0);
        parcel.writeInt(this.isVideoPicMix ? 1 : 0);
        parcel.writeInt(this.getPhotoExType);
        parcel.writeLong(this.sharer);
        parcel.writeString(this.loginNickName);
        parcel.writeLong(this.qzoneUserType);
        parcel.writeInt(this.isSharedFeeds ? 1 : 0);
        parcel.writeInt(this.videoUgcRight);
        parcel.writeInt(this.noNeedToFetchPhotoList ? 1 : 0);
        parcel.writeInt(this.notAllowShareOutside ? 1 : 0);
        parcel.writeString(this.singleVideoQCircleSchema);
    }
}
