package com.tencent.mobileqq.wink.model;

import java.io.Serializable;

/* compiled from: P */
/* loaded from: classes21.dex */
public class WinkEditorVideoInfo implements Serializable {
    public static final String AEEDITOR_GENERATE_STATUS_WAIT = "AEEDITOR_GENERATE_STATUS_WAIT";
    public String errorMsg;
    public String filterID;
    public int height;
    public float lastProgress;
    public float mKuolieCenterX;
    public float mKuolieCenterY;
    public float mKuolieHeightScale;
    public String mKuolieId;
    public float mKuolieRotate;
    public float mKuolieWidthScale;
    public String materialID;
    public String materialName;
    public String missionID;
    public String path;
    public float predictTime;
    public float progress;
    public String scheme;
    public int showCircleTakeSame;
    public String sourcePath;
    public String thumbPath;
    public int videoRate;
    public int width;
    public long videoDuration = 0;
    public String status = "AEEDITOR_GENERATE_STATUS_WAIT";
    public long errorCode = 0;
    public long lastBroadCastTime = 0;

    public WinkEditorVideoInfo(String str, String str2, String str3, String str4, int i3, String str5, String str6, String str7, String str8, String str9, float f16, float f17, float f18, float f19, float f26, int i16) {
        this.materialID = str;
        this.materialName = str2;
        this.filterID = str3;
        this.scheme = str4;
        this.showCircleTakeSame = i3;
        this.path = str7;
        this.sourcePath = str6;
        this.missionID = str5;
        this.thumbPath = str8;
        this.mKuolieId = str9;
        this.mKuolieCenterX = f16;
        this.mKuolieCenterY = f17;
        this.mKuolieWidthScale = f18;
        this.mKuolieHeightScale = f19;
        this.mKuolieRotate = f26;
        this.videoRate = i16;
    }

    public String toString() {
        StringBuffer stringBuffer = new StringBuffer("WinkEditorVideoInfo{\n");
        stringBuffer.append("path='");
        stringBuffer.append(this.path);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", width=");
        stringBuffer.append(this.width);
        stringBuffer.append('\n');
        stringBuffer.append(", height=");
        stringBuffer.append(this.height);
        stringBuffer.append('\n');
        stringBuffer.append(", sourcePath='");
        stringBuffer.append(this.sourcePath);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", thumbPath='");
        stringBuffer.append(this.thumbPath);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", progress=");
        stringBuffer.append(this.progress);
        stringBuffer.append('\n');
        stringBuffer.append(", lastProgress=");
        stringBuffer.append(this.lastProgress);
        stringBuffer.append('\n');
        stringBuffer.append(", lastBroadCastTime=");
        stringBuffer.append(this.lastBroadCastTime);
        stringBuffer.append('\n');
        stringBuffer.append(", predictTime=");
        stringBuffer.append(this.predictTime);
        stringBuffer.append('\n');
        stringBuffer.append(", status='");
        stringBuffer.append(this.status);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", missionID='");
        stringBuffer.append(this.missionID);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", errorCode=");
        stringBuffer.append(this.errorCode);
        stringBuffer.append('\n');
        stringBuffer.append(", errorMsg='");
        stringBuffer.append(this.errorMsg);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", materialID='");
        stringBuffer.append(this.materialID);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", materialName='");
        stringBuffer.append(this.materialName);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", filterID='");
        stringBuffer.append(this.filterID);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", scheme='");
        stringBuffer.append(this.scheme);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", showCircleTakeSame=");
        stringBuffer.append(this.showCircleTakeSame);
        stringBuffer.append('\n');
        stringBuffer.append(", mKuolieId='");
        stringBuffer.append(this.mKuolieId);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", mKuolieCenterX=");
        stringBuffer.append(this.mKuolieCenterX);
        stringBuffer.append('\n');
        stringBuffer.append(", mKuolieCenterY=");
        stringBuffer.append(this.mKuolieCenterY);
        stringBuffer.append('\n');
        stringBuffer.append(", mKuolieRotate=");
        stringBuffer.append(this.mKuolieRotate);
        stringBuffer.append('\n');
        stringBuffer.append(", mKuolieWidthScale=");
        stringBuffer.append(this.mKuolieWidthScale);
        stringBuffer.append('\n');
        stringBuffer.append(", mKuolieHeightScale=");
        stringBuffer.append(this.mKuolieHeightScale);
        stringBuffer.append('\n');
        stringBuffer.append(", videoRate=");
        stringBuffer.append(this.videoRate);
        stringBuffer.append('\n');
        stringBuffer.append(", videoDuration=");
        stringBuffer.append(this.videoDuration);
        stringBuffer.append('\n');
        stringBuffer.append('}');
        return stringBuffer.toString();
    }
}
