package com.tencent.mobileqq.webview.view;

import android.content.Context;
import android.content.res.ColorStateList;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.tencent.mobileqq.R;
import com.tencent.mobileqq.qfix.redirect.IPatchRedirector;
import com.tencent.mobileqq.webview.swift.utils.n;
import com.tencent.widget.FadeIconImageView;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;

/* compiled from: P */
@Metadata(d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\u0018\u00002\u00020\u0001B\r\u0012\u0006\u0010\u0002\u001a\u00020\u0003\u00a2\u0006\u0002\u0010\u0004\u00a8\u0006\u0005"}, d2 = {"Lcom/tencent/mobileqq/webview/view/BrowserTitleBar;", "Landroid/widget/RelativeLayout;", "context", "Landroid/content/Context;", "(Landroid/content/Context;)V", "webview_kit_release"}, k = 1, mv = {1, 7, 1}, xi = 48)
/* loaded from: classes20.dex */
public final class BrowserTitleBar extends RelativeLayout {
    static IPatchRedirector $redirector_;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public BrowserTitleBar(@NotNull Context context) {
        super(context);
        Intrinsics.checkNotNullParameter(context, "context");
        IPatchRedirector iPatchRedirector = $redirector_;
        if (iPatchRedirector != null && iPatchRedirector.hasPatch((short) 1)) {
            iPatchRedirector.redirect((short) 1, (Object) this, (Object) context);
            return;
        }
        setId(R.id.f166798ic2);
        setLayoutParams(new RelativeLayout.LayoutParams(-1, -2));
        RelativeLayout relativeLayout = new RelativeLayout(getContext());
        relativeLayout.setId(R.id.rlCommenTitle);
        relativeLayout.setLayoutParams(new RelativeLayout.LayoutParams(-1, b.d(R.dimen.title_bar_height)));
        relativeLayout.setGravity(16);
        relativeLayout.setClipChildren(false);
        RelativeLayout relativeLayout2 = new RelativeLayout(relativeLayout.getContext());
        relativeLayout2.setId(R.id.f166812ie4);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams.leftMargin = b.e(96);
        layoutParams.rightMargin = b.e(96);
        layoutParams.addRule(13);
        relativeLayout2.setLayoutParams(layoutParams);
        LinearLayout linearLayout = new LinearLayout(relativeLayout2.getContext());
        linearLayout.setGravity(17);
        linearLayout.setOrientation(1);
        linearLayout.setLayoutParams(new RelativeLayout.LayoutParams(-2, -1));
        TextView textView = new TextView(linearLayout.getContext());
        textView.setId(R.id.ivTitleName);
        textView.setEllipsize(TextUtils.TruncateAt.END);
        textView.setGravity(17);
        textView.setSingleLine();
        textView.setMinWidth(b.e(88));
        textView.setText("");
        textView.setTextSize(0, b.e(17));
        ColorStateList colorStateList = n.token_color_navText_values;
        textView.setTextColor(colorStateList);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-2, -1);
        layoutParams2.gravity = 1;
        textView.setLayoutParams(layoutParams2);
        linearLayout.addView(textView);
        TextView textView2 = new TextView(linearLayout.getContext());
        textView2.setId(R.id.dtg);
        textView2.setVisibility(8);
        textView2.setText("");
        textView2.setTextSize(0, b.e(17));
        textView2.setTextColor(colorStateList);
        textView2.setEllipsize(TextUtils.TruncateAt.END);
        textView2.setGravity(17);
        textView2.setSingleLine();
        LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 1;
        layoutParams3.topMargin = b.e(1);
        textView2.setLayoutParams(layoutParams3);
        linearLayout.addView(textView2);
        relativeLayout2.addView(linearLayout);
        RelativeLayout relativeLayout3 = new RelativeLayout(relativeLayout2.getContext());
        relativeLayout3.setVisibility(8);
        relativeLayout3.setId(R.id.jp7);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams4.topMargin = b.e(5);
        layoutParams4.bottomMargin = b.e(5);
        layoutParams4.addRule(13);
        relativeLayout3.setLayoutParams(layoutParams4);
        TextView textView3 = new TextView(relativeLayout3.getContext());
        textView3.setId(R.id.jq5);
        textView3.setEllipsize(TextUtils.TruncateAt.END);
        textView3.setGravity(17);
        textView3.setSingleLine();
        textView3.setTextColor(colorStateList);
        textView3.setTextSize(0, b.e(16));
        textView3.setText("");
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams5.addRule(14);
        textView3.setLayoutParams(layoutParams5);
        relativeLayout3.addView(textView3);
        TextView textView4 = new TextView(relativeLayout3.getContext());
        textView4.setId(R.id.joi);
        textView4.setEllipsize(TextUtils.TruncateAt.END);
        textView4.setGravity(17);
        textView4.setText("");
        textView4.setSingleLine();
        textView4.setTextColor(colorStateList);
        textView4.setTextSize(0, b.e(12));
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams6.addRule(14);
        layoutParams6.addRule(3, R.id.jq5);
        textView4.setLayoutParams(layoutParams6);
        relativeLayout3.addView(textView4);
        relativeLayout2.addView(relativeLayout3);
        relativeLayout.addView(relativeLayout2);
        RelativeLayout relativeLayout4 = new RelativeLayout(relativeLayout.getContext());
        relativeLayout4.setId(R.id.f166810ie2);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams7.addRule(9);
        layoutParams7.addRule(15);
        relativeLayout4.setLayoutParams(layoutParams7);
        Context context2 = relativeLayout4.getContext();
        Intrinsics.checkNotNullExpressionValue(context2, "this.context");
        AlphaTextView alphaTextView = new AlphaTextView(context2);
        alphaTextView.setId(R.id.ivTitleBtnLeft);
        alphaTextView.setGravity(17);
        alphaTextView.setIncludeFontPadding(false);
        alphaTextView.setMaxWidth(b.e(88));
        alphaTextView.setMinWidth(b.e(40));
        alphaTextView.setText("");
        alphaTextView.setTextColor(colorStateList);
        alphaTextView.setTextSize(0, b.e(17));
        alphaTextView.setSingleLine();
        int i3 = n.token_icon_navLeftBack;
        Drawable c16 = b.c(i3);
        if (c16 != null) {
            int i16 = n.token_icon_size;
            c16.setBounds(0, 0, i16, i16);
        } else {
            c16 = null;
        }
        alphaTextView.setTag(R.id.f9219578, Integer.valueOf(i3));
        alphaTextView.setCompoundDrawablesWithIntrinsicBounds(c16, (Drawable) null, (Drawable) null, (Drawable) null);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams8.addRule(9);
        layoutParams8.addRule(15);
        layoutParams8.leftMargin = b.e(10);
        alphaTextView.setLayoutParams(layoutParams8);
        relativeLayout4.addView(alphaTextView);
        Context context3 = relativeLayout4.getContext();
        Intrinsics.checkNotNullExpressionValue(context3, "this.context");
        AlphaTextView alphaTextView2 = new AlphaTextView(context3);
        alphaTextView2.setId(R.id.ivTitleBtnLeftButton);
        alphaTextView2.setVisibility(8);
        alphaTextView2.setEllipsize(TextUtils.TruncateAt.END);
        alphaTextView2.setGravity(17);
        alphaTextView2.setIncludeFontPadding(false);
        alphaTextView2.setMaxWidth(b.e(88));
        alphaTextView2.setMinWidth(b.e(52));
        alphaTextView2.setText("");
        alphaTextView2.setTextColor(colorStateList);
        alphaTextView2.setSingleLine();
        alphaTextView2.setTextSize(1, 12.0f);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(9);
        layoutParams9.addRule(15);
        layoutParams9.leftMargin = b.e(10);
        alphaTextView2.setLayoutParams(layoutParams9);
        relativeLayout4.addView(alphaTextView2);
        FadeIconImageView fadeIconImageView = new FadeIconImageView(relativeLayout4.getContext());
        fadeIconImageView.setId(R.id.dsc);
        fadeIconImageView.setVisibility(8);
        fadeIconImageView.setScaleType(ImageView.ScaleType.CENTER);
        int i17 = n.token_icon_navLeftClose;
        fadeIconImageView.setImageResource(i17);
        fadeIconImageView.setTag(R.id.f9219578, Integer.valueOf(i17));
        RelativeLayout.LayoutParams layoutParams10 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams10.addRule(9);
        layoutParams10.addRule(15);
        layoutParams10.leftMargin = b.e(10);
        fadeIconImageView.setLayoutParams(layoutParams10);
        relativeLayout4.addView(fadeIconImageView);
        relativeLayout.addView(relativeLayout4);
        RelativeLayout relativeLayout5 = new RelativeLayout(relativeLayout.getContext());
        relativeLayout5.setId(R.id.f166811ie3);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams11.addRule(11);
        layoutParams11.addRule(15);
        relativeLayout5.setLayoutParams(layoutParams11);
        Context context4 = relativeLayout5.getContext();
        Intrinsics.checkNotNullExpressionValue(context4, "this.context");
        AlphaTextView alphaTextView3 = new AlphaTextView(context4);
        alphaTextView3.setId(R.id.ivTitleBtnRightText);
        alphaTextView3.setVisibility(8);
        alphaTextView3.setPadding(0, 0, b.e(10), 0);
        alphaTextView3.setGravity(17);
        alphaTextView3.setIncludeFontPadding(false);
        alphaTextView3.setMaxWidth(b.e(100));
        alphaTextView3.setMinWidth(b.e(52));
        alphaTextView3.setSingleLine();
        alphaTextView3.setTextColor(colorStateList);
        alphaTextView3.setTextSize(0, b.e(17));
        alphaTextView3.setLayoutParams(new RelativeLayout.LayoutParams(-2, b.e(36)));
        relativeLayout5.addView(alphaTextView3);
        RelativeLayout relativeLayout6 = new RelativeLayout(relativeLayout5.getContext());
        relativeLayout6.setPadding(0, 0, b.e(10), 0);
        relativeLayout6.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        FadeIconImageView fadeIconImageView2 = new FadeIconImageView(relativeLayout6.getContext());
        fadeIconImageView2.setId(R.id.ivTitleBtnRightImage);
        fadeIconImageView2.setVisibility(8);
        fadeIconImageView2.setScaleType(ImageView.ScaleType.CENTER);
        RelativeLayout.LayoutParams layoutParams12 = new RelativeLayout.LayoutParams(b.e(30), b.e(30));
        layoutParams12.addRule(15);
        fadeIconImageView2.setLayoutParams(layoutParams12);
        relativeLayout6.addView(fadeIconImageView2);
        FadeIconImageView fadeIconImageView3 = new FadeIconImageView(relativeLayout6.getContext());
        fadeIconImageView3.setId(R.id.dsr);
        fadeIconImageView3.setVisibility(8);
        fadeIconImageView3.setScaleType(ImageView.ScaleType.CENTER);
        RelativeLayout.LayoutParams layoutParams13 = new RelativeLayout.LayoutParams(b.e(30), b.e(30));
        layoutParams13.addRule(15);
        layoutParams13.addRule(1, R.id.ivTitleBtnRightImage);
        fadeIconImageView3.setLayoutParams(layoutParams13);
        relativeLayout6.addView(fadeIconImageView3);
        View view = new View(relativeLayout6.getContext());
        view.setVisibility(4);
        RelativeLayout.LayoutParams layoutParams14 = new RelativeLayout.LayoutParams(0, 0);
        layoutParams14.addRule(3, R.id.ivTitleBtnRightImage);
        view.setLayoutParams(layoutParams14);
        relativeLayout6.addView(view);
        relativeLayout5.addView(relativeLayout6);
        relativeLayout.addView(relativeLayout5);
        RelativeLayout relativeLayout7 = new RelativeLayout(relativeLayout.getContext());
        relativeLayout7.setId(R.id.ied);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(b.e(36), b.e(36));
        layoutParams15.rightMargin = b.e(2);
        layoutParams15.addRule(0, R.id.f166811ie3);
        relativeLayout7.setLayoutParams(layoutParams15);
        View imageView = new ImageView(relativeLayout7.getContext());
        imageView.setId(R.id.ews);
        imageView.setBackgroundResource(R.drawable.mini_msg_float_view_top_white);
        RelativeLayout.LayoutParams layoutParams16 = new RelativeLayout.LayoutParams(b.e(24), b.e(24));
        layoutParams16.addRule(12);
        imageView.setLayoutParams(layoutParams16);
        relativeLayout7.addView(imageView);
        TextView textView5 = new TextView(relativeLayout7.getContext());
        textView5.setId(R.id.ewt);
        textView5.setVisibility(8);
        textView5.setGravity(17);
        textView5.setSingleLine();
        textView5.setText("");
        textView5.setTextColor(b.a(R.color.f158017al3));
        textView5.setTextSize(2, 10.0f);
        textView5.setBackgroundResource(R.drawable.skin_tips_newmessage);
        RelativeLayout.LayoutParams layoutParams17 = new RelativeLayout.LayoutParams(-2, b.e(20));
        layoutParams17.addRule(11);
        layoutParams17.addRule(12);
        layoutParams17.bottomMargin = b.e(12);
        layoutParams17.rightMargin = b.e(2);
        textView5.setLayoutParams(layoutParams17);
        relativeLayout7.addView(textView5);
        relativeLayout.addView(relativeLayout7);
        addView(relativeLayout);
        RelativeLayout relativeLayout8 = new RelativeLayout(getContext());
        relativeLayout8.setId(R.id.jse);
        relativeLayout8.setVisibility(8);
        relativeLayout8.setBackgroundColor(b.a(R.color.f156810bz));
        RelativeLayout.LayoutParams layoutParams18 = new RelativeLayout.LayoutParams(-1, b.e(50));
        layoutParams18.addRule(3, R.id.rlCommenTitle);
        relativeLayout8.setLayoutParams(layoutParams18);
        ImageView imageView2 = new ImageView(relativeLayout8.getContext());
        imageView2.setId(R.id.toast_icon);
        RelativeLayout.LayoutParams layoutParams19 = new RelativeLayout.LayoutParams(b.e(20), b.e(20));
        layoutParams19.leftMargin = b.e(12);
        layoutParams19.rightMargin = b.e(6);
        layoutParams19.addRule(9);
        layoutParams19.addRule(15);
        imageView2.setLayoutParams(layoutParams19);
        imageView2.setScaleType(ImageView.ScaleType.FIT_XY);
        imageView2.setImageResource(R.drawable.common_alert_icon);
        relativeLayout8.addView(imageView2);
        TextView textView6 = new TextView(relativeLayout8.getContext());
        textView6.setId(R.id.toast_msg);
        RelativeLayout.LayoutParams layoutParams20 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams20.rightMargin = b.e(12);
        layoutParams20.addRule(15);
        layoutParams20.addRule(1, R.id.toast_icon);
        textView6.setLayoutParams(layoutParams20);
        textView6.setEllipsize(TextUtils.TruncateAt.END);
        textView6.setGravity(17);
        textView6.setSingleLine();
        textView6.setMaxLines(1);
        textView6.setTextSize(2, 18.0f);
        textView6.setText(R.string.f211985ma);
        textView6.setTextColor(b.b(R.color.skin_tips));
        relativeLayout8.addView(textView6);
        View view2 = new View(relativeLayout8.getContext());
        view2.setId(R.id.jsa);
        view2.setBackgroundResource(R.drawable.cqa);
        RelativeLayout.LayoutParams layoutParams21 = new RelativeLayout.LayoutParams(b.e(28), b.e(28));
        layoutParams21.rightMargin = b.e(12);
        layoutParams21.addRule(15);
        layoutParams21.addRule(11);
        view2.setLayoutParams(layoutParams21);
        relativeLayout8.addView(view2);
        addView(relativeLayout8);
    }
}
