package com.tencent.luggage.wxa.h4;

import com.tencent.luggage.wxa.bf.h0;
import com.tencent.luggage.wxa.df.d;
import com.tencent.luggage.wxa.df.f;
import com.tencent.luggage.wxa.df.h;
import com.tencent.luggage.wxa.df.j;
import com.tencent.luggage.wxa.ig.w;
import com.tencent.luggage.wxa.jg.k;
import com.tencent.luggage.wxa.jg.n;
import com.tencent.luggage.wxa.jg.o;
import com.tencent.luggage.wxa.jg.p;
import com.tencent.luggage.wxa.jg.q;
import com.tencent.luggage.wxa.jg.v;
import com.tencent.luggage.wxa.jg.x;
import com.tencent.luggage.wxa.p004if.e0;
import com.tencent.luggage.wxa.p004if.i;
import com.tencent.luggage.wxa.se.l;
import com.tencent.luggage.wxa.tn.w0;
import com.tencent.luggage.wxa.uk.p0;
import com.tencent.luggage.wxa.wj.g;
import com.tencent.luggage.wxa.xd.a1;
import com.tencent.luggage.wxa.xd.b1;
import com.tencent.luggage.wxa.xd.c1;
import com.tencent.luggage.wxa.xd.d1;
import com.tencent.luggage.wxa.xd.n0;
import com.tencent.luggage.wxa.xd.n1;
import com.tencent.luggage.wxa.xd.r0;
import com.tencent.luggage.wxa.xd.s0;
import com.tencent.luggage.wxa.xd.t0;
import com.tencent.luggage.wxa.xd.u0;
import com.tencent.luggage.wxa.xd.v0;
import com.tencent.luggage.wxa.xd.x0;
import com.tencent.luggage.wxa.xd.y0;
import com.tencent.luggage.wxa.xd.z0;
import com.tencent.luggage.wxa.yf.a0;
import com.tencent.luggage.wxa.yf.b0;
import com.tencent.luggage.wxa.yf.c0;
import com.tencent.luggage.wxa.yf.d0;
import com.tencent.luggage.wxa.yf.f0;
import com.tencent.luggage.wxa.yf.g0;
import com.tencent.luggage.wxa.yf.i0;
import com.tencent.luggage.wxa.yf.j0;
import com.tencent.luggage.wxa.yf.k0;
import com.tencent.luggage.wxa.yf.l0;
import com.tencent.luggage.wxa.yf.m;
import com.tencent.luggage.wxa.yf.m0;
import com.tencent.luggage.wxa.yf.o0;
import com.tencent.luggage.wxa.yf.q0;
import com.tencent.luggage.wxa.yf.r;
import com.tencent.luggage.wxa.yf.s;
import com.tencent.luggage.wxa.yf.t;
import com.tencent.luggage.wxa.yf.u;
import com.tencent.luggage.wxa.yf.y;
import com.tencent.luggage.wxa.yf.z;
import com.tencent.luggage.wxa.zf.e;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiOperateRecorder;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiSetBackgroundAudioState;
import com.tencent.mm.plugin.appbrand.jsapi.sensor.JsApiEnableDeviceOrientation;
import com.tencent.mm.plugin.soter.ui.SoterAuthenticationUI;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/* compiled from: P */
/* loaded from: classes8.dex */
public class a {

    /* renamed from: a, reason: collision with root package name */
    public Map f126856a = new HashMap();

    /* renamed from: b, reason: collision with root package name */
    public Map f126857b = new HashMap();

    static {
        n1.a();
        e.a(g.f144278b);
        com.tencent.luggage.wxa.h1.e.a(com.tencent.luggage.wxa.cg.a.class, p0.f142776a);
        e0.f130199a.b();
        i.f130205a.a();
    }

    public Map a() {
        d();
        return this.f126856a;
    }

    public Map b() {
        c();
        return this.f126857b;
    }

    public void c() {
        a(new t0());
        a(new h());
        a(new com.tencent.luggage.wxa.df.c());
        a(new com.tencent.luggage.wxa.df.b());
        a(new com.tencent.luggage.wxa.df.i());
        a(new com.tencent.luggage.wxa.df.g());
        a(new d());
        a(new j());
        a(new com.tencent.luggage.wxa.df.e());
        a(new f());
        a(new o());
        a(new p());
        a(new n());
        a(new k());
        a(new com.tencent.luggage.wxa.yf.h());
        a(new com.tencent.luggage.wxa.yf.n());
        a(new m());
        a(new z0());
        a(new com.tencent.luggage.wxa.zf.f());
        a(new com.tencent.luggage.wxa.zf.h());
        a(new com.tencent.luggage.wxa.yf.c());
        a(new com.tencent.luggage.wxa.xd.p0());
        a(new com.tencent.luggage.wxa.wg.a());
        a(new com.tencent.luggage.wxa.wg.f());
        a(new com.tencent.luggage.wxa.wg.e());
        a(new com.tencent.luggage.wxa.wg.c());
        a(new com.tencent.luggage.wxa.wg.b());
        a(new com.tencent.luggage.wxa.wg.d());
        a(new com.tencent.luggage.wxa.se.f());
        a(new com.tencent.luggage.wxa.se.g());
        a(new com.tencent.luggage.wxa.se.j());
        a(new l());
        a(new com.tencent.luggage.wxa.yf.b());
        a(new com.tencent.luggage.wxa.be.d());
        a(new com.tencent.luggage.wxa.be.f());
        a(new com.tencent.luggage.wxa.be.a());
        a(new com.tencent.luggage.wxa.be.e());
        a(new b1());
        a(new x());
        a(new com.tencent.luggage.wxa.we.b());
        a(new com.tencent.luggage.wxa.we.d());
        a(new com.tencent.luggage.wxa.we.c());
        a(new com.tencent.luggage.wxa.be.c());
        a(new com.tencent.luggage.wxa.zf.g());
        a(new com.tencent.luggage.wxa.zf.i());
        a(new a1());
        a(new com.tencent.luggage.wxa.ye.h());
        a(new com.tencent.luggage.wxa.ye.o());
        a(new com.tencent.luggage.wxa.ye.l());
        a(new com.tencent.luggage.wxa.ye.f());
        a(new com.tencent.luggage.wxa.ye.m());
        a(new com.tencent.luggage.wxa.ye.j());
        a(new com.tencent.luggage.wxa.re.j());
        a(new com.tencent.luggage.wxa.re.n());
        a(new com.tencent.luggage.wxa.re.m());
        a(new com.tencent.luggage.wxa.id.b());
        a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.a());
        a(new s());
        a(new com.tencent.luggage.wxa.ye.g());
        a(new com.tencent.luggage.wxa.ye.n());
        a(new com.tencent.luggage.wxa.ye.k());
        a(new b0());
        a(new z());
        a(new j0());
        a(new com.tencent.luggage.wxa.yf.f());
        a(new u());
        a(new t());
        a(com.tencent.luggage.wxa.gf.p0.a());
        a(new com.tencent.luggage.wxa.kg.c());
        a(new com.tencent.luggage.wxa.kg.a());
        a(new i0());
        a(new com.tencent.luggage.wxa.yf.e());
        a(new com.tencent.luggage.wxa.kg.d());
        a(new com.tencent.luggage.wxa.kg.b());
        a(new com.tencent.luggage.wxa.jf.h());
        a(new com.tencent.luggage.wxa.jf.f());
        a(new a0());
        a(new com.tencent.luggage.wxa.ig.k());
        a(new com.tencent.luggage.wxa.ig.s());
        a(new w());
        a(new com.tencent.luggage.wxa.ig.l());
        a(new com.tencent.luggage.wxa.jg.l());
        a(new com.tencent.luggage.wxa.jg.u());
        a(new q());
        a(new v());
        a(new o0());
        a(new com.tencent.luggage.wxa.dg.a());
        a(new com.tencent.luggage.wxa.bf.t());
        a(new q0());
        a(new c0());
        a(new com.tencent.luggage.wxa.yf.o());
        a(new n0());
        a(new com.tencent.luggage.wxa.xd.o0());
        a(new com.tencent.luggage.wxa.jh.b());
        a(new com.tencent.luggage.wxa.jh.d());
        a(new com.tencent.luggage.wxa.jh.c());
        a(new com.tencent.luggage.wxa.bf.u());
        a(new com.tencent.luggage.wxa.yf.x());
        a(new y());
    }

    public void d() {
        b(new com.tencent.luggage.wxa.ig.g());
        b(new com.tencent.luggage.wxa.ig.m());
        b(new com.tencent.luggage.wxa.ig.c());
        b(new com.tencent.luggage.wxa.ig.d());
        b(new com.tencent.luggage.wxa.ig.e());
        b(new com.tencent.luggage.wxa.ig.f());
        b(new com.tencent.luggage.wxa.ig.x());
        b(new com.tencent.luggage.wxa.ig.h());
        b(new com.tencent.luggage.wxa.ig.q());
        b(new com.tencent.luggage.wxa.ig.y());
        b(new com.tencent.luggage.wxa.ig.k());
        b(new com.tencent.luggage.wxa.ig.s());
        b(new w());
        b(new com.tencent.luggage.wxa.ig.l());
        b(new b0());
        b(new com.tencent.luggage.wxa.yf.j());
        b(new com.tencent.luggage.wxa.yf.q());
        b(new r());
        b(new com.tencent.luggage.wxa.yf.i());
        b(new v0());
        b(new com.tencent.luggage.wxa.p004if.t());
        b(new com.tencent.luggage.wxa.ih.f());
        b(new com.tencent.luggage.wxa.ih.g());
        b(new com.tencent.luggage.wxa.hh.e());
        b(new com.tencent.luggage.wxa.hh.d());
        b(new com.tencent.luggage.wxa.hh.f());
        b(new com.tencent.luggage.wxa.ef.l());
        b(new com.tencent.luggage.wxa.ef.i());
        b(new com.tencent.luggage.wxa.ef.j());
        b(new k());
        b(new com.tencent.luggage.wxa.zd.l());
        b(new com.tencent.luggage.wxa.ve.c());
        b(new com.tencent.luggage.wxa.ve.e());
        b(new m0());
        b(new j0());
        b(new com.tencent.luggage.wxa.yf.f());
        b(new i0());
        b(new com.tencent.luggage.wxa.yf.e());
        b(new com.tencent.luggage.wxa.yf.d());
        b(new com.tencent.luggage.wxa.se.f());
        b(new o());
        b(new p());
        b(new n());
        b(new com.tencent.luggage.wxa.jg.r());
        b(new z0());
        b(new com.tencent.luggage.wxa.df.g());
        b(new com.tencent.luggage.wxa.xd.p0());
        b(new com.tencent.luggage.wxa.df.c());
        b(new com.tencent.luggage.wxa.fg.b());
        b(new com.tencent.luggage.wxa.fg.c());
        b(new com.tencent.luggage.wxa.fg.e());
        b(new com.tencent.luggage.wxa.fg.d());
        b(new JsApiEnableDeviceOrientation());
        b(new com.tencent.luggage.wxa.ig.t());
        b(new com.tencent.luggage.wxa.ig.u());
        b(new com.tencent.luggage.wxa.sh.a());
        b(new com.tencent.luggage.wxa.se.e());
        b(new com.tencent.luggage.wxa.bg.c());
        b(new com.tencent.luggage.wxa.bg.f());
        b(new com.tencent.luggage.wxa.bg.b());
        b(new com.tencent.luggage.wxa.bg.e());
        b(new com.tencent.luggage.wxa.bg.d());
        b(new com.tencent.luggage.wxa.bg.g());
        b(new com.tencent.luggage.wxa.bg.a());
        b(new s0());
        b(new x0());
        b(new com.tencent.luggage.wxa.ig.n());
        b(new com.tencent.luggage.wxa.ig.o());
        b(new com.tencent.luggage.wxa.p004if.v());
        b(new com.tencent.luggage.wxa.yf.n0());
        b(new com.tencent.luggage.wxa.gg.c());
        b(new com.tencent.luggage.wxa.jg.g());
        b(new com.tencent.luggage.wxa.jg.i());
        b(new com.tencent.luggage.wxa.jg.s());
        b(new com.tencent.luggage.wxa.he.m());
        b(new com.tencent.luggage.wxa.he.b());
        b(new com.tencent.luggage.wxa.he.g());
        b(new com.tencent.luggage.wxa.he.p());
        b(new com.tencent.luggage.wxa.he.q());
        b(new com.tencent.luggage.wxa.he.h());
        b(new com.tencent.luggage.wxa.he.k());
        b(new com.tencent.luggage.wxa.he.j());
        b(new com.tencent.luggage.wxa.he.o());
        b(new com.tencent.luggage.wxa.he.e());
        b(new com.tencent.luggage.wxa.he.c());
        b(new com.tencent.luggage.wxa.he.a());
        b(new com.tencent.luggage.wxa.he.f());
        b(new com.tencent.luggage.wxa.he.d());
        b(new com.tencent.luggage.wxa.he.n());
        b(new com.tencent.luggage.wxa.he.r());
        b(new com.tencent.luggage.wxa.he.l());
        b(new com.tencent.luggage.wxa.he.i());
        b(new com.tencent.luggage.wxa.ie.c());
        b(new com.tencent.luggage.wxa.ie.d());
        b(new com.tencent.luggage.wxa.ie.e());
        b(new com.tencent.luggage.wxa.ie.f());
        b(new com.tencent.luggage.wxa.ie.g());
        b(new com.tencent.luggage.wxa.ie.h());
        b(new com.tencent.luggage.wxa.ie.i());
        b(new com.tencent.luggage.wxa.yf.p());
        b(new com.tencent.luggage.wxa.jf.e());
        b(new b1());
        b(new com.tencent.luggage.wxa.zd.k());
        b(new JsApiSetBackgroundAudioState());
        b(new com.tencent.mm.plugin.appbrand.jsapi.audio.b());
        b(new com.tencent.luggage.wxa.gg.d());
        b(new com.tencent.luggage.wxa.gg.a());
        b(new u0());
        b(new com.tencent.luggage.wxa.ve.b());
        b(new com.tencent.luggage.wxa.jg.l());
        b(new com.tencent.luggage.wxa.jg.u());
        b(new com.tencent.luggage.wxa.jg.w());
        b(new x());
        b(new com.tencent.luggage.wxa.gg.g());
        b(new com.tencent.luggage.wxa.gg.f());
        b(new com.tencent.luggage.wxa.gg.h());
        b(new com.tencent.luggage.wxa.cf.c());
        b(new com.tencent.luggage.wxa.cf.d());
        b(new com.tencent.luggage.wxa.cf.e());
        b(new com.tencent.luggage.wxa.wg.c());
        b(new com.tencent.luggage.wxa.p004if.x());
        b(new com.tencent.luggage.wxa.p004if.y());
        b(new r0());
        b(new com.tencent.luggage.wxa.jg.t());
        b(new com.tencent.luggage.wxa.xd.j0());
        b(new com.tencent.luggage.wxa.se.i());
        b(new com.tencent.luggage.wxa.ye.i());
        b(new com.tencent.luggage.wxa.jf.h());
        b(new com.tencent.luggage.wxa.jf.f());
        b(new com.tencent.luggage.wxa.jf.i());
        b(new a0());
        b(new com.tencent.luggage.wxa.yf.p0());
        b(new y0());
        b(new d0());
        b(new a1());
        b(new z());
        b(new com.tencent.luggage.wxa.fe.b());
        b(new com.tencent.luggage.wxa.fe.c(SoterAuthenticationUI.class));
        b(new com.tencent.luggage.wxa.pf.b(com.tencent.luggage.wxa.pf.a.f137501g, null));
        b(new com.tencent.luggage.wxa.pf.c(com.tencent.luggage.wxa.pf.a.f137501g, null));
        b(new com.tencent.luggage.wxa.pf.d());
        b(new com.tencent.luggage.wxa.of.b(null));
        b(new com.tencent.luggage.wxa.of.c(null));
        b(new com.tencent.luggage.wxa.of.d());
        b(new com.tencent.luggage.wxa.qf.b(null));
        b(new com.tencent.luggage.wxa.qf.c(null));
        b(new com.tencent.luggage.wxa.qf.d());
        b(new c1());
        b(new com.tencent.luggage.wxa.xd.i0());
        b(new com.tencent.luggage.wxa.re.l());
        b(new l0());
        b(new JsApiOperateRecorder());
        b(new com.tencent.luggage.wxa.ih.e());
        b(new com.tencent.luggage.wxa.zd.g());
        b(new com.tencent.luggage.wxa.zd.h());
        b(new com.tencent.luggage.wxa.zd.m());
        b(new com.tencent.luggage.wxa.zd.j());
        b(new com.tencent.mm.plugin.appbrand.jsapi.audio.a());
        b(new com.tencent.luggage.wxa.zd.i());
        b(new com.tencent.luggage.wxa.ef.g());
        b(new com.tencent.luggage.wxa.ef.f());
        b(new com.tencent.luggage.wxa.ef.d());
        b(new com.tencent.luggage.wxa.fe.a());
        b(new com.tencent.luggage.wxa.mh.d());
        b(new com.tencent.luggage.wxa.mh.e());
        b(new com.tencent.luggage.wxa.mh.c());
        b(new com.tencent.luggage.wxa.mh.b());
        b(new com.tencent.luggage.wxa.mh.a());
        b(new com.tencent.luggage.wxa.rf.g(null));
        b(new com.tencent.luggage.wxa.rf.h());
        b(new com.tencent.luggage.wxa.rf.f());
        b(new com.tencent.luggage.wxa.rf.d());
        b(new com.tencent.luggage.wxa.rf.e());
        b(new com.tencent.luggage.wxa.uf.i());
        b(new com.tencent.luggage.wxa.uf.l());
        b(new com.tencent.luggage.wxa.uf.f());
        b(new com.tencent.luggage.wxa.uf.e());
        b(new com.tencent.luggage.wxa.uf.d());
        b(new com.tencent.luggage.wxa.uf.k());
        b(new com.tencent.luggage.wxa.uf.m());
        b(new com.tencent.luggage.wxa.uf.n());
        b(new com.tencent.luggage.wxa.uf.o());
        b(new com.tencent.luggage.wxa.uf.g());
        b(new com.tencent.luggage.wxa.uf.j());
        b(new com.tencent.luggage.wxa.uf.h());
        b(new com.tencent.luggage.wxa.yf.e0());
        b(new g0());
        b(new f0());
        b(new com.tencent.luggage.wxa.yf.g());
        b(new k0());
        b(new com.tencent.luggage.wxa.kg.c());
        b(new com.tencent.luggage.wxa.kg.a());
        b(new com.tencent.luggage.wxa.kg.d());
        b(new com.tencent.luggage.wxa.kg.b());
        b(new com.tencent.luggage.wxa.nf.f(com.tencent.luggage.wxa.nf.f.f135778h, null));
        b(new com.tencent.luggage.wxa.nf.i(null));
        b(new com.tencent.luggage.wxa.yf.v());
        b(new com.tencent.luggage.wxa.nf.e());
        b(new com.tencent.luggage.wxa.nf.g());
        b(new com.tencent.luggage.wxa.nf.d());
        b(new com.tencent.luggage.wxa.bf.l0());
        b(new com.tencent.luggage.wxa.bf.m0());
        b(new com.tencent.luggage.wxa.bf.o());
        b(new com.tencent.luggage.wxa.bf.p());
        b(new com.tencent.luggage.wxa.bf.q());
        b(new com.tencent.luggage.wxa.bf.g0());
        b(new com.tencent.luggage.wxa.bf.e0());
        b(new com.tencent.luggage.wxa.bf.r0());
        b(new com.tencent.luggage.wxa.bf.y());
        b(new com.tencent.luggage.wxa.bf.c0());
        b(new com.tencent.luggage.wxa.bf.k0());
        b(new com.tencent.luggage.wxa.bf.h());
        b(new com.tencent.luggage.wxa.bf.o0());
        b(new com.tencent.luggage.wxa.bf.s());
        b(new com.tencent.luggage.wxa.bf.n());
        b(new com.tencent.luggage.wxa.bf.d0());
        b(new com.tencent.luggage.wxa.bf.q0());
        b(new com.tencent.luggage.wxa.bf.x());
        b(new com.tencent.luggage.wxa.bf.b0());
        b(new com.tencent.luggage.wxa.bf.j0());
        b(new com.tencent.luggage.wxa.bf.g());
        b(new com.tencent.luggage.wxa.bf.n0());
        b(new com.tencent.luggage.wxa.bf.r());
        b(new com.tencent.luggage.wxa.bf.m());
        b(new com.tencent.luggage.wxa.bf.p0());
        b(new com.tencent.luggage.wxa.bf.f0());
        b(new com.tencent.luggage.wxa.bf.k());
        b(new com.tencent.luggage.wxa.bf.l());
        b(new h0());
        b(new com.tencent.luggage.wxa.bf.i0());
        b(new com.tencent.luggage.wxa.bf.i());
        b(new com.tencent.luggage.wxa.bf.j());
        b(new com.tencent.luggage.wxa.bf.z());
        b(new com.tencent.luggage.wxa.bf.a0());
        b(new com.tencent.luggage.wxa.se.b());
        b(new com.tencent.luggage.wxa.se.c());
        b(new com.tencent.luggage.wxa.jg.h());
        b(new com.tencent.luggage.wxa.yd.a());
        b(new d1());
        b(new com.tencent.luggage.wxa.xd.m0());
        b(new t());
        b(new u());
        b(com.tencent.luggage.wxa.gf.p0.b());
        b(new com.tencent.luggage.wxa.kf.c());
        b(new com.tencent.luggage.wxa.kf.d());
        b(new com.tencent.luggage.wxa.kf.a());
        b(new com.tencent.luggage.wxa.kf.b());
        b(new n0());
        b(new com.tencent.luggage.wxa.xd.o0());
        b(new q());
        b(new v());
        b(new o0());
        b(new com.tencent.luggage.wxa.nf.h());
        b(new com.tencent.luggage.wxa.zd.n());
        b(new q0());
        b(new c0());
        b(new com.tencent.luggage.wxa.ye.h());
        b(new com.tencent.luggage.wxa.ye.o());
        b(new com.tencent.luggage.wxa.ye.l());
        b(new com.tencent.luggage.wxa.ye.f());
        b(new com.tencent.luggage.wxa.ye.m());
        b(new com.tencent.luggage.wxa.ye.j());
        b(new com.tencent.luggage.wxa.ye.g());
        b(new com.tencent.luggage.wxa.ye.n());
        b(new com.tencent.luggage.wxa.ye.k());
        b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.a());
        b(new com.tencent.luggage.wxa.wg.a());
        b(new com.tencent.luggage.wxa.wg.f());
        b(new com.tencent.luggage.wxa.wg.e());
        b(new com.tencent.luggage.wxa.wg.b());
        b(new com.tencent.luggage.wxa.wg.d());
        b(new com.tencent.luggage.wxa.ci.e());
        b(new com.tencent.luggage.wxa.ci.i());
        b(new com.tencent.luggage.wxa.ci.h());
        b(new com.tencent.luggage.wxa.ci.g());
        b(new com.tencent.luggage.wxa.wh.e());
        b(new com.tencent.luggage.wxa.wh.i());
        b(new com.tencent.luggage.wxa.wh.f());
        b(new com.tencent.luggage.wxa.wh.h());
        b(new com.tencent.luggage.wxa.wh.g());
        b(new com.tencent.luggage.wxa.yh.d());
        b(new com.tencent.luggage.wxa.yh.g());
        b(new com.tencent.luggage.wxa.yh.e());
        b(new com.tencent.luggage.wxa.yh.f());
        b(new com.tencent.luggage.wxa.bf.v());
        b(new com.tencent.luggage.wxa.bf.w());
        b(new com.tencent.luggage.wxa.yf.h0());
        b(new com.tencent.luggage.wxa.yf.h());
        b(new com.tencent.luggage.wxa.jh.b());
        b(new com.tencent.luggage.wxa.jh.d());
        b(new com.tencent.luggage.wxa.jh.c());
        b(new com.tencent.luggage.wxa.o4.b());
        b(new com.tencent.luggage.wxa.hg.c());
        b(new com.tencent.luggage.wxa.hg.e());
        b(new com.tencent.luggage.wxa.hg.f());
        b(new com.tencent.luggage.wxa.xe.a());
        b(new com.tencent.luggage.wxa.xe.b());
        b(new com.tencent.luggage.wxa.xd.q0());
        b(new com.tencent.luggage.wxa.yf.w());
        b(new com.tencent.luggage.wxa.yf.x());
        b(new y());
    }

    public void a(List list) {
        if (list == null || list.size() <= 0) {
            return;
        }
        Iterator it = list.iterator();
        while (it.hasNext()) {
            a((com.tencent.luggage.wxa.xd.o) it.next());
        }
    }

    public void b(List list) {
        if (list == null || list.size() <= 0) {
            return;
        }
        Iterator it = list.iterator();
        while (it.hasNext()) {
            b((com.tencent.luggage.wxa.xd.o) it.next());
        }
    }

    public void a(com.tencent.luggage.wxa.xd.o oVar) {
        if (oVar == null || w0.c(oVar.getName())) {
            return;
        }
        this.f126857b.put(oVar.getName(), oVar);
    }

    public void b(com.tencent.luggage.wxa.xd.o oVar) {
        if (oVar == null || w0.c(oVar.getName())) {
            return;
        }
        this.f126856a.put(oVar.getName(), oVar);
    }
}
