package cooperation.qqcircle.report;

import com.tencent.qphone.base.util.QLog;
import java.io.Serializable;

/* compiled from: P */
/* loaded from: classes28.dex */
public class QCircleTaskReportInfo implements Serializable {
    public String albumId;
    public long author_uin;
    public int backendPicHeight;
    public long backendPicSize;
    public int backendPicWidth;
    public String city_name;
    public long clientCompressMediaBitrate;
    public int clientCompressPicHeight;
    public long clientCompressPicSize;
    public int clientCompressPicWidth;
    public String country_name;
    public int editedPicHeight;
    public long editedPicSize;
    public int editedPicWidth;
    public long editedVideoMediaBitrate;
    public String feed_tag;
    public String feedid;
    public boolean hasCompress = false;
    public int is_video;
    public String lloc;
    public long mediaOriginBitrate;
    public int origPicHeight;
    public long origPicSize;
    public int origPicWidth;
    public String picture_format;
    public String place;
    public String place_name;
    public String prov_name;
    public long retCode;
    public String shoot_model;
    public String shoot_place;
    public String shoot_product;
    public String shooting_time;
    public int total_upload_num;
    public String traceId;
    public String txtinfo;
    public String up_place;
    public int up_source;
    public int up_type;
    public String vid;

    public String toString() {
        StringBuffer stringBuffer = new StringBuffer("QCircleTaskReportInfo{\n");
        stringBuffer.append("retCode=");
        stringBuffer.append(this.retCode);
        stringBuffer.append('\n');
        stringBuffer.append(", up_source=");
        stringBuffer.append(this.up_source);
        stringBuffer.append('\n');
        stringBuffer.append(", up_type=");
        stringBuffer.append(this.up_type);
        stringBuffer.append('\n');
        stringBuffer.append(", is_video=");
        stringBuffer.append(this.is_video);
        stringBuffer.append('\n');
        stringBuffer.append(", txtinfo='");
        stringBuffer.append(this.txtinfo);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", lloc='");
        stringBuffer.append(this.lloc);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", vid='");
        stringBuffer.append(this.vid);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", feedid='");
        stringBuffer.append(this.feedid);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", total_upload_num=");
        stringBuffer.append(this.total_upload_num);
        stringBuffer.append('\n');
        stringBuffer.append(", shooting_time='");
        stringBuffer.append(this.shooting_time);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        if (QLog.isColorLevel()) {
            stringBuffer.append(", place='");
            stringBuffer.append(this.place);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
            stringBuffer.append(", up_place='");
            stringBuffer.append(this.up_place);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
            stringBuffer.append(", shoot_product='");
            stringBuffer.append(this.shoot_product);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
            stringBuffer.append(", shoot_model='");
            stringBuffer.append(this.shoot_model);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
            stringBuffer.append(", picture_format='");
            stringBuffer.append(this.picture_format);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
            stringBuffer.append(", country_name='");
            stringBuffer.append(this.country_name);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
            stringBuffer.append(", prov_name='");
            stringBuffer.append(this.prov_name);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
            stringBuffer.append(", city_name='");
            stringBuffer.append(this.city_name);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
            stringBuffer.append(", place_name='");
            stringBuffer.append(this.place_name);
            stringBuffer.append('\'');
            stringBuffer.append('\n');
        }
        stringBuffer.append(", feed_tag='");
        stringBuffer.append(this.feed_tag);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", author_uin=");
        stringBuffer.append(this.author_uin);
        stringBuffer.append('\n');
        stringBuffer.append(", shoot_place='");
        stringBuffer.append(this.shoot_place);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", albumId='");
        stringBuffer.append(this.albumId);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", traceId='");
        stringBuffer.append(this.traceId);
        stringBuffer.append('\'');
        stringBuffer.append('\n');
        stringBuffer.append(", origPicWidth=");
        stringBuffer.append(this.origPicWidth);
        stringBuffer.append('\n');
        stringBuffer.append(", origPicHeight=");
        stringBuffer.append(this.origPicHeight);
        stringBuffer.append('\n');
        stringBuffer.append(", origPicSize=");
        stringBuffer.append(this.origPicSize);
        stringBuffer.append('\n');
        stringBuffer.append(", mediaOriginBitrate=");
        stringBuffer.append(this.mediaOriginBitrate);
        stringBuffer.append('\n');
        stringBuffer.append(", edited_pic_width=");
        stringBuffer.append(this.editedPicWidth);
        stringBuffer.append('\n');
        stringBuffer.append(", edited_pic_height=");
        stringBuffer.append(this.editedPicHeight);
        stringBuffer.append('\n');
        stringBuffer.append(", edited_pic_size=");
        stringBuffer.append(this.editedPicSize);
        stringBuffer.append('\n');
        stringBuffer.append(", edited_video_mediaBitrate=");
        stringBuffer.append(this.editedVideoMediaBitrate);
        stringBuffer.append('\n');
        stringBuffer.append(", client_compress_pic_width=");
        stringBuffer.append(this.clientCompressPicWidth);
        stringBuffer.append('\n');
        stringBuffer.append(", client_compress_pic_height=");
        stringBuffer.append(this.clientCompressPicHeight);
        stringBuffer.append('\n');
        stringBuffer.append(", client_compress_pic_size=");
        stringBuffer.append(this.clientCompressPicSize);
        stringBuffer.append('\n');
        stringBuffer.append(", client_compress_mediaBitrate=");
        stringBuffer.append(this.clientCompressMediaBitrate);
        stringBuffer.append('\n');
        stringBuffer.append(", backendPicWidth=");
        stringBuffer.append(this.backendPicWidth);
        stringBuffer.append('\n');
        stringBuffer.append(", backendPicHeight=");
        stringBuffer.append(this.backendPicHeight);
        stringBuffer.append('\n');
        stringBuffer.append(", backendPicSize=");
        stringBuffer.append(this.backendPicSize);
        stringBuffer.append('\n');
        stringBuffer.append(", hasCompress=");
        stringBuffer.append(this.hasCompress);
        stringBuffer.append('\n');
        stringBuffer.append('}');
        return stringBuffer.toString();
    }
}
