package com.qzone.proxy.covercomponent;

import com.qzone.util.l;
import com.tencent.avbiz.Constants;
import com.tencent.mobileqq.R;
import com.tencent.qqmini.sdk.core.utils.WnsConfig;
import common.config.service.QzoneConfig;

/* compiled from: P */
/* loaded from: classes39.dex */
public class QzoneCoverConst {
    public static final String ACTION_COVER_IMG_CROP_END = "action.com.qzone.cover.ui.activity.QZoneCoverSetCustomActivity.cover_img_crop_end";
    public static final String ACTION_SET_COVER_SUCCESS = "action.com.qzone.cover.set_cover_success";
    public static final String ACTION_WEBVIEW_UPLOADING_VIDEO_COVER = "com.tencent.mobileqq.action.ACTION_WEBVIEW_UPLOADING_VIDEO_COVER";
    public static final int ALIAN_CENTER = 3;
    public static final int ALIAN_DEFAULT = 0;
    public static final int ALIAN_DOWN = 2;
    public static final int ALIAN_UP = 1;
    public static final String CONFIG_PARAM_COVER_SET_JIGSAW = "cover_setjigsaw";
    public static final String COVER_EXTINFO_DYNAMIC_ALBUM_STATIC_PIC_URL = "dynamic_album_cover_static_pic_url";
    public static final String COVER_EXTINFO_DYNAMIC_ALBUM_TEMPLATE_ID = "dynamic_album_cover_template_id";
    public static final String COVER_EXTINFO_WEBVIEW_H5_URL = "custom_webview_url";
    public static final String COVER_EXTINOF_DYNAMIC_ALBUM_H5_URL = "dynamic_album_cover_h5_url";
    public static final String COVER_QZONE_SHOW_DOWNGRADE_BG = "qzone_show_downgrade_bg_url";
    public static final String COVER_QZONE_SHOW_FG_ID = "qzone_show_fg_id";
    public static final String COVER_QZONE_SHOW_FG_IMG_COUNT = "qzone_show_fg_img_count";
    public static final String COVER_QZONE_SHOW_FG_ZIP = "qzone_show_fg_zip";
    public static final String COVER_QZONE_SHOW_FORCE_DOWNGRADE_FLAG = "qzone_show_force_downgrade_flag";
    public static final String COVER_QZONE_SHOW_FULL_SCREEN_ALIGN = "qzone_show_fullscreen_align";
    public static final String COVER_QZONE_SHOW_FULL_SCREEN_URL = "qzone_show_fullscreen_url";
    public static final String COVER_QZONE_SHOW_OLD_COVER_ID = "qzone_show_old_id";
    public static final String COVER_QZONE_SHOW_OLD_COVER_TYPE = "qzone_show_old_type";
    public static final String COVER_QZONE_SHOW_TRANS = "qzone_show_fullscreen_transparency";
    public static final String COVER_QZONE_SHOW_USE_DOWNGRADE = "qzone_show_downgrade";
    public static final int COVER_REFER_AVATAR_PREVIEW = 4;
    public static final int COVER_REFER_COVER_PREVIEW = 3;
    public static final int COVER_REFER_FEED = 1;
    public static final int COVER_REFER_HOME = 2;
    public static final int COVER_REFER_UNKNOWN = 0;
    public static final String COVER_SHOW_GUIDE = "CoverShowGuide";
    public static final String COVER_STORE_ACTIVITY_FULL_NAME = "com.qzone.cover.ui.activity.QZoneCoverSetCustomActivity";
    public static final String COVER_STRING_TYPE = "COVER_STRING_TYPE";
    public static final int COVER_TRANSPARENCY_DEFAULT_VALUE = 255;
    public static final int COVER_TYPE_COCOS2DX = 14;
    public static final int COVER_TYPE_CUSTOM_DYNAMIC_ALBUM_COVER = 10;
    public static final int COVER_TYPE_CUSTOM_GIF_COVER = 16;
    public static final int COVER_TYPE_CUSTOM_WEBVIEW = 8;
    public static final int COVER_TYPE_DEFAULT = 3;
    public static final int COVER_TYPE_DYNAMIC_COVER = 11;
    public static final int COVER_TYPE_GAME = 5;
    public static final int COVER_TYPE_HTML_DYNAMIC_COVER = 12;
    public static final int COVER_TYPE_JIGSAW = 2;
    public static final int COVER_TYPE_MAX = 19;
    public static final int COVER_TYPE_MOVING = 1;
    public static final int COVER_TYPE_MUSIC_COVER = 19;
    public static final int COVER_TYPE_NEW_VIDEO_COVER = 15;
    public static final int COVER_TYPE_PANORAMA_COVER = 18;
    public static final int COVER_TYPE_QZONE_SHOW = 6;
    public static final int COVER_TYPE_STATIC = 0;
    public static final int COVER_TYPE_SUPER_COVER = 7;
    public static final int COVER_TYPE_UNKNOWN = 4;
    public static final int COVER_TYPE_VIDEO_COVER = 9;
    public static final int COVER_TYPE_WEATHER_COVER = 13;
    public static final int COVER_TYPE_WEBVIEW_COVER = 17;
    public static final int CROP_CENTER = 0;
    public static final String DEFAULT_COVER = "https://qzonestyle.gtimg.cn/qzone/client/mqq/cover/Qzone-cover-day.png.webp";
    public static final String DEFAULT_COVER_NIGHT = "https://qzonestyle.gtimg.cn/qzone/client/mqq/cover/Qzone-cover-night.png.webp";
    public static final String EVENT_CODE_VIDEO_COVER_GUEST_VISIT = "QzoneVideoCover_GuestVisit";
    public static final String EVENT_CODE_VIDEO_COVER_HOST_VISIT = "QzoneVideoCover_HostVisit";
    public static final String EVENT_CODE_VIDEO_COVER_SET = "QzoneVideoCover_Set";
    public static final int FROME_COVER_FEED = 4;
    public static final int FROME_FEED = 1;
    public static final int FROME_FEED_BANNER = 5;
    public static final int FROME_FEED_FRIEND = 9;
    public static final int FROME_FEED_SELF = 8;
    public static final int FROME_PROFILE_CARD = 3;
    public static final int FROME_PROFILE_CARD_BANNER = 7;
    public static final int FROME_USERHOME = 2;
    public static final int FROME_USERHOME_BANNER = 6;
    public static final String FULL_SCREEN_ALIGN_BOTTOM = "2";
    public static final String FULL_SCREEN_ALIGN_CENTER = "0";
    public static final String FULL_SCREEN_ALIGN_TOP = "1";
    public static final String HTTP_TYPE_QZONE_DOWNLOAD_COVER_PIC = "qzCvPicd";
    public static final String INTENT_PARAM_CURRENT_COVER = "current_cover";
    public static final String INTENT_PARAM_DIRECT_SELECTPHOTO = "direct_select_photo";
    public static final String INTENT_PARAM_FROM = "key_from";
    public static final String INTENT_PARAM_JIGSAW_OPEN = "jigsaw_open";
    public static final String INTENT_PARAM_PHOTOWALL_MODE = "photowall_mode";
    public static final String INTENT_PARAM_PHOTOWALL_UPDATED = "photowall_updated";
    public static final String INTENT_PARAM_SET_SOURCE = "set_source";
    public static final String INTENT_PARAM_SHOW_WIDGET_SET = "showWidgetSet";
    public static final String INTENT_PARAM_UIN = "cover_uin";
    public static final String KEY_ACTIVITY_COVER_URL = "act_jump";
    public static final String KEY_HIGH_RESOLUTION = "HigeResolutionCover";
    public static final String KEY_IS_QZONE_SHOW = "qzone_show";
    public static final String KEY_LOW_RESOLUTION = "LowResolutionCover";
    public static final String KEY_QZONE_SHOW_BG_URL = "qzone_show_url";
    public static final String KEY_TRANSPARENCY = "iTransparency";
    public static final String KEY_VIDEO_COVER_CLIENT_KEY = "strClientKey";
    public static final String KEY_VIDEO_COVER_DURATION = "strVideoCoverDuration";
    public static final String KEY_VIDEO_COVER_LOCAL_CLIENT_KEY = "strLocalClientKey";
    public static final String KEY_VIDEO_COVER_LOCAL_PATH = "strVideoCoverLocalPath";
    public static final String KEY_VIDEO_COVER_LOCAL_PIC = "strVideoCoverLocalPic";
    public static final String KEY_VIDEO_COVER_LOCAL_PIC_HEIGHT = "iLocalVideoHeight";
    public static final String KEY_VIDEO_COVER_LOCAL_PIC_WIDTH = "iLocalVideoWidth";
    public static final String KEY_VIDEO_COVER_LOCAL_VIDEO_ID = "strAlbumVideoId";
    public static final String KEY_VIDEO_COVER_ORIGINAL_TYPE = "originalType";
    public static final String KEY_VIDEO_COVER_PIC = "strVideoCoverPic";
    public static final String KEY_VIDEO_COVER_PIC_HEIGHT = "iVideoHeight";
    public static final String KEY_VIDEO_COVER_PIC_WIDTH = "iVideoWidth";
    public static final String KEY_VIDEO_COVER_PLAY_URL = "strVideoCoverPlayUrl";
    public static final String KEY_VIDEO_COVER_START_TIME = "strVideoCoverStartTime";
    public static final String KEY_VIDEO_COVER_STATUS = "iVideoCoverStatus";
    public static final String KEY_VIDEO_ID = "strVideoId";
    public static final String LIMIT_PAGE_COVER = "https://qzonestyle.gtimg.cn/aoi/sola/20190402163746_VrByepBYlY.png";
    public static final String MAIN_KEY_H5URL = "H5Url";
    public static final String MAIN_QZONE_SETTING = "QZoneSetting";
    public static final int MATCH_WIDTH_BOTTOM = 7;
    public static final int MATCH_WIDTH_CENTER = 8;
    public static final int MATCH_WIDTH_TOP = 6;
    public static final int MAX_PHOTO_NUM = 8;
    public static final int MSG_COVER_INVALIDATE = 1192;
    public static final int MSG_COVER_UPDATE_UI = 1000024;
    public static final int MSG_SET_SUPER_COVER = 1193;
    public static final int MSG_UNSET_SUPER_COVER = 1194;
    public static final int NONWIFI_PHOTO_NUM = 3;
    public static final String PARAM_CACHE_DATA = "CoverCacheData";
    public static final String PERMISSION = "com.tencent.msg.permission.pushnotify";
    public static final String PRELOAD_COVER_UIN = "preload_cover_uin";
    public static final String PRELOAD_COVER_URL = "preload_cover_url";
    public static final String QZONE_COVER_SERVICE_TAG = "QZoneCoverService";
    public static final String QZONE_SHOW_URL = "https://h5.qzone.qq.com/qzoneshow/cover/{uin}/qzshow?screenWidth={screenWidth}&qua={qua}&_wv=1029&hideperson={hideperson}";
    public static final String REFER_QZONE = "qzone";
    public static final String REFER_USERHOME = "userhome";
    public static final int REQUEST_CODE_CUSTOM_LOCAL = 2;
    public static final int REQUEST_CODE_CUSTOM_QZONE = 3;
    public static final int REQUEST_CODE_OPEN_VIP = 4;
    public static final int REQUEST_CODE_PHOTOWALL = 1;
    public static final int REQUEST_CODE_SET_COVER = 7;
    public static final int REQUEST_CODE_SET_LOCAL_COVER = 8;
    public static final int REQUEST_CODE_WIDGET_ENABLE = 6;
    public static final int REQUEST_CODE_WIDGET_ID = 5;
    public static final String SECONDARY_COVER_DYNAMIC_ALBUM_SETTING_URL = "DynamicAlbumSettingUrl";
    public static final String SECONDARY_COVER_DYNAMIC_ALBUM_SETTING_URL_DEFAULT = "https://h5.qzone.qq.com/bgstore/index?_wv=2098179&uin={uin}&from={from}&page=1&qua={qua}&router=video&_proxy=1";
    public static final String SECONDARY_COVER_GIF_COVER_MALL_URL = "CoverGifMall";
    public static final String SECONDARY_COVER_PREVIEW = "CoverPreview";
    public static final String SECONDARY_COVER_QZONE_SHOW_BEST_DEVICE_LOW_MEMORY_USE_HECHENGTU = "QzoneShowBestDeviceLowMemoryUseHechengTu";
    public static final String SECONDARY_COVER_QZONE_SHOW_BEST_DEVICE_LOW_MEMORY_USE_HECHENGTU_DEFAULT = "1";
    public static final String SECONDARY_COVER_QZONE_SHOW_BG_IMAGE_CUT_RATE = "QzoneShowBgImageCutRate";
    public static final String SECONDARY_COVER_QZONE_SHOW_GUEST_PAGE_URL = "QzoneShowGuestPageUrl";
    public static final String SECONDARY_COVER_QZONE_SHOW_NEED_REPORT_DENGTA = "QzoneShowNeedReportDengTa";
    public static final String SECONDARY_COVER_QZONE_SHOW_NEED_REPORT_DENGTA_DEFAULT = "1";
    public static final String SECONDARY_COVER_QZONE_SHOW_OFFLINE_DOMAIN = "QzoneShowOfflineDomain";
    public static final String SECONDARY_COVER_QZONE_SHOW_SETTING_URL = "QzoneShowSettingUrl";
    public static final String SECONDARY_COVER_QZONE_SHOW_URL = "AndroidQzoneShowCover";
    public static final String SECONDARY_COVER_QZONE_SHOW_USE_HECHENGTU_IMAGE_AND_EMPTY_WEBVIEW = "QzoneShowUseHechengtuAndEmptyWebview";
    public static final String SECONDARY_COVER_STORE = "CoverStore";
    public static final String SECONDARY_COVER_VIDEO_AUTOPLAY_BLACKLIST = "VideoCoverAutoPlayBlackList";
    public static final String SECONDARY_COVER_VIDEO_USER_DEFINE_TAB_URL = "CoverUserDefined";
    public static final String SECONDARY_FAMOUS_SPACE_COVER_BG_IMAGE_URL = "HybridCoverBgImage";
    public static final String SECONDARY_FAMOUS_SPACE_COVER_BG_IMAGE_URL_DEFAULT = "https://qzonestyle.gtimg.cn/qzone/hybrid/app/vpage/images/avatar/{uin}.jpg?t={timestamp}";
    public static final int SECONDARY_QZONE_SHOW_CUT_RATE_DEFAULT = 80;
    public static final String SECONDARY_QZONE_SHOW_GUEST_PAGE_URL_DEFAULT = "https://h5.qzone.qq.com/qzoneshow/cover/{uin}/qzshowFull?_wv=18875395&incover=no&_ws=32&qzUseTransparentNavBar=1&_bid=2197&screenWidth={screenWidth}&qua={qua}";
    public static final String SECONDARY_QZONE_SHOW_SETTING_URL_DEFAULT = "https://h5.qzone.qq.com/qzoneshow/setcover?_wv=18875395&_ws=32&_proxy=1&screenWidth={screenWidth}&qua={qua}&qzUseTransparentNavBar=1";
    public static final String SECONDARY_WEBVIEW_COERR = "WebviewCover";
    public static final String SECOND_KEY_QZONE_DEFAULT_COVER = "QzoneDefaultCover";
    public static final String SECOND_KEY_QZONE_DEFAULT_COVER_NIGHT = "QzoneNightDefaultCover";
    public static final String SECOND_KEY_QZONE_LIMIT_PAGE_COVER = "QzoneLimitPageCover";
    public static final int SET_SOURCE_PROFILECARD = 1;
    public static final int SET_SOURCE_QZONE = 0;
    public static final String STATUS_VIDEO_COVER_ALBUM_VIDEO_FAKE = "1002";
    public static final String STATUS_VIDEO_COVER_AVAIL = "2";
    public static final String STATUS_VIDEO_COVER_BANNED = "3";
    public static final String STATUS_VIDEO_COVER_FAKE = "1000";
    public static final String STATUS_VIDEO_COVER_HALF_FAKE = "1001";
    public static final String STATUS_VIDEO_COVER_HANDLING = "1";
    public static final String STATUS_VIDEO_COVER_UNSET = "0";
    public static final int SYNC_FLAG_BOTH = 1;
    public static final int WIFI_PHOTO_NUM = 8;
    public static final String qzone_video_select_qzone_album_video_too_long_alert = l.a(R.string.rpf);
    public static final String qzone_video_select_qzone_album_video_unknow_time_alert = l.a(R.string.rpj);
    public static final String qzone_video_uploading = l.a(R.string.rpi);
    public static final String qzone_video_cover_fail_unknow_videotype = l.a(R.string.rpk);
    public static final String qzone_video_cover_fail_unknow_videocoverurl = l.a(R.string.rph);
    public static final String qzone_video_cover_actionsheet_title = QzoneConfig.getInstance().getConfig(WnsConfig.MAIN_KEY_QZONE_TEXT_SETTING, "ActionSheetAddDiyVideo", "\u6dfb\u52a0\u81ea\u5b9a\u4e49\u89c6\u9891\u80cc\u666f");
    public static final String qzone_video_cover_actionsheet_qzone_more_video = QzoneConfig.getInstance().getConfig(WnsConfig.MAIN_KEY_QZONE_TEXT_SETTING, "ActionSheetMoreVideoBg", "\u66f4\u591a\u89c6\u9891\u80cc\u666f");
    public static final String qzone_video_cover_actionsheet_qzonealbumvideo = QzoneConfig.getInstance().getConfig(WnsConfig.MAIN_KEY_QZONE_TEXT_SETTING, "ActionSheetQzoneAlbum", "\u7a7a\u95f4\u76f8\u518c");
    public static final String qzone_video_cover_actionsheet_recordvideo = QzoneConfig.getInstance().getConfig(WnsConfig.MAIN_KEY_QZONE_TEXT_SETTING, "ActionSheetShortVideo", Constants.Business.QQCIRCLE);
    public static final String qzone_video_cover_actionsheet_cancel = l.a(R.string.j6l);
    public static final String qzone_video_cover_bad_devices_alert_tips = l.a(R.string.rpm);
    public static final String qzone_video_cover_not_support_trim_alert_tips = l.a(R.string.rpl);
    public static final String qzone_video_cover_fail_unknow_video_width_height_invalid = l.a(R.string.rpe);
    public static final String qzone_video_cover_open_vip_succ_tips = l.a(R.string.rpo);
    public static final String qzone_album_title_my_videolist = QzoneConfig.getInstance().getConfig(WnsConfig.MAIN_KEY_QZONE_TEXT_SETTING, "AlbumTitleMyVideo", "\u6211\u7684\u89c6\u9891");
    public static final String WEBVIEW_DEFAULT_ERROR_MSG = QzoneConfig.getInstance().getConfig(WnsConfig.MAIN_KEY_QZONE_TEXT_SETTING, "QzoneShowLoadError", "\u7cdf\u7cd5\uff0c\u7a7a\u95f4\u79c0\u52a0\u8f7d\u51fa\u9519\u4e86");

    /* compiled from: P */
    /* loaded from: classes39.dex */
    public static class CoverStringType {
        public static final String COVER_TYPE_CARTOON_COVER = "CartoonCover";
        public static final String COVER_TYPE_COCOS2D_COVER = "Cocos2DCover_v1";
        public static final String COVER_TYPE_CUSTOM = "CustomCover";
        public static final String COVER_TYPE_CUSTOM_DYNAMIC_ALBUM_COVER = "DynamicAlbumCover";
        public static final String COVER_TYPE_CUSTOM_GIF_COVER = "CustomGifCover";
        public static final String COVER_TYPE_DEFAULT = "default";
        public static final String COVER_TYPE_DYNAMIC_COVER = "DynamicCover";
        public static final String COVER_TYPE_FULL_SCREEN = "FullScreenCover";
        public static final String COVER_TYPE_GAME = "GameStaticCover";
        public static final String COVER_TYPE_MUSIC_COVER = "MusicCover";
        public static final String COVER_TYPE_NEW_VIDEO_COVER = "VideoCover";
        public static final String COVER_TYPE_PANORAMA_COVER = "PanoramaCover";
        public static final String COVER_TYPE_PHOTOWALL = "PhotoWallCover";
        public static final String COVER_TYPE_QZONE_SHOW_COVER = "QzoneShowCover";
        public static final String COVER_TYPE_STATIC = "StaticCover";
        public static final String COVER_TYPE_VIDEO_COVER = "CustomVideoCover";
        public static final String COVER_TYPE_WEATHER_COVER = "WeatherCover";
        public static final String COVER_TYPE_WEBVIEW_COVER_PREFIX = "Webview";
    }

    /* compiled from: P */
    /* loaded from: classes39.dex */
    public static class PhotoEnum {
        public static final int _PhotoSpecBig = 1;
        public static final int _PhotoSpecBigClip = 5;
        public static final int _PhotoSpecCurrent = 11;
        public static final int _PhotoSpecMedium = 2;
        public static final int _PhotoSpecMediumClip = 6;
        public static final int _PhotoSpecOrigin = 0;
        public static final int _PhotoSpecSmall = 3;
        public static final int _PhotoSpecSmallClip = 7;
        public static final int _PhotoSpecThumb = 4;
        public static final int _PhotoSpecVideoPlay = 12;
    }

    /* compiled from: P */
    /* loaded from: classes39.dex */
    public static class WebViewConst {
        public static final String KEY_WNS_PROXY_HTTP_DATA = "wns_proxy_http_data";
        public static final int MSG_WNS_HTTP_GET_DATA = 203;
        public static final String WEBVIEW_URL = "url";
    }
}
