package tencent.im.msg.hummer.resv;

import com.tencent.ad.tangram.statistics.AdReporterForEffect;
import com.tencent.biz.qqcircle.immersive.constants.QFSNumberConstants;
import com.tencent.biz.qqcircle.immersive.feed.event.QFSBottomDynamicGuideEvent;
import com.tencent.ecommerce.repo.consumer.resp.PlayUI;
import com.tencent.luggage.wxa.fe.a;
import com.tencent.luggage.wxa.ig.w;
import com.tencent.luggage.wxa.rf.g;
import com.tencent.luggage.wxa.v6.d;
import com.tencent.luggage.wxa.wh.b;
import com.tencent.mm.plugin.appbrand.jsapi.sensor.JsApiEnableDeviceOrientation;
import com.tencent.mobileqq.data.troop.TroopInfo;
import com.tencent.mobileqq.pb.ByteStringMicro;
import com.tencent.mobileqq.pb.MessageMicro;
import com.tencent.mobileqq.pb.PBBytesField;
import com.tencent.mobileqq.pb.PBField;
import com.tencent.mobileqq.pb.PBFloatField;
import com.tencent.mobileqq.pb.PBRepeatField;
import com.tencent.mobileqq.pb.PBRepeatMessageField;
import com.tencent.mobileqq.pb.PBUInt32Field;
import com.tencent.mobileqq.pb.PBUInt64Field;
import com.tencent.mobileqq.qzoneplayer.ui.common.PlayerResources;
import com.tencent.mobileqq.vas.config.business.qvip.QVipServiceAccountFolderProcessor;
import com.tencent.qqlive.tvkplayer.qqliveasset.player.message.TVKQQLiveAssetPlayerMsg;
import com.tencent.qqnt.kernel.nativeinterface.MsgConstant;
import com.tencent.tmassistantbase.common.TMAssistantDownloadErrorCode;
import com.tencent.view.FilterEnum;

/* compiled from: P */
/* loaded from: classes29.dex */
public final class generalflags$ResvAttr extends MessageMicro<generalflags$ResvAttr> {
    static final MessageMicro.FieldMap __fieldMap__;
    public generalflags$BotMetaData bot_meta_data;
    public final PBBytesField bytes_golden_msg_info;
    public final PBBytesField bytes_group_confess_sig;
    public final PBBytesField bytes_group_msg_busi_buf;
    public final PBBytesField bytes_hudong_mark;
    public final PBBytesField bytes_kpl_info;
    public final PBBytesField bytes_messsage_ext;
    public final PBBytesField bytes_oac_msg_extend;
    public final PBBytesField bytes_pass_through;
    public final PBBytesField bytes_pb_ptt_waveform;
    public final PBBytesField bytes_robot_general_trans;
    public final PBBytesField bytes_service_msg_name;
    public final PBBytesField bytes_shortVideoId;
    public final PBBytesField bytes_subscription_url;
    public final PBBytesField bytes_tag_name;
    public final PBBytesField bytes_upload_image_to_qzone_param;
    public final PBBytesField bytes_user_vip_info;
    public final PBBytesField bytes_wo_info;
    public final PBBytesField bytes_yuheng_task_msg_buf;
    public generalflags$MetaData game_meta_data;
    public generalflags$MsgIcon msg_icons;
    public generalflags$NTExt nt_ext;
    public generalflags$PassThrough pass_through;
    public final PBRepeatField<Integer> rpt_uint32_custom_featureid;
    public final PBBytesField trans_data;
    public final PBUInt32Field uint32_aio_sync_to_story_flag;
    public final PBUInt32Field uint32_auto_reply;
    public final PBUInt32Field uint32_bot_message_class_id;
    public final PBUInt32Field uint32_comment_flag;
    public final PBUInt32Field uint32_compound_msg_flag;
    public final PBUInt32Field uint32_device_type;
    public final PBUInt32Field uint32_diy_font_timestamp;
    public final PBUInt32Field uint32_face_id;
    public final PBUInt32Field uint32_gray_name_plate;
    public final PBUInt32Field uint32_group_info_flag_ex3;
    public final PBUInt32Field uint32_group_info_flag_ex4;
    public final PBUInt32Field uint32_group_member_flag_ex2;
    public final PBUInt32Field uint32_group_rich_flag;
    public final PBUInt32Field uint32_group_ringtone_id;
    public final PBUInt32Field uint32_group_savedb_flag;
    public final PBUInt32Field uint32_holiday_flag;
    public final PBUInt32Field uint32_important_msg_enum;
    public final PBUInt32Field uint32_important_msg_type;
    public final PBUInt32Field uint32_is_ice_break_msg;
    public final PBUInt32Field uint32_kings_honor_level;
    public final PBUInt32Field uint32_love_language_flag;
    public final PBUInt32Field uint32_msg_flag_type;
    public final PBUInt32Field uint32_msg_info_flag;
    public final PBUInt32Field uint32_nameplate;
    public final PBUInt32Field uint32_nameplate_vip_type;
    public final PBUInt32Field uint32_pendant_diy_id;
    public final PBUInt32Field uint32_red_envelope_type;
    public final PBUInt32Field uint32_req_font_effect_id;
    public final PBUInt32Field uint32_req_is_bigclub_hidden;
    public final PBUInt32Field uint32_rich_card_name_ver;
    public final PBUInt32Field uint32_service_msg_remind_type;
    public final PBUInt32Field uint32_service_msg_type;
    public final PBUInt32Field uint32_show_in_msg_list;
    public final PBUInt32Field uint32_timed_message;
    public final PBUInt32Field uint32_troop_pobing_template;
    public final PBUInt32Field uint32_unsafe_msg_flag;
    public final PBUInt32Field uint32_upload_image_to_qzone_flag;
    public final PBUInt32Field uint32_user_bigclub_flag;
    public final PBUInt32Field uint32_user_bigclub_level;
    public final PBUInt32Field uint32_vip_level;
    public final PBUInt32Field uint32_vip_type;
    public final PBUInt64Field uint64_comment_location;
    public final PBUInt64Field uint64_longmsg_flag;
    public final PBUInt64Field uint64_subfont_id;
    public final PBUInt32Field unit32_file_from_scene;
    public final PBUInt32Field uint32_global_group_level = PBField.initUInt32(0);
    public final PBUInt32Field uint32_nearby_charm_level = PBField.initUInt32(0);
    public final PBUInt64Field redbag_msg_sender_uin = PBField.initUInt64(0);
    public final PBUInt32Field uint32_title_id = PBField.initUInt32(0);
    public final PBUInt32Field uint32_robot_msg_flag = PBField.initUInt32(0);
    public final PBUInt64Field want_gift_sender_uin = PBField.initUInt64(0);
    public final PBFloatField float_sticker_x = PBField.initFloat(0.0f);
    public final PBFloatField float_sticker_y = PBField.initFloat(0.0f);
    public final PBFloatField float_sticker_width = PBField.initFloat(0.0f);
    public final PBFloatField float_sticker_height = PBField.initFloat(0.0f);
    public final PBUInt32Field uint32_sticker_rotate = PBField.initUInt32(0);
    public final PBUInt64Field uint64_sticker_host_msgseq = PBField.initUInt64(0);
    public final PBUInt64Field uint64_sticker_host_msguid = PBField.initUInt64(0);
    public final PBUInt64Field uint64_sticker_host_time = PBField.initUInt64(0);
    public final PBUInt32Field uint32_mobile_custom_font = PBField.initUInt32(0);
    public final PBUInt32Field uint32_tail_key = PBField.initUInt32(0);
    public final PBUInt32Field uint32_show_tail_flag = PBField.initUInt32(0);
    public final PBUInt32Field uint32_doutu_msg_type = PBField.initUInt32(0);
    public final PBUInt32Field uint32_doutu_combo = PBField.initUInt32(0);
    public final PBUInt32Field uint32_custom_featureid = PBField.initUInt32(0);
    public final PBUInt32Field uint32_golden_msg_type = PBField.initUInt32(0);

    static {
        Float valueOf = Float.valueOf(0.0f);
        ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
        __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16, 24, 32, 40, 48, 61, 69, 77, 85, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 178, 184, 194, 200, 208, 216, 234, 240, 248, 256, 266, 272, FilterEnum.MIC_PTU_TRANS_XINXIAN, 288, 296, 314, 322, AdReporterForEffect.ACTION_MOBILEAPP_QUICKAPP_OPEN_FAILURE, 336, a.CTRL_INDEX, g.CTRL_INDEX, 376, MsgConstant.KRMFILETHUMBSIZE384, QFSBottomDynamicGuideEvent.DYNAMIC_GUIDE_BUTTON_TYPE, 402, 408, 416, PlayUI.UIType.BIG_CARD_SHAPED_PIC, 432, 440, TroopInfo.PAY_PRIVILEGE_ALL, QFSNumberConstants.Int.NUM_456, 464, JsApiEnableDeviceOrientation.CTRL_INDEX, 482, 488, w.CTRL_INDEX, 506, 512, 522, 528, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_REFRESH_PLAYER_WITH_REOPEN_START, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_QUICK_PLAY_WITH_OFFLINE_RESOURCE, PlayerResources.ViewId.SWITCH_LANDSCAPE_BUTTON, PlayerResources.ViewId.GET_MORE_TOGGLE_AREA, PlayerResources.ViewId.EXTENDED_VIEW_BTN_NORMAL_BUTTON, PlayerResources.ViewId.CANVAS_VIDEO_TOTAL_TRAFFIC_TEXT, 586, d.CTRL_INDEX, 600, 608, 616, 626, 632, 640, 648, 658, 666, 674, 680, 690, 698, 704, 714, QVipServiceAccountFolderProcessor.CMD, TMAssistantDownloadErrorCode.DownloadSDKErrorCode_SPACE_NOT_ENOUGH, b.CTRL_INDEX, 744, 818, 16002}, new String[]{"uint32_global_group_level", "uint32_nearby_charm_level", "redbag_msg_sender_uin", "uint32_title_id", "uint32_robot_msg_flag", "want_gift_sender_uin", "float_sticker_x", "float_sticker_y", "float_sticker_width", "float_sticker_height", "uint32_sticker_rotate", "uint64_sticker_host_msgseq", "uint64_sticker_host_msguid", "uint64_sticker_host_time", "uint32_mobile_custom_font", "uint32_tail_key", "uint32_show_tail_flag", "uint32_doutu_msg_type", "uint32_doutu_combo", "uint32_custom_featureid", "uint32_golden_msg_type", "bytes_golden_msg_info", "uint32_bot_message_class_id", "bytes_subscription_url", "uint32_pendant_diy_id", "uint32_timed_message", "uint32_holiday_flag", "bytes_kpl_info", "uint32_face_id", "uint32_diy_font_timestamp", "uint32_red_envelope_type", "bytes_shortVideoId", "uint32_req_font_effect_id", "uint32_love_language_flag", "uint32_aio_sync_to_story_flag", "uint32_upload_image_to_qzone_flag", "bytes_upload_image_to_qzone_param", "bytes_group_confess_sig", "uint64_subfont_id", "uint32_msg_flag_type", "rpt_uint32_custom_featureid", "uint32_rich_card_name_ver", "uint32_msg_info_flag", "uint32_service_msg_type", "uint32_service_msg_remind_type", "bytes_service_msg_name", "uint32_vip_type", "uint32_vip_level", "bytes_pb_ptt_waveform", "uint32_user_bigclub_level", "uint32_user_bigclub_flag", "uint32_nameplate", "uint32_auto_reply", "uint32_req_is_bigclub_hidden", "uint32_show_in_msg_list", "bytes_oac_msg_extend", "uint32_group_member_flag_ex2", "uint32_group_ringtone_id", "bytes_robot_general_trans", "uint32_troop_pobing_template", "bytes_hudong_mark", "uint32_group_info_flag_ex3", "uint32_comment_flag", "uint64_comment_location", "bytes_pass_through", "uint32_group_savedb_flag", "uint32_nameplate_vip_type", "uint32_gray_name_plate", "bytes_user_vip_info", "uint32_important_msg_type", "uint32_important_msg_enum", "uint32_device_type", "uint32_unsafe_msg_flag", "bytes_group_msg_busi_buf", "uint32_group_info_flag_ex4", "uint32_kings_honor_level", "uint32_group_rich_flag", "bytes_yuheng_task_msg_buf", "bytes_tag_name", "bytes_messsage_ext", "uint32_compound_msg_flag", "trans_data", "game_meta_data", "uint64_longmsg_flag", "bot_meta_data", "nt_ext", "bytes_wo_info", "unit32_file_from_scene", "uint32_is_ice_break_msg", "msg_icons", "pass_through"}, new Object[]{0, 0, 0L, 0, 0, 0L, valueOf, valueOf, valueOf, valueOf, 0, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, byteStringMicro, 0, byteStringMicro, 0, 0, 0, byteStringMicro, 0, 0, 0, byteStringMicro, 0, 0, 0, 0, byteStringMicro, byteStringMicro, 0L, 0, 0, 0, 0, 0, 0, byteStringMicro, 0, 0, byteStringMicro, 0, 0, 0, 0, 0, 0, byteStringMicro, 0, 0, byteStringMicro, 0, byteStringMicro, 0, 0, 0L, byteStringMicro, 0, 0, 0, byteStringMicro, 0, 0, 0, 0, byteStringMicro, 0, 0, 0, byteStringMicro, byteStringMicro, byteStringMicro, 0, byteStringMicro, null, 0L, null, null, byteStringMicro, 0, 0, null, null}, generalflags$ResvAttr.class);
    }

    /* JADX WARN: Type inference failed for: r0v2, types: [tencent.im.msg.hummer.resv.generalflags$MsgIcon] */
    /* JADX WARN: Type inference failed for: r1v5, types: [tencent.im.msg.hummer.resv.generalflags$NTExt] */
    public generalflags$ResvAttr() {
        ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
        this.bytes_golden_msg_info = PBField.initBytes(byteStringMicro);
        this.uint32_bot_message_class_id = PBField.initUInt32(0);
        this.bytes_subscription_url = PBField.initBytes(byteStringMicro);
        this.uint32_pendant_diy_id = PBField.initUInt32(0);
        this.uint32_timed_message = PBField.initUInt32(0);
        this.uint32_holiday_flag = PBField.initUInt32(0);
        this.bytes_kpl_info = PBField.initBytes(byteStringMicro);
        this.uint32_face_id = PBField.initUInt32(0);
        this.uint32_diy_font_timestamp = PBField.initUInt32(0);
        this.uint32_red_envelope_type = PBField.initUInt32(0);
        this.bytes_shortVideoId = PBField.initBytes(byteStringMicro);
        this.uint32_req_font_effect_id = PBField.initUInt32(0);
        this.uint32_love_language_flag = PBField.initUInt32(0);
        this.uint32_aio_sync_to_story_flag = PBField.initUInt32(0);
        this.uint32_upload_image_to_qzone_flag = PBField.initUInt32(0);
        this.bytes_upload_image_to_qzone_param = PBField.initBytes(byteStringMicro);
        this.bytes_group_confess_sig = PBField.initBytes(byteStringMicro);
        this.uint64_subfont_id = PBField.initUInt64(0L);
        this.uint32_msg_flag_type = PBField.initUInt32(0);
        this.rpt_uint32_custom_featureid = PBField.initRepeat(PBUInt32Field.__repeatHelper__);
        this.uint32_rich_card_name_ver = PBField.initUInt32(0);
        this.uint32_msg_info_flag = PBField.initUInt32(0);
        this.uint32_service_msg_type = PBField.initUInt32(0);
        this.uint32_service_msg_remind_type = PBField.initUInt32(0);
        this.bytes_service_msg_name = PBField.initBytes(byteStringMicro);
        this.uint32_vip_type = PBField.initUInt32(0);
        this.uint32_vip_level = PBField.initUInt32(0);
        this.bytes_pb_ptt_waveform = PBField.initBytes(byteStringMicro);
        this.uint32_user_bigclub_level = PBField.initUInt32(0);
        this.uint32_user_bigclub_flag = PBField.initUInt32(0);
        this.uint32_nameplate = PBField.initUInt32(0);
        this.uint32_auto_reply = PBField.initUInt32(0);
        this.uint32_req_is_bigclub_hidden = PBField.initUInt32(0);
        this.uint32_show_in_msg_list = PBField.initUInt32(0);
        this.bytes_oac_msg_extend = PBField.initBytes(byteStringMicro);
        this.uint32_group_member_flag_ex2 = PBField.initUInt32(0);
        this.uint32_group_ringtone_id = PBField.initUInt32(0);
        this.bytes_robot_general_trans = PBField.initBytes(byteStringMicro);
        this.uint32_troop_pobing_template = PBField.initUInt32(0);
        this.bytes_hudong_mark = PBField.initBytes(byteStringMicro);
        this.uint32_group_info_flag_ex3 = PBField.initUInt32(0);
        this.uint32_comment_flag = PBField.initUInt32(0);
        this.uint64_comment_location = PBField.initUInt64(0L);
        this.bytes_pass_through = PBField.initBytes(byteStringMicro);
        this.uint32_group_savedb_flag = PBField.initUInt32(0);
        this.uint32_nameplate_vip_type = PBField.initUInt32(0);
        this.uint32_gray_name_plate = PBField.initUInt32(0);
        this.bytes_user_vip_info = PBField.initBytes(byteStringMicro);
        this.uint32_important_msg_type = PBField.initUInt32(0);
        this.uint32_important_msg_enum = PBField.initUInt32(0);
        this.uint32_device_type = PBField.initUInt32(0);
        this.uint32_unsafe_msg_flag = PBField.initUInt32(0);
        this.bytes_group_msg_busi_buf = PBField.initBytes(byteStringMicro);
        this.uint32_group_info_flag_ex4 = PBField.initUInt32(0);
        this.uint32_kings_honor_level = PBField.initUInt32(0);
        this.uint32_group_rich_flag = PBField.initUInt32(0);
        this.bytes_yuheng_task_msg_buf = PBField.initBytes(byteStringMicro);
        this.bytes_tag_name = PBField.initBytes(byteStringMicro);
        this.bytes_messsage_ext = PBField.initBytes(byteStringMicro);
        this.uint32_compound_msg_flag = PBField.initUInt32(0);
        this.trans_data = PBField.initBytes(byteStringMicro);
        this.game_meta_data = new generalflags$MetaData();
        this.uint64_longmsg_flag = PBField.initUInt64(0L);
        this.bot_meta_data = new generalflags$BotMetaData();
        this.nt_ext = new MessageMicro<generalflags$NTExt>() { // from class: tencent.im.msg.hummer.resv.generalflags$NTExt
            static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8}, new String[]{"c2c_msg_seq"}, new Object[]{0L}, generalflags$NTExt.class);
            public final PBUInt64Field c2c_msg_seq = PBField.initUInt64(0);
        };
        this.bytes_wo_info = PBField.initBytes(byteStringMicro);
        this.unit32_file_from_scene = PBField.initUInt32(0);
        this.uint32_is_ice_break_msg = PBField.initUInt32(0);
        this.msg_icons = new MessageMicro<generalflags$MsgIcon>() { // from class: tencent.im.msg.hummer.resv.generalflags$MsgIcon
            static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{10}, new String[]{"personal_icon_info"}, new Object[]{null}, generalflags$MsgIcon.class);
            public final PBRepeatMessageField<generalflags$IconInfo> personal_icon_info = PBField.initRepeatMessage(generalflags$IconInfo.class);
        };
        this.pass_through = new generalflags$PassThrough();
    }
}
