package com.tencent.mobileqq.msf.sdk;

import com.tencent.mobileqq.qfix.redirect.IPatchRedirector;
import com.tencent.mobileqq.qfix.redirect.PatchRedirectCenter;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* compiled from: P */
/* loaded from: classes15.dex */
public final class MsfCommand {
    private static final /* synthetic */ MsfCommand[] $VALUES;
    static IPatchRedirector $redirector_;
    public static final MsfCommand SEND_WIRELESS_MEIBAOREQ;
    public static final MsfCommand SEND_WIRELESS_PSWREQ;
    public static final MsfCommand _msf_HeartbeatAlive;
    public static final MsfCommand _msf_NetException;
    public static final MsfCommand _msf_QualityTest;
    public static final MsfCommand _msf_QuickHeartBeat;
    public static final MsfCommand _msf_RegPush;
    public static final MsfCommand _msf_UnRegPush;
    public static final MsfCommand _msf_getConfig;
    public static final MsfCommand _msf_hello;
    public static final MsfCommand _msf_kickedAndCleanTokenResp;
    public static final MsfCommand _msf_queryPush;
    public static final MsfCommand _msf_refreToken;
    public static final MsfCommand _setMsfResunmed;
    public static final MsfCommand _setMsfSuspend;
    public static final MsfCommand accountTokenSyncCheckSign;
    public static final MsfCommand appDataIncerment;
    public static final MsfCommand appReportLog;
    public static final MsfCommand changeToken;
    public static final MsfCommand changeUinLogin;
    public static final MsfCommand checkRole;
    public static final MsfCommand check_msf_conErro;
    public static final MsfCommand delLoginedAccount;
    public static final MsfCommand getAlterTickets;
    public static final MsfCommand getAppDataCount;
    public static final MsfCommand getGatewayIp;
    public static final MsfCommand getKey;
    public static final MsfCommand getMsfDebugInfo;
    public static final MsfCommand getPluginConfig;
    public static final MsfCommand getServerConfig;
    public static final MsfCommand getServerTime;
    public static final MsfCommand gm_GuardEvent;
    public static final MsfCommand keepProcessAlive;
    public static final MsfCommand loginAuth;
    public static final MsfCommand loginByWx;
    public static final MsfCommand msfCoreState;
    public static final MsfCommand msfGetWeakNet;
    public static final MsfCommand msfUpdateManagerConfig;
    public static final MsfCommand msfUpdateToggle;
    public static final MsfCommand msf_FEKit;
    public static final MsfCommand msf_active_log_report;
    public static final MsfCommand msf_after_fetch_config_log_report;
    public static final MsfCommand msf_before_msg_sync_config;
    public static final MsfCommand msf_listen_msg_sync_end;
    public static final MsfCommand msf_listen_online_register;
    public static final MsfCommand msf_manual_set_log_level;
    public static final MsfCommand msf_msgsignal;
    public static final MsfCommand msf_new_log_report_color;
    public static final MsfCommand msf_oshello;
    public static final MsfCommand msf_pbSyncMsg;
    public static final MsfCommand msf_push_register_switch;
    public static final MsfCommand msf_refreshDA2;
    public static final MsfCommand msf_save_geoginfo;
    public static final MsfCommand msf_sec_dispatch_event;
    public static final MsfCommand msf_sec_dispatch_to_app_event;
    public static final MsfCommand msf_send_wtpkg;
    public static final MsfCommand msf_ssoping;
    public static final MsfCommand msf_step_counter;
    public static final MsfCommand msf_test_close_conn;
    public static final MsfCommand msf_update_battery;
    public static final MsfCommand msf_update_common_config;
    public static final MsfCommand msf_update_complex_connect_config;
    public static final MsfCommand msf_update_locale_id;
    public static final MsfCommand msf_update_mmkv_config;
    public static final MsfCommand msf_update_weakNet_config;
    public static final MsfCommand msf_weak_net_switch;
    public static final MsfCommand nt_login_inject_sig;
    public static final MsfCommand onConnClosed;
    public static final MsfCommand onConnOpened;
    public static final MsfCommand onConnWeakNet;
    public static final MsfCommand onConnWeakNetNew;
    public static final MsfCommand onGrayCheckFailed;
    public static final MsfCommand onInvalidSign;
    public static final MsfCommand onNetNeedSignon;
    public static final MsfCommand onOepnConnAllFailed;
    public static final MsfCommand onOnlineStatusChanged;
    public static final MsfCommand onOverloadPushNotify;
    public static final MsfCommand onPCActive;
    public static final MsfCommand onProxyIpChanged;
    public static final MsfCommand onReceFirstResp;
    public static final MsfCommand onRecvConfigPush;
    public static final MsfCommand onRecvNotifyMsg;
    public static final MsfCommand onRecvPushMsg;
    public static final MsfCommand onRecvVerifyCode;
    public static final MsfCommand onStartConnect;
    public static final MsfCommand onTicketChanged;
    public static final MsfCommand onTokenExpired;
    public static final MsfCommand openConn;
    public static final MsfCommand openPCActive;
    public static final MsfCommand proxyRegisterPush;
    public static final MsfCommand proxyUnRegisterPush;
    public static final MsfCommand pushSetConfig;
    public static final MsfCommand qqwifi_notifyAvail;
    public static final MsfCommand quick_register_checkAccount;
    public static final MsfCommand quick_register_getAccount;
    public static final MsfCommand reNotifyConnOpened;
    public static final MsfCommand refreVerifyCode;
    public static final MsfCommand refreshTickets;
    public static final MsfCommand regUin_commitMobile;
    public static final MsfCommand regUin_commitMobileWatch;
    public static final MsfCommand regUin_commitPass;
    public static final MsfCommand regUin_commitPassWatch;
    public static final MsfCommand regUin_commitSmsCode;
    public static final MsfCommand regUin_commitSmsCodeWatch;
    public static final MsfCommand regUin_queryMobile;
    public static final MsfCommand regUin_queryMobileWatch;
    public static final MsfCommand regUin_querySmsStat;
    public static final MsfCommand regUin_querySmsStatWatch;
    public static final MsfCommand regUin_reSendSms;
    public static final MsfCommand regUin_reSendSmsWatch;
    public static final MsfCommand registerCmdCallback;
    public static final MsfCommand registerMsfService;
    public static final MsfCommand registerPush;
    public static final MsfCommand reportMsg;
    public static final MsfCommand reportRdm;
    public static final MsfCommand reportSocket;
    public static final MsfCommand resetCmdCallback;
    public static final MsfCommand sendVideoAck;
    public static final MsfCommand setMsfConnStatus;
    public static final MsfCommand startPCActivePolling;
    public static final MsfCommand stopPCActivePolling;
    public static final MsfCommand submitPuzzleVerifyCodeTicket;
    public static final MsfCommand submitVerifyCode;
    public static final MsfCommand unRegisterMsfService;
    public static final MsfCommand unRegisterPush;
    public static final MsfCommand unknown;
    public static final MsfCommand verifyPasswd;
    public static final MsfCommand verifyPasswdImage;
    public static final MsfCommand verifyPasswdRefreshImage;
    public static final MsfCommand wt_AskDevLockSms;
    public static final MsfCommand wt_CancelCode;
    public static final MsfCommand wt_CheckDevLockSms;
    public static final MsfCommand wt_CheckDevLockStatus;
    public static final MsfCommand wt_CheckPictureAndGetSt;
    public static final MsfCommand wt_CheckSMSAndGetSt;
    public static final MsfCommand wt_CheckSMSAndGetStExt;
    public static final MsfCommand wt_CheckSMSVerifyLoginAccount;
    public static final MsfCommand wt_CloseCode;
    public static final MsfCommand wt_CloseDevLock;
    public static final MsfCommand wt_FetchCodeSigVerifyLogin;
    public static final MsfCommand wt_GetA1WithA1;
    public static final MsfCommand wt_GetOpenKeyWithoutPasswd;
    public static final MsfCommand wt_GetSaltUinList;
    public static final MsfCommand wt_GetStViaGatewayLogin;
    public static final MsfCommand wt_GetStViaPhonePwdLogin;
    public static final MsfCommand wt_GetStViaSMSVerifyLogin;
    public static final MsfCommand wt_GetStWithPasswd;
    public static final MsfCommand wt_GetStWithoutPasswd;
    public static final MsfCommand wt_QueryCodeResult;
    public static final MsfCommand wt_QuickLoginByGateway;
    public static final MsfCommand wt_RefreshPictureData;
    public static final MsfCommand wt_RefreshSMSData;
    public static final MsfCommand wt_RefreshSMSVerifyLoginCode;
    public static final MsfCommand wt_RegGetSMSVerifyLoginAccount;
    public static final MsfCommand wt_SetDevlockMobileType;
    public static final MsfCommand wt_VerifyCode;
    public static final MsfCommand wt_VerifySMSVerifyLoginCode;
    public static final MsfCommand wt_exchange;
    public static final MsfCommand wt_getStViaWxLogin;
    public static final MsfCommand wt_getStWithQrSig;
    public static final MsfCommand wt_getUIDWithoutPasswd;
    public static final MsfCommand wt_loginAuth;
    public static final MsfCommand wt_name2uin;
    public static final MsfCommand wt_other;
    public static final MsfCommand wt_refreshMemorySig;
    public static final MsfCommand wt_setRegDevLockFlag;
    public static final MsfCommand wt_sig_checker_when_online;

    static {
        IPatchRedirector redirector = PatchRedirectCenter.getRedirector(18032);
        $redirector_ = redirector;
        if (redirector != null && redirector.hasPatch((short) 2)) {
            redirector.redirect((short) 2);
            return;
        }
        MsfCommand msfCommand = new MsfCommand("unknown", 0);
        unknown = msfCommand;
        MsfCommand msfCommand2 = new MsfCommand("registerMsfService", 1);
        registerMsfService = msfCommand2;
        MsfCommand msfCommand3 = new MsfCommand("unRegisterMsfService", 2);
        unRegisterMsfService = msfCommand3;
        MsfCommand msfCommand4 = new MsfCommand("loginAuth", 3);
        loginAuth = msfCommand4;
        MsfCommand msfCommand5 = new MsfCommand("verifyPasswd", 4);
        verifyPasswd = msfCommand5;
        MsfCommand msfCommand6 = new MsfCommand("verifyPasswdImage", 5);
        verifyPasswdImage = msfCommand6;
        MsfCommand msfCommand7 = new MsfCommand("verifyPasswdRefreshImage", 6);
        verifyPasswdRefreshImage = msfCommand7;
        MsfCommand msfCommand8 = new MsfCommand("changeUinLogin", 7);
        changeUinLogin = msfCommand8;
        MsfCommand msfCommand9 = new MsfCommand("delLoginedAccount", 8);
        delLoginedAccount = msfCommand9;
        MsfCommand msfCommand10 = new MsfCommand("submitVerifyCode", 9);
        submitVerifyCode = msfCommand10;
        MsfCommand msfCommand11 = new MsfCommand("refreVerifyCode", 10);
        refreVerifyCode = msfCommand11;
        MsfCommand msfCommand12 = new MsfCommand("refreshTickets", 11);
        refreshTickets = msfCommand12;
        MsfCommand msfCommand13 = new MsfCommand("getServerTime", 12);
        getServerTime = msfCommand13;
        MsfCommand msfCommand14 = new MsfCommand("registerPush", 13);
        registerPush = msfCommand14;
        MsfCommand msfCommand15 = new MsfCommand("unRegisterPush", 14);
        unRegisterPush = msfCommand15;
        MsfCommand msfCommand16 = new MsfCommand("registerCmdCallback", 15);
        registerCmdCallback = msfCommand16;
        MsfCommand msfCommand17 = new MsfCommand("resetCmdCallback", 16);
        resetCmdCallback = msfCommand17;
        MsfCommand msfCommand18 = new MsfCommand("reportMsg", 17);
        reportMsg = msfCommand18;
        MsfCommand msfCommand19 = new MsfCommand("getServerConfig", 18);
        getServerConfig = msfCommand19;
        MsfCommand msfCommand20 = new MsfCommand("onStartConnect", 19);
        onStartConnect = msfCommand20;
        MsfCommand msfCommand21 = new MsfCommand("onConnOpened", 20);
        onConnOpened = msfCommand21;
        MsfCommand msfCommand22 = new MsfCommand("reNotifyConnOpened", 21);
        reNotifyConnOpened = msfCommand22;
        MsfCommand msfCommand23 = new MsfCommand("onReceFirstResp", 22);
        onReceFirstResp = msfCommand23;
        MsfCommand msfCommand24 = new MsfCommand("onOepnConnAllFailed", 23);
        onOepnConnAllFailed = msfCommand24;
        MsfCommand msfCommand25 = new MsfCommand("onConnClosed", 24);
        onConnClosed = msfCommand25;
        MsfCommand msfCommand26 = new MsfCommand("onConnWeakNet", 25);
        onConnWeakNet = msfCommand26;
        MsfCommand msfCommand27 = new MsfCommand("onConnWeakNetNew", 26);
        onConnWeakNetNew = msfCommand27;
        MsfCommand msfCommand28 = new MsfCommand("onNetNeedSignon", 27);
        onNetNeedSignon = msfCommand28;
        MsfCommand msfCommand29 = new MsfCommand("onInvalidSign", 28);
        onInvalidSign = msfCommand29;
        MsfCommand msfCommand30 = new MsfCommand("onTokenExpired", 29);
        onTokenExpired = msfCommand30;
        MsfCommand msfCommand31 = new MsfCommand("onTicketChanged", 30);
        onTicketChanged = msfCommand31;
        MsfCommand msfCommand32 = new MsfCommand("onProxyIpChanged", 31);
        onProxyIpChanged = msfCommand32;
        MsfCommand msfCommand33 = new MsfCommand("onOverloadPushNotify", 32);
        onOverloadPushNotify = msfCommand33;
        MsfCommand msfCommand34 = new MsfCommand("onPCActive", 33);
        onPCActive = msfCommand34;
        MsfCommand msfCommand35 = new MsfCommand("onGrayCheckFailed", 34);
        onGrayCheckFailed = msfCommand35;
        MsfCommand msfCommand36 = new MsfCommand("onRecvConfigPush", 35);
        onRecvConfigPush = msfCommand36;
        MsfCommand msfCommand37 = new MsfCommand("onRecvVerifyCode", 36);
        onRecvVerifyCode = msfCommand37;
        MsfCommand msfCommand38 = new MsfCommand("onRecvPushMsg", 37);
        onRecvPushMsg = msfCommand38;
        MsfCommand msfCommand39 = new MsfCommand("onRecvNotifyMsg", 38);
        onRecvNotifyMsg = msfCommand39;
        MsfCommand msfCommand40 = new MsfCommand("onOnlineStatusChanged", 39);
        onOnlineStatusChanged = msfCommand40;
        MsfCommand msfCommand41 = new MsfCommand("_msf_RegPush", 40);
        _msf_RegPush = msfCommand41;
        MsfCommand msfCommand42 = new MsfCommand("_msf_UnRegPush", 41);
        _msf_UnRegPush = msfCommand42;
        MsfCommand msfCommand43 = new MsfCommand("_msf_queryPush", 42);
        _msf_queryPush = msfCommand43;
        MsfCommand msfCommand44 = new MsfCommand("_msf_hello", 43);
        _msf_hello = msfCommand44;
        MsfCommand msfCommand45 = new MsfCommand("_msf_refreToken", 44);
        _msf_refreToken = msfCommand45;
        MsfCommand msfCommand46 = new MsfCommand("_msf_kickedAndCleanTokenResp", 45);
        _msf_kickedAndCleanTokenResp = msfCommand46;
        MsfCommand msfCommand47 = new MsfCommand("_msf_getConfig", 46);
        _msf_getConfig = msfCommand47;
        MsfCommand msfCommand48 = new MsfCommand("_msf_HeartbeatAlive", 47);
        _msf_HeartbeatAlive = msfCommand48;
        MsfCommand msfCommand49 = new MsfCommand("_msf_NetException", 48);
        _msf_NetException = msfCommand49;
        MsfCommand msfCommand50 = new MsfCommand("SEND_WIRELESS_PSWREQ", 49);
        SEND_WIRELESS_PSWREQ = msfCommand50;
        MsfCommand msfCommand51 = new MsfCommand("SEND_WIRELESS_MEIBAOREQ", 50);
        SEND_WIRELESS_MEIBAOREQ = msfCommand51;
        MsfCommand msfCommand52 = new MsfCommand("_setMsfSuspend", 51);
        _setMsfSuspend = msfCommand52;
        MsfCommand msfCommand53 = new MsfCommand("_setMsfResunmed", 52);
        _setMsfResunmed = msfCommand53;
        MsfCommand msfCommand54 = new MsfCommand("msfGetWeakNet", 53);
        msfGetWeakNet = msfCommand54;
        MsfCommand msfCommand55 = new MsfCommand("msfCoreState", 54);
        msfCoreState = msfCommand55;
        MsfCommand msfCommand56 = new MsfCommand("getPluginConfig", 55);
        getPluginConfig = msfCommand56;
        MsfCommand msfCommand57 = new MsfCommand("regUin_queryMobile", 56);
        regUin_queryMobile = msfCommand57;
        MsfCommand msfCommand58 = new MsfCommand("regUin_commitMobile", 57);
        regUin_commitMobile = msfCommand58;
        MsfCommand msfCommand59 = new MsfCommand("regUin_querySmsStat", 58);
        regUin_querySmsStat = msfCommand59;
        MsfCommand msfCommand60 = new MsfCommand("regUin_reSendSms", 59);
        regUin_reSendSms = msfCommand60;
        MsfCommand msfCommand61 = new MsfCommand("regUin_commitSmsCode", 60);
        regUin_commitSmsCode = msfCommand61;
        MsfCommand msfCommand62 = new MsfCommand("regUin_commitPass", 61);
        regUin_commitPass = msfCommand62;
        MsfCommand msfCommand63 = new MsfCommand("regUin_queryMobileWatch", 62);
        regUin_queryMobileWatch = msfCommand63;
        MsfCommand msfCommand64 = new MsfCommand("regUin_commitMobileWatch", 63);
        regUin_commitMobileWatch = msfCommand64;
        MsfCommand msfCommand65 = new MsfCommand("regUin_querySmsStatWatch", 64);
        regUin_querySmsStatWatch = msfCommand65;
        MsfCommand msfCommand66 = new MsfCommand("regUin_reSendSmsWatch", 65);
        regUin_reSendSmsWatch = msfCommand66;
        MsfCommand msfCommand67 = new MsfCommand("regUin_commitSmsCodeWatch", 66);
        regUin_commitSmsCodeWatch = msfCommand67;
        MsfCommand msfCommand68 = new MsfCommand("regUin_commitPassWatch", 67);
        regUin_commitPassWatch = msfCommand68;
        MsfCommand msfCommand69 = new MsfCommand("quick_register_checkAccount", 68);
        quick_register_checkAccount = msfCommand69;
        MsfCommand msfCommand70 = new MsfCommand("quick_register_getAccount", 69);
        quick_register_getAccount = msfCommand70;
        MsfCommand msfCommand71 = new MsfCommand("checkRole", 70);
        checkRole = msfCommand71;
        MsfCommand msfCommand72 = new MsfCommand(com.tencent.mobileqq.msf.core.auth.d.f247424j, 71);
        changeToken = msfCommand72;
        MsfCommand msfCommand73 = new MsfCommand("proxyRegisterPush", 72);
        proxyRegisterPush = msfCommand73;
        MsfCommand msfCommand74 = new MsfCommand("proxyUnRegisterPush", 73);
        proxyUnRegisterPush = msfCommand74;
        MsfCommand msfCommand75 = new MsfCommand("appDataIncerment", 74);
        appDataIncerment = msfCommand75;
        MsfCommand msfCommand76 = new MsfCommand("getAppDataCount", 75);
        getAppDataCount = msfCommand76;
        MsfCommand msfCommand77 = new MsfCommand("accountTokenSyncCheckSign", 76);
        accountTokenSyncCheckSign = msfCommand77;
        MsfCommand msfCommand78 = new MsfCommand("appReportLog", 77);
        appReportLog = msfCommand78;
        MsfCommand msfCommand79 = new MsfCommand("getMsfDebugInfo", 78);
        getMsfDebugInfo = msfCommand79;
        MsfCommand msfCommand80 = new MsfCommand("reportRdm", 79);
        reportRdm = msfCommand80;
        MsfCommand msfCommand81 = new MsfCommand("reportSocket", 80);
        reportSocket = msfCommand81;
        MsfCommand msfCommand82 = new MsfCommand("pushSetConfig", 81);
        pushSetConfig = msfCommand82;
        MsfCommand msfCommand83 = new MsfCommand("getKey", 82);
        getKey = msfCommand83;
        MsfCommand msfCommand84 = new MsfCommand("getAlterTickets", 83);
        getAlterTickets = msfCommand84;
        MsfCommand msfCommand85 = new MsfCommand("openConn", 84);
        openConn = msfCommand85;
        MsfCommand msfCommand86 = new MsfCommand("getGatewayIp", 85);
        getGatewayIp = msfCommand86;
        MsfCommand msfCommand87 = new MsfCommand("setMsfConnStatus", 86);
        setMsfConnStatus = msfCommand87;
        MsfCommand msfCommand88 = new MsfCommand("keepProcessAlive", 87);
        keepProcessAlive = msfCommand88;
        MsfCommand msfCommand89 = new MsfCommand("sendVideoAck", 88);
        sendVideoAck = msfCommand89;
        MsfCommand msfCommand90 = new MsfCommand("wt_loginAuth", 89);
        wt_loginAuth = msfCommand90;
        MsfCommand msfCommand91 = new MsfCommand("wt_exchange", 90);
        wt_exchange = msfCommand91;
        MsfCommand msfCommand92 = new MsfCommand("wt_name2uin", 91);
        wt_name2uin = msfCommand92;
        MsfCommand msfCommand93 = new MsfCommand("wt_other", 92);
        wt_other = msfCommand93;
        MsfCommand msfCommand94 = new MsfCommand("_msf_QualityTest", 93);
        _msf_QualityTest = msfCommand94;
        MsfCommand msfCommand95 = new MsfCommand("wt_GetStWithPasswd", 94);
        wt_GetStWithPasswd = msfCommand95;
        MsfCommand msfCommand96 = new MsfCommand("wt_GetStWithoutPasswd", 95);
        wt_GetStWithoutPasswd = msfCommand96;
        MsfCommand msfCommand97 = new MsfCommand("wt_CheckPictureAndGetSt", 96);
        wt_CheckPictureAndGetSt = msfCommand97;
        MsfCommand msfCommand98 = new MsfCommand("wt_RefreshPictureData", 97);
        wt_RefreshPictureData = msfCommand98;
        MsfCommand msfCommand99 = new MsfCommand("wt_VerifyCode", 98);
        wt_VerifyCode = msfCommand99;
        MsfCommand msfCommand100 = new MsfCommand("wt_CloseCode", 99);
        wt_CloseCode = msfCommand100;
        MsfCommand msfCommand101 = new MsfCommand("wt_CancelCode", 100);
        wt_CancelCode = msfCommand101;
        MsfCommand msfCommand102 = new MsfCommand("wt_GetA1WithA1", 101);
        wt_GetA1WithA1 = msfCommand102;
        MsfCommand msfCommand103 = new MsfCommand("wt_GetOpenKeyWithoutPasswd", 102);
        wt_GetOpenKeyWithoutPasswd = msfCommand103;
        MsfCommand msfCommand104 = new MsfCommand("wt_QuickLoginByGateway", 103);
        wt_QuickLoginByGateway = msfCommand104;
        MsfCommand msfCommand105 = new MsfCommand("wt_GetStViaGatewayLogin", 104);
        wt_GetStViaGatewayLogin = msfCommand105;
        MsfCommand msfCommand106 = new MsfCommand("wt_getUIDWithoutPasswd", 105);
        wt_getUIDWithoutPasswd = msfCommand106;
        MsfCommand msfCommand107 = new MsfCommand("wt_GetSaltUinList", 106);
        wt_GetSaltUinList = msfCommand107;
        MsfCommand msfCommand108 = new MsfCommand("wt_GetStViaPhonePwdLogin", 107);
        wt_GetStViaPhonePwdLogin = msfCommand108;
        MsfCommand msfCommand109 = new MsfCommand("wt_CheckDevLockStatus", 108);
        wt_CheckDevLockStatus = msfCommand109;
        MsfCommand msfCommand110 = new MsfCommand("wt_AskDevLockSms", 109);
        wt_AskDevLockSms = msfCommand110;
        MsfCommand msfCommand111 = new MsfCommand("wt_CheckDevLockSms", 110);
        wt_CheckDevLockSms = msfCommand111;
        MsfCommand msfCommand112 = new MsfCommand("wt_CloseDevLock", 111);
        wt_CloseDevLock = msfCommand112;
        MsfCommand msfCommand113 = new MsfCommand("wt_RefreshSMSData", 112);
        wt_RefreshSMSData = msfCommand113;
        MsfCommand msfCommand114 = new MsfCommand("wt_CheckSMSAndGetSt", 113);
        wt_CheckSMSAndGetSt = msfCommand114;
        MsfCommand msfCommand115 = new MsfCommand("wt_CheckSMSAndGetStExt", 114);
        wt_CheckSMSAndGetStExt = msfCommand115;
        MsfCommand msfCommand116 = new MsfCommand("wt_setRegDevLockFlag", 115);
        wt_setRegDevLockFlag = msfCommand116;
        MsfCommand msfCommand117 = new MsfCommand("wt_SetDevlockMobileType", 116);
        wt_SetDevlockMobileType = msfCommand117;
        MsfCommand msfCommand118 = new MsfCommand("wt_RegGetSMSVerifyLoginAccount", 117);
        wt_RegGetSMSVerifyLoginAccount = msfCommand118;
        MsfCommand msfCommand119 = new MsfCommand("wt_CheckSMSVerifyLoginAccount", 118);
        wt_CheckSMSVerifyLoginAccount = msfCommand119;
        MsfCommand msfCommand120 = new MsfCommand("wt_RefreshSMSVerifyLoginCode", 119);
        wt_RefreshSMSVerifyLoginCode = msfCommand120;
        MsfCommand msfCommand121 = new MsfCommand("wt_VerifySMSVerifyLoginCode", 120);
        wt_VerifySMSVerifyLoginCode = msfCommand121;
        MsfCommand msfCommand122 = new MsfCommand("wt_GetStViaSMSVerifyLogin", 121);
        wt_GetStViaSMSVerifyLogin = msfCommand122;
        MsfCommand msfCommand123 = new MsfCommand("wt_FetchCodeSigVerifyLogin", 122);
        wt_FetchCodeSigVerifyLogin = msfCommand123;
        MsfCommand msfCommand124 = new MsfCommand("wt_QueryCodeResult", 123);
        wt_QueryCodeResult = msfCommand124;
        MsfCommand msfCommand125 = new MsfCommand("wt_getStWithQrSig", 124);
        wt_getStWithQrSig = msfCommand125;
        MsfCommand msfCommand126 = new MsfCommand("loginByWx", 125);
        loginByWx = msfCommand126;
        MsfCommand msfCommand127 = new MsfCommand("wt_getStViaWxLogin", 126);
        wt_getStViaWxLogin = msfCommand127;
        MsfCommand msfCommand128 = new MsfCommand("gm_GuardEvent", 127);
        gm_GuardEvent = msfCommand128;
        MsfCommand msfCommand129 = new MsfCommand("qqwifi_notifyAvail", 128);
        qqwifi_notifyAvail = msfCommand129;
        MsfCommand msfCommand130 = new MsfCommand("submitPuzzleVerifyCodeTicket", 129);
        submitPuzzleVerifyCodeTicket = msfCommand130;
        MsfCommand msfCommand131 = new MsfCommand("startPCActivePolling", 130);
        startPCActivePolling = msfCommand131;
        MsfCommand msfCommand132 = new MsfCommand("stopPCActivePolling", 131);
        stopPCActivePolling = msfCommand132;
        MsfCommand msfCommand133 = new MsfCommand("openPCActive", 132);
        openPCActive = msfCommand133;
        MsfCommand msfCommand134 = new MsfCommand("_msf_QuickHeartBeat", 133);
        _msf_QuickHeartBeat = msfCommand134;
        MsfCommand msfCommand135 = new MsfCommand("msf_ssoping", 134);
        msf_ssoping = msfCommand135;
        MsfCommand msfCommand136 = new MsfCommand("msf_msgsignal", 135);
        msf_msgsignal = msfCommand136;
        MsfCommand msfCommand137 = new MsfCommand("check_msf_conErro", 136);
        check_msf_conErro = msfCommand137;
        MsfCommand msfCommand138 = new MsfCommand("msf_refreshDA2", 137);
        msf_refreshDA2 = msfCommand138;
        MsfCommand msfCommand139 = new MsfCommand("msf_oshello", 138);
        msf_oshello = msfCommand139;
        MsfCommand msfCommand140 = new MsfCommand("msf_step_counter", 139);
        msf_step_counter = msfCommand140;
        MsfCommand msfCommand141 = new MsfCommand("msf_pbSyncMsg", 140);
        msf_pbSyncMsg = msfCommand141;
        MsfCommand msfCommand142 = new MsfCommand("msf_send_wtpkg", 141);
        msf_send_wtpkg = msfCommand142;
        MsfCommand msfCommand143 = new MsfCommand("msf_save_geoginfo", 142);
        msf_save_geoginfo = msfCommand143;
        MsfCommand msfCommand144 = new MsfCommand("msf_manual_set_log_level", 143);
        msf_manual_set_log_level = msfCommand144;
        MsfCommand msfCommand145 = new MsfCommand("msf_update_battery", 144);
        msf_update_battery = msfCommand145;
        MsfCommand msfCommand146 = new MsfCommand("msf_update_locale_id", 145);
        msf_update_locale_id = msfCommand146;
        MsfCommand msfCommand147 = new MsfCommand("msfUpdateManagerConfig", 146);
        msfUpdateManagerConfig = msfCommand147;
        MsfCommand msfCommand148 = new MsfCommand("msfUpdateToggle", 147);
        msfUpdateToggle = msfCommand148;
        MsfCommand msfCommand149 = new MsfCommand("wt_refreshMemorySig", 148);
        wt_refreshMemorySig = msfCommand149;
        MsfCommand msfCommand150 = new MsfCommand("msf_FEKit", 149);
        msf_FEKit = msfCommand150;
        MsfCommand msfCommand151 = new MsfCommand("msf_sec_dispatch_event", 150);
        msf_sec_dispatch_event = msfCommand151;
        MsfCommand msfCommand152 = new MsfCommand("msf_sec_dispatch_to_app_event", 151);
        msf_sec_dispatch_to_app_event = msfCommand152;
        MsfCommand msfCommand153 = new MsfCommand("msf_active_log_report", 152);
        msf_active_log_report = msfCommand153;
        MsfCommand msfCommand154 = new MsfCommand("msf_after_fetch_config_log_report", 153);
        msf_after_fetch_config_log_report = msfCommand154;
        MsfCommand msfCommand155 = new MsfCommand("msf_new_log_report_color", 154);
        msf_new_log_report_color = msfCommand155;
        MsfCommand msfCommand156 = new MsfCommand("msf_update_weakNet_config", 155);
        msf_update_weakNet_config = msfCommand156;
        MsfCommand msfCommand157 = new MsfCommand("msf_update_common_config", 156);
        msf_update_common_config = msfCommand157;
        MsfCommand msfCommand158 = new MsfCommand("msf_push_register_switch", 157);
        msf_push_register_switch = msfCommand158;
        MsfCommand msfCommand159 = new MsfCommand("msf_weak_net_switch", 158);
        msf_weak_net_switch = msfCommand159;
        MsfCommand msfCommand160 = new MsfCommand("msf_update_complex_connect_config", 159);
        msf_update_complex_connect_config = msfCommand160;
        MsfCommand msfCommand161 = new MsfCommand("msf_update_mmkv_config", 160);
        msf_update_mmkv_config = msfCommand161;
        MsfCommand msfCommand162 = new MsfCommand("msf_listen_online_register", 161);
        msf_listen_online_register = msfCommand162;
        MsfCommand msfCommand163 = new MsfCommand("msf_listen_msg_sync_end", 162);
        msf_listen_msg_sync_end = msfCommand163;
        MsfCommand msfCommand164 = new MsfCommand("msf_before_msg_sync_config", 163);
        msf_before_msg_sync_config = msfCommand164;
        MsfCommand msfCommand165 = new MsfCommand("wt_sig_checker_when_online", 164);
        wt_sig_checker_when_online = msfCommand165;
        MsfCommand msfCommand166 = new MsfCommand("nt_login_inject_sig", 165);
        nt_login_inject_sig = msfCommand166;
        MsfCommand msfCommand167 = new MsfCommand("msf_test_close_conn", 166);
        msf_test_close_conn = msfCommand167;
        $VALUES = new MsfCommand[]{msfCommand, msfCommand2, msfCommand3, msfCommand4, msfCommand5, msfCommand6, msfCommand7, msfCommand8, msfCommand9, msfCommand10, msfCommand11, msfCommand12, msfCommand13, msfCommand14, msfCommand15, msfCommand16, msfCommand17, msfCommand18, msfCommand19, msfCommand20, msfCommand21, msfCommand22, msfCommand23, msfCommand24, msfCommand25, msfCommand26, msfCommand27, msfCommand28, msfCommand29, msfCommand30, msfCommand31, msfCommand32, msfCommand33, msfCommand34, msfCommand35, msfCommand36, msfCommand37, msfCommand38, msfCommand39, msfCommand40, msfCommand41, msfCommand42, msfCommand43, msfCommand44, msfCommand45, msfCommand46, msfCommand47, msfCommand48, msfCommand49, msfCommand50, msfCommand51, msfCommand52, msfCommand53, msfCommand54, msfCommand55, msfCommand56, msfCommand57, msfCommand58, msfCommand59, msfCommand60, msfCommand61, msfCommand62, msfCommand63, msfCommand64, msfCommand65, msfCommand66, msfCommand67, msfCommand68, msfCommand69, msfCommand70, msfCommand71, msfCommand72, msfCommand73, msfCommand74, msfCommand75, msfCommand76, msfCommand77, msfCommand78, msfCommand79, msfCommand80, msfCommand81, msfCommand82, msfCommand83, msfCommand84, msfCommand85, msfCommand86, msfCommand87, msfCommand88, msfCommand89, msfCommand90, msfCommand91, msfCommand92, msfCommand93, msfCommand94, msfCommand95, msfCommand96, msfCommand97, msfCommand98, msfCommand99, msfCommand100, msfCommand101, msfCommand102, msfCommand103, msfCommand104, msfCommand105, msfCommand106, msfCommand107, msfCommand108, msfCommand109, msfCommand110, msfCommand111, msfCommand112, msfCommand113, msfCommand114, msfCommand115, msfCommand116, msfCommand117, msfCommand118, msfCommand119, msfCommand120, msfCommand121, msfCommand122, msfCommand123, msfCommand124, msfCommand125, msfCommand126, msfCommand127, msfCommand128, msfCommand129, msfCommand130, msfCommand131, msfCommand132, msfCommand133, msfCommand134, msfCommand135, msfCommand136, msfCommand137, msfCommand138, msfCommand139, msfCommand140, msfCommand141, msfCommand142, msfCommand143, msfCommand144, msfCommand145, msfCommand146, msfCommand147, msfCommand148, msfCommand149, msfCommand150, msfCommand151, msfCommand152, msfCommand153, msfCommand154, msfCommand155, msfCommand156, msfCommand157, msfCommand158, msfCommand159, msfCommand160, msfCommand161, msfCommand162, msfCommand163, msfCommand164, msfCommand165, msfCommand166, msfCommand167};
    }

    MsfCommand(String str, int i3) {
        IPatchRedirector iPatchRedirector = $redirector_;
        if (iPatchRedirector != null && iPatchRedirector.hasPatch((short) 1)) {
            iPatchRedirector.redirect((short) 1, (Object) this, (Object) str, i3);
        }
    }

    public static MsfCommand valueOf(String str) {
        return (MsfCommand) Enum.valueOf(MsfCommand.class, str);
    }

    public static MsfCommand[] values() {
        return (MsfCommand[]) $VALUES.clone();
    }
}
