package com.tencent.luggage.wxa.ui;

/* compiled from: P */
/* loaded from: classes8.dex */
public enum b {
    CopyPath,
    BackToHome,
    splitScreen,
    ShareAppMsg,
    ShareToTimeLine,
    EnableDebug,
    ShowPkgInfo,
    EnablePerformancePanel,
    OpenGamePreload,
    Exit,
    StickInWeChat,
    SendToDesktop,
    ModifyCollection,
    AboutUs,
    AppId,
    DebugRestart,
    DumpPerformanceTrace,
    SendRed,
    ReceiveRed,
    GameCpuProfiler,
    GameHeapProfiler,
    GameForceGc,
    Minimize,
    Setting,
    Complaint,
    GrowthCare,
    DevTools,
    Restart,
    Fav,
    SendHandoff,
    CopyShortLink,
    SalesDriving,
    GameLive,
    TradeComplaint,
    CommentFeedBack,
    GameIntroduction,
    Translate,
    ChangeTranslateLanguage
}
