package com.qzone.reborn.feedx.itemview;

/* compiled from: P */
/* loaded from: classes37.dex */
public enum QZoneFeedType {
    UNIQUE_TYPE_UNKNOWN(0),
    UNIQUE_TYPE_SINGLE_VIDEO_FEED(1),
    UNIQUE_TYPE_MIX_VIDEO_PIC_FEED(2),
    UNIQUE_TYPE_TEXT_FEED(3),
    UNIQUE_TYPE_FORWARD_BLOG(4),
    UNIQUE_TYPE_LEFT_H5_SHARE_FEED(5),
    UNIQUE_TYPE_AD_FEED(6),
    UNIQUE_TYPE_THAT_YEAR_TODAY_FEED(7),
    UNIQUE_TYPE_PYMK_FEED(8),
    UNIQUE_TYPE_QQ_LIVE_FEED(9),
    UNIQUE_TYPE_FRIEND_LIKE_FEED(10),
    UNIQUE_TYPE_FRIEND_BIRTHDAY(11),
    UNIQUE_TYPE_NEW_GUIDE(12),
    UNIQUE_TYPE_READ_LINE(15),
    UNIQUE_TYPE_QCIRCLE_SHARE_FEED(16),
    UNIQUE_TYPE_APP_SHARE_FEED(17),
    UNIQUE_TYPE_BLOG(18),
    UNIQUE_TYPE_FORWARD_SINGLE_VIDEO_FEED(19),
    UNIQUE_TYPE_FORWARD_MIX_PIC_VIDEO_FEED(20),
    UNIQUE_TYPE_FORWARD_TEXT_FEED(21),
    UNIQUE_TYPE_FORWARD_HAND_BLOG_FEED(22),
    UNIQUE_TYPE_HAND_BLOG_FEED(23),
    UNIQUE_TYPE_INDIVIDUAL_DRESS_UP_FEED(24),
    UNIQUE_TYPE_REPRINTED_TEXT_BLOG_FEED(25),
    UNIQUE_TYPE_GAME_PIC_SHARE_FEED(26),
    UNIQUE_TYPE_QCIRCLE_FRIEND_LIKE(27),
    UNIQUE_TYPE_READ_LINE_LOAD_MORE_UP(28),
    UNIQUE_TYPE_FRIEND_PLAYING(29),
    UNIQUE_TYPE_FRIEND_ANNIVERSARY(30),
    UNIQUE_TYPE_PERMISSION_SETTING(31),
    UNIQUE_TYPE_MEMORY_SEAL(32),
    UNIQUE_TYPE_GUEST_MEMORY_SEAL(33),
    UNIQUE_TYPE_TIMELINE_EMPTY(34),
    UNIQUE_TYPE_FRD_HOT_VIDEO(35),
    UNIQUE_TYPE_FRIEND_PLAYING_BIG_CARD(36),
    UNIQUE_TYPE_FAVORITE_SHARE(37),
    UNIQUE_TYPE_QCIRCLE_SHARE_SINGLE_VIDEO_FEED(38),
    UNIQUE_TYPE_TIANSHU_SINGLE_PIC_WITH_BUTTON_TYPE(39),
    UNIQUE_TYPE_FRIEND_POSTING_CARD_TYPE(40),
    UNIQUE_TYPE_REEDIT(41),
    UNIQUE_TYPE_AD_PICTURE_FEED(1001),
    UNIQUE_TYPE_AD_VIDEO_FEED(1002),
    UNIQUE_TYPE_AD_CAROUSEL_CARD_FEED(1003),
    UNIQUE_TYPE_AD_MDPA_FEED(1004),
    UNIQUE_TYPE_AD_REWARD_FEED(1005),
    UNIQUE_TYPE_AD_TIANSHU_VIDEO_FEED(1006),
    UNIQUE_TYPE_AD_TIANSHU_PIC_FEED(1007),
    UNIQUE_TYPE_AD_SHAKE_VIDEO_FEED(1008),
    UNIQUE_TYPE_AD_SHAKE_PIC_FEED(1009),
    UNIQUE_TYPE_AD_SHAKE_CAIDAN_VIDEO_FEED(1010),
    UNIQUE_TYPE_AD_SHAKE_CAIDAN_PIC_FEED(1011),
    UNIQUE_TYPE_AD_GESTURE_STAGE_VIDEO_FEED(1012),
    UNIQUE_TYPE_AD_GESTURE_STAGE_PIC_FEED(1013),
    UNIQUE_TYPE_AD_SHAKE_SINGLE_PIC_FEED(1014),
    UNIQUE_TYPE_AD_SHAKE_MULTI_PIC_FEED(1015),
    UNIQUE_TYPE_HIDE(404);

    public int mViewType;

    QZoneFeedType(int i3) {
        this.mViewType = i3;
    }
}
