package com.tencent.qqnt.kernelgpro.nativeinterface;

/* loaded from: classes24.dex */
public enum GProGuildMemberSearchSourceId {
    DEFAULT,
    ALL_MEMBER,
    GUILD_ROLE_MEMBER,
    CHANNEL_ADMIN_MEMBER,
    CATEGORY_ADMIN_MEMBER,
    ADD_GUILD_ROLE_MEMBER,
    ADD_CHANNEL_ADMIN_MEMBER,
    ADD_CATEGORY_ADMIN_MEMBER,
    CHANNEL_VISIBLE_MEMBER,
    CHANNEL_VISIBLE_SETTING_MEMBER,
    ADD_CHANNEL_VISIBLE_SETTING_MEMBER,
    CHANNEL_SPEAK_SETTING_MEMBER,
    ADD_CHANNEL_SPEAK_SETTING_MEMBER,
    CHANNEL_LIVE_SETTING_MEMBER,
    ADD_CHANNEL_LIVE_SETTING_MEMBER,
    CHANNEL_ACTIVITY_SETTING_MEMBER,
    ADD_CHANNEL_ACTIVITY_SETTING_MEMBER,
    AV_CHANNEL_ONLINE_MEMBER,
    CHANNEL_AT_MEMBER,
    GUILD_SPEAK_RULE_UNRESTRICTED_MEMBER,
    ADD_GUILD_SPEAK_RULE_UNRESTRICTED_MEMBER,
    GUILD_GLOBAL_SPEAK_LIST,
    GUILD_GLOBAL_WITHOUT_SPEAK_LIST
}
