package com.tencent.qqnt.kernelgpro.nativeinterface;

/* loaded from: classes24.dex */
public final class GProBusiType {
    public static final int CHANNEL_DISCOVER_HOT_FEEDS = 53;
    public static final int CHANNEL_DISCOVER_MINE_FEEDS = 54;
    public static final int CHANNEL_OFFICIAL_ACCOUNT_DOUBLE_FEEDS = 82;
    public static final int CHANNEL_OFFICIAL_ACCOUNT_HOT_FEEDS = 55;
    public static final int CHANNEL_OFFICIAL_ACCOUNT_MINE_FEEDS = 56;
    public static final int CHANNEL_OWNER_INDEX_FEEDS = 69;
    public static final int CHANNEL_OWNER_PROFILE_HOT_FEEDS = 79;
    public static final int CHANNEL_OWNER_PROFILE_NEWEST_FEEDS = 80;
    public static final int CHANNEL_TAB_DOUBLE_FEEDS = 81;
    public static final int CREATOR_SHARE_ADV_QQ_LIVE = 25;
    public static final int CREATOR_SHARE_ADV_XWORLD = 21;
    public static final int GROUP_TOP_ADV = 57;
    public static final int MINI_APP_MINI_GAME = 11;
    public static final int OFFICIAL_ACCOUNT_ADV = 4;
    public static final int OFFICIAL_ACCOUNT_ADV_GAME = 8;
    public static final int OFFICIAL_ACCOUNT_ADV_SHOP = 9;
    public static final int OFFICIAL_ACCOUNT_ADV_VIP = 7;
    public static final int OFFICIAL_ACCOUNT_LAYER_MASK_ADV = 14;
    public static final int OFFICIAL_ACCOUNT_SPORT = 13;
    public static final int OFFICIAL_ACCOUNT_TIAN_QI = 10;
    public static final int PC_QQTAB_ADV = 18;
    public static final int PULLDOWN_RECENT_MINIAPP = 51;
    public static final int QIQIAOBAN_SDK = 15;
    public static final int QQ_BANNER = 70;
    public static final int QQ_CPS = 16;
    public static final int QQ_MINIGAME_DAILY_RECOMMEND_GAME = 71;
    public static final int QQ_MINIGAME_DAILY_RECOMMEND_VIDEO = 72;
    public static final int QQ_MINIGAME_DAILY_RECOMMEND_VIDEO_FLOW = 73;
    public static final int QQ_MINIGAME_OFFICIAL_ACCOUNT_GAME = 74;
    public static final int QQ_MINIGAME_OFFICIAL_ACCOUNT_VIDEO = 75;
    public static final int QQ_MINIGAME_OFFICIAL_ACCOUNT_VIDEO_FLOW = 76;
    public static final int QQ_SHOP_ACCOUNT_FIRST_PAGE = 77;
    public static final int QQ_SHOP_ACCOUNT_WATERFALL = 29;
    public static final int QQ_SHOP_ACCOUNT_WATERFALL_FIRST = 28;
    public static final int QQ_SPLASH_SCREEN = 59;
    public static final int QQ_WALLET_CPS = 17;
    public static final int QZONE_APP_SPLASH_SCREEN = 67;
    public static final int QZONE_FEEDS = 0;
    public static final int QZONE_GROUP_PHOTO_TAIL = 68;
    public static final int QZONE_PHOTO_TAIL = 2;
    public static final int QZONE_SIMILAR_ADV = 78;
    public static final int QZONE_THIRD_NONSTANDARD = 62;
    public static final int QZONE_VIDEO_LAYER = 1;
    public static final int REWARD_2023_SPRING_FESTIVAL = 30;
    public static final int REWARD_COMMON = 66;
    public static final int REWARD_GIFT_ADV = 6;
    public static final int REWARD_GROUPGIFT_ADV = 12;
    public static final int REWARD_NOVEL_CREATURE = 52;
    public static final int REWARD_PERSONAL_ADV = 5;
    public static final int REWARD_QQSPORT_ADV = 27;
    public static final int REWARD_QQWEATHER_ADV = 58;
    public static final int REWARD_QZONE_THIRD_ACTIVITY = 60;
    public static final int REWARD_SUPER_SHOW = 61;
    public static final int REWARD_SUPER_SHOW_AD_ACTIVITY = 63;
    public static final int REWARD_SUPER_SHOW_CREATIVE_VOUCHER = 65;
    public static final int REWARD_SUPER_SHOW_FREE_ITEM = 64;
    public static final int SHAISHAI_WATERFALL = 39;
    public static final int WEISEE_OFFICIAL_ACCOUNT = 3;
    public static final int WEISEE_OFFICIAL_ACCOUNT_WATERFALL = 24;
    public static final int X_WORLD_AIO_VIDEO_ADV = 46;
    public static final int X_WORLD_AI_POSTER = 34;
    public static final int X_WORLD_COMMENT_SHARE_ADV = 50;
    public static final int X_WORLD_CREATOR_ADV = 20;
    public static final int X_WORLD_EXPLORE = 37;
    public static final int X_WORLD_EXPLORE_WATERFALL = 38;
    public static final int X_WORLD_FULLSCREEN_PAUSE = 49;
    public static final int X_WORLD_GENERAL_ACTIVITY = 36;
    public static final int X_WORLD_LANDSCAPE_LAYER_ADV = 47;
    public static final int X_WORLD_OFFICIAL_ACCOUNT_ADV = 26;
    public static final int X_WORLD_PROFILE_LAYER_ADV = 48;
    public static final int X_WORLD_PURCHASE_AD_DEMO = 45;
    public static final int X_WORLD_QZONE_FRIEND_RECOMMEND = 40;
    public static final int X_WORLD_QZONE_LAYER = 22;
    public static final int X_WORLD_QZONE_OTHER_ENTRY = 44;
    public static final int X_WORLD_QZONE_PUBLISH_SYNC = 41;
    public static final int X_WORLD_QZONE_VIDEO_TAB = 42;
    public static final int X_WORLD_QZONE_VIDEO_UGC = 43;
    public static final int X_WORLD_SEARCH_ADV = 33;
    public static final int X_WORLD_SHOP = 31;
    public static final int X_WORLD_SUG_ADV = 35;
    public static final int X_WORLD_TOPVIEW_ADV = 23;
    public static final int X_WORLD_VIDEO_ADV = 19;
    public static final int X_WORLD_WATERFALL = 32;

    public String toString() {
        return "GProBusiType{}";
    }
}
