package com.tencent.biz.qqcircle.beans;

import com.tencent.biz.qcircleshadow.lib.variation.HostAppSettingUtil;
import com.tencent.mobileqq.multishare.action.c;
import com.tencent.mobileqq.selectmember.ResultRecord;
import cooperation.qqcircle.report.QCircleReportBean;
import e30.b;
import feedcloud.FeedCloudMeta$StComment;
import feedcloud.FeedCloudMeta$StFeed;
import feedcloud.FeedCloudMeta$StGPSV2;
import feedcloud.FeedCloudMeta$StReply;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Map;
import qqcircle.QQCircleBase$UserCircleInfo;

/* compiled from: P */
/* loaded from: classes4.dex */
public class QCircleShareInfo implements Serializable {
    public static final int TYPE_COMMENT_PIC_PREVIEW_PAGE = 10;
    public static final int TYPE_SHARE_ALBUM_POLYMERIZATION_PAGE = 7;
    public static final int TYPE_SHARE_COLLECT_BOX_PAGE = 9;
    public static final int TYPE_SHARE_COMMENT = 12;
    public static final int TYPE_SHARE_FEED = 0;
    public static final int TYPE_SHARE_HOT_EVENT_POLYMERIZATION_PAGE = 8;
    public static final int TYPE_SHARE_INVITE = 2;
    public static final int TYPE_SHARE_KUIKLY = 14;
    public static final int TYPE_SHARE_LBS_POLYMERIZATION_PAGE = 5;
    public static final int TYPE_SHARE_NEW_CONTENT_DETAIL = 15;
    public static final int TYPE_SHARE_PAT_SAME_POLYMERIZATION_PAGE = 6;
    public static final int TYPE_SHARE_REPLY = 13;
    public static final int TYPE_SHARE_SPRING_FESTIVAL_ACTIVITY_DIALOG = 11;
    public static final int TYPE_SHARE_TAG_PAGE = 3;
    public static final int TYPE_SHARE_TAG_POLYMERIZATION_PAGE = 4;
    public static final int TYPE_SHARE_USER = 1;
    private static final long serialVersionUID = -137590948041340056L;
    public QQCircleBase$UserCircleInfo circleInfo;
    public long collectBoxId;
    public FeedCloudMeta$StComment comment;
    public int contextHashCode;
    public String copyContent;
    public QCircleExtraTypeInfo extraTypeInfo;
    public FeedCloudMeta$StFeed feed;
    public b feedBlockData;
    public FeedCloudMeta$StGPSV2 gpsInfo;
    public boolean isCloseRecentShare;
    public boolean isLongClick;
    public boolean isNotAllowDownload;
    public boolean isShowBackgroundMusic;
    public boolean isShowCollect;
    public boolean isShowCopyContent;
    public boolean isShowCopyShortLink;
    public boolean isShowDebug;
    public boolean isShowDelete;
    public boolean isShowDeleteAndEditAlbum;
    public boolean isShowDeletePush;
    public boolean isShowDeletePushDisable;
    public boolean isShowDisLike;
    public boolean isShowDownLoad;
    public boolean isShowFeedBindQQGroup;
    public boolean isShowFeedback;
    public boolean isShowHideThisWork;
    public boolean isShowPersonalQrcode;
    public boolean isShowPersonalQrcodeDown;
    public boolean isShowPlayRate;
    public boolean isShowReport;
    public boolean isShowSetToPrivatePermission;
    public boolean isShowSetToPublicPermission;
    public boolean isShowStick;
    public boolean isShowUnCollect;
    public boolean isShowUnStick;
    public Map<String, Object> mDTReportExtMapOnSendSuccess;
    public QCircleReportBean mReportBean;
    public String mShareUin;
    public int mShareUinType;
    public String mainPageUserUin;
    public FeedCloudMeta$StReply reply;
    public String mShareTitle = "\u7ba1\u7406\u4f5c\u54c1";
    public int type = 0;
    public int picDownPos = 0;
    public String polymerizationName = "";
    public String tagId = "";
    public String tagName = "";
    public long albumId = 0;
    public int albumStatus = 0;
    public int source = 0;
    public String shareButtonType = "default";
    public int hadAdBanner = 0;
    public int shareStyleType = 0;
    public int silentShareType = -1;
    public String mDirectShowMsg = "";
    public String mShareUinName = "";
    public final ArrayList<ResultRecord> mMultiShareUsers = new ArrayList<>();
    public final ArrayList<c> mSelectedUserList = new ArrayList<>();
    public boolean mNeedShowShareDialog = true;
    public String customShareSuccessToast = "";
    public boolean isNeedShowShareSuccessToast = true;
    public String shareFrom = "";
    public boolean isEnableShareToMutual = false;
    public boolean isShowShareToFriend = false;
    public boolean isShowShareToQZone = false;
    public boolean isShowShareToWechat = false;
    public boolean isShowShareToWechatCircle = false;
    public boolean isShowShareToChannel = false;
    public boolean isShowQCircleEnterFloatingWindow = false;
    public boolean isShowBarrageSwitch = false;
    public boolean isShowCopySchemaLink = !HostAppSettingUtil.isPublicVersion();
    public boolean isShowSetQQProfileCover = false;
    public boolean isShowWatchLater = false;
    public boolean isShowCancelWatchLater = false;
    public boolean isShowPushRanComment = false;
    public boolean isShareBottomBarrageSwitch = false;
    public boolean isFromMultiSharePanel = false;
    public String materialType = null;
    public String materialId = null;
    public String feedTagPageFromType = "0";
    public float mPlayRate = 1.0f;
}
