package com.qzone.module.feedcomponent.ui;

import com.qzone.proxy.feedcomponent.FeedGlobalEnv;

/* compiled from: P */
/* loaded from: classes39.dex */
public class AreaConst {
    public static int ADV_CONTAINER_FEED_WIDTH = 0;
    public static int ADV_CONTAINER_SUMMARY_MAX_LINE = 0;
    public static int ADV_DRESS_HEIGHT = 0;
    public static String ADV_RECOMM_HEADER_SIZE = null;
    public static final int AREA_VERTICAL_MARGIN;
    public static final int ATTACH_PIC_WIDTH_IN_PX;
    public static final int ATTACH_TEXT_MARGIN_TOP_IN_PX;
    public static final int ATTACH_TEXT_SIZIE_IN_PX;
    static final int CARD_RECOMM_ACTION_HEIGHT_IN_PX;
    public static final int COMMENT_GUIDE_PADDING_TOP;
    public static final int COMMENT_LINE_HEIGHT;
    public static final int CONTAINER_LINE_WIDTH;
    public static int DEFAULT_COMMENT_PADDING = 0;
    public static int DEFAULT_FULL_FEED_WIDTH = 0;
    public static final int DEFAULT_GUIDE_HEIGHT;
    static int DEFAULT_HEIGHT = 0;
    public static final int DEFAULT_PRAISE_WIDTH;
    public static int DEFAULT_TITLEBAR_HEIGHT = 0;
    private static int DEFAULT_WIDTH = 0;
    public static int DEFAULT_WIDTH_REC = 0;
    public static float FBG_WIDTH_WEIGHT = 0.0f;
    public static int FEED_AVATAR_DECORATION_LEFT = 0;
    public static final int FEED_BACKGROUND_PART1_HEIGHT;
    public static int FEED_INTERVAL = 0;
    public static final int FEED_VIEW_BOTTOM_BLACK_AREA;
    public static final int FEED_VIEW_LEFT_RIGH_BLACK_AREA;
    public static final int FEED_VIEW_TOP_BLACK_AREA;
    static int FORWARD_TEXT_WIDTH = 0;
    public static final int LEFT_THUMB_SUMMARY_MAX_LINE_WITHOUT_TITLE = 2;
    public static final int LEFT_THUMB_SUMMARY_MAX_LINE_WITH_TITLE = 1;
    public static final int LEFT_THUMB_TITLE_DEFAULT_MAX_LINE = 1;
    public static final int LEFT_THUMB_TITLE_MAX_LINE = 2;
    public static final int LIKE_LIST_MAX_WIDTH_RIGHT_OFFSET;
    public static final int MARGIN_LEFT;
    public static final int MARGIN_RIGHT;
    public static final int MIN_DYNAMIC_ALBUM_PIC_HEIGHT = 300;
    public static int NICKNAME_MAX_WIDTH = 0;
    static int PASSIVE_HEIGHT = 0;
    public static final float QCIRCLE_RATIO_HW = 1.13f;
    public static final float QCIRCLE_RATIO_MULTI_HW = 1.3f;
    public static int RECOMMEND_WIDTH = 0;
    public static int RECOMM_SUMMARY_WIDTH = 0;
    public static int REC_FEED_SCREENWIDEHT = 0;
    public static float REC_GAP_WIDTH_WEIGHT = 0.0f;
    public static float REC_WIDTH_WEIGHT = 0.0f;
    public static final int SCROLL_DIRECTION_THRESHHOLD;
    public static final float SQUARE_CARD_CONTAINER_WEIGHT = 0.661f;
    public static final int SQUARE_CARD_CONTAINER_WIDTH_IN_PX;
    protected static final int SUMMARY_DEFAULT_MAX_LINE = 10;
    protected static final int SUMMARY_MAX_PACK = 20;
    protected static final int SUMMARY_MIN_PACK = 10;
    protected static final int SUMMARY_PACK_OR_UNPACK_DIRECT = 1;
    protected static final int SUMMARY_PACK_SHOW_LINE = 8;
    public static int TIME_LBS_WIDTH;
    public static int TIME_LBS_WIDTH_REC;
    public static int TODAY_IN_HISTORY_WIDTH;
    public static int cardContainerGap;
    public static int cardContainerWidth;
    public static int cardContainerWingPad;
    public static int commentSummaryWidth_Rec;
    static float commentTextSize;
    private static int commentWidth;
    public static int commentWidth_Rec;

    /* renamed from: dp1, reason: collision with root package name */
    public static final int f48746dp1;
    public static final int dp10;
    public static final int dp105;
    public static final int dp10_5;
    public static final int dp11;
    public static final int dp11_5;
    public static final int dp12;
    public static final int dp12_5;
    public static final int dp13;
    public static final int dp13_5;
    public static final int dp14;
    public static final int dp14_5;
    public static final int dp15;
    public static final int dp158;
    public static final int dp16;
    public static final int dp17;
    public static final int dp18;
    public static final int dp1_3;
    public static final int dp1_5;

    /* renamed from: dp2, reason: collision with root package name */
    public static final int f48747dp2;
    public static final int dp20;
    public static final int dp204;
    public static final int dp21;
    public static final int dp213;
    public static final int dp22;
    public static final int dp22_5;
    public static final int dp23_5;
    public static final int dp24;
    public static final int dp25;
    public static final int dp26;
    public static final int dp27;
    public static final int dp28;
    public static final int dp29;
    public static final int dp2_5;

    /* renamed from: dp3, reason: collision with root package name */
    public static final int f48748dp3;
    public static final int dp30;
    public static final int dp31;
    public static final int dp32;
    public static final int dp34;
    public static final int dp35;
    public static final int dp36;
    public static final int dp37;
    public static final int dp38;
    public static final int dp39;
    public static final int dp3_5;
    public static final int dp3_75;

    /* renamed from: dp4, reason: collision with root package name */
    public static final int f48749dp4;
    public static final int dp40;
    public static final int dp42;
    public static final int dp43;
    public static final int dp44;
    public static final int dp45;
    public static final int dp47;
    public static final int dp48;
    public static final int dp4_5;
    public static final int dp5;
    public static final int dp50;
    public static final int dp51;
    public static final int dp52;
    public static final int dp53;
    public static final int dp54;
    public static final int dp55;
    public static final int dp56;
    public static final int dp57;
    public static final int dp58;
    public static final int dp59;
    public static final int dp5_5;
    public static final int dp6;
    public static final int dp60;
    public static final int dp64;
    public static final int dp65;
    public static final int dp66;
    public static final int dp6_5;
    public static final int dp7;
    public static final int dp70;
    public static final int dp72;
    public static final int dp77;
    public static final int dp7_5;
    public static final int dp8;
    public static final int dp80;
    public static final int dp83;
    public static final int dp84;
    public static final int dp88;
    public static final int dp8_5;
    public static final int dp9;
    public static final int dp90;
    public static final int dp96;
    public static final int dp9_5;
    public static int fbg_feedWidth_Rec;
    static int feedWidth;
    public static int feedWidth_Rec;
    static float leftThumbSummarySize;
    static float leftThumbTitleSize;
    public static int maxPack;
    public static int minPack;
    public static int normalMaxLines;
    public static int packOrUnpackDirect;
    public static int packShowLine;
    static float praiseListTextSize;
    static float secondTextSize;
    public static float summaryTextSize;
    public static float thirdTextSize;
    static float titleTextSize;
    static float visitListTextSize;
    public static final int SCREEN_WIDTH = FeedGlobalEnv.g().getScreenWidth();
    public static final int dp0_5 = com.qzone.proxy.feedcomponent.util.g.a(0.5f);

    static {
        int a16 = com.qzone.proxy.feedcomponent.util.g.a(1.0f);
        f48746dp1 = a16;
        dp1_3 = com.qzone.proxy.feedcomponent.util.g.a(1.3f);
        dp1_5 = com.qzone.proxy.feedcomponent.util.g.a(1.5f);
        int a17 = com.qzone.proxy.feedcomponent.util.g.a(2.0f);
        f48747dp2 = a17;
        dp2_5 = com.qzone.proxy.feedcomponent.util.g.a(2.5f);
        f48748dp3 = com.qzone.proxy.feedcomponent.util.g.a(3.0f);
        dp3_5 = com.qzone.proxy.feedcomponent.util.g.a(3.5f);
        dp3_75 = com.qzone.proxy.feedcomponent.util.g.a(3.75f);
        int a18 = com.qzone.proxy.feedcomponent.util.g.a(4.0f);
        f48749dp4 = a18;
        dp4_5 = com.qzone.proxy.feedcomponent.util.g.a(4.5f);
        int a19 = com.qzone.proxy.feedcomponent.util.g.a(5.0f);
        dp5 = a19;
        dp5_5 = com.qzone.proxy.feedcomponent.util.g.a(5.5f);
        int a26 = com.qzone.proxy.feedcomponent.util.g.a(6.0f);
        dp6 = a26;
        dp6_5 = com.qzone.proxy.feedcomponent.util.g.a(6.5f);
        dp7 = com.qzone.proxy.feedcomponent.util.g.a(7.0f);
        dp7_5 = com.qzone.proxy.feedcomponent.util.g.a(7.5f);
        int a27 = com.qzone.proxy.feedcomponent.util.g.a(8.0f);
        dp8 = a27;
        dp8_5 = com.qzone.proxy.feedcomponent.util.g.a(8.5f);
        dp9 = com.qzone.proxy.feedcomponent.util.g.a(9.0f);
        dp9_5 = com.qzone.proxy.feedcomponent.util.g.a(9.5f);
        dp10 = com.qzone.proxy.feedcomponent.util.g.a(10.0f);
        int a28 = com.qzone.proxy.feedcomponent.util.g.a(10.5f);
        dp10_5 = a28;
        dp11 = com.qzone.proxy.feedcomponent.util.g.a(11.0f);
        dp11_5 = com.qzone.proxy.feedcomponent.util.g.a(11.5f);
        dp12 = com.qzone.proxy.feedcomponent.util.g.a(12.0f);
        dp12_5 = com.qzone.proxy.feedcomponent.util.g.a(12.5f);
        dp13 = com.qzone.proxy.feedcomponent.util.g.a(13.0f);
        dp13_5 = com.qzone.proxy.feedcomponent.util.g.a(13.5f);
        int a29 = com.qzone.proxy.feedcomponent.util.g.a(14.0f);
        dp14 = a29;
        dp14_5 = com.qzone.proxy.feedcomponent.util.g.a(145.0f);
        int a36 = com.qzone.proxy.feedcomponent.util.g.a(15.0f);
        dp15 = a36;
        int a37 = com.qzone.proxy.feedcomponent.util.g.a(16.0f);
        dp16 = a37;
        int a38 = com.qzone.proxy.feedcomponent.util.g.a(17.0f);
        dp17 = a38;
        dp18 = com.qzone.proxy.feedcomponent.util.g.a(18.0f);
        int a39 = com.qzone.proxy.feedcomponent.util.g.a(20.0f);
        dp20 = a39;
        dp21 = com.qzone.proxy.feedcomponent.util.g.a(21.0f);
        dp22 = com.qzone.proxy.feedcomponent.util.g.a(22.0f);
        dp22_5 = com.qzone.proxy.feedcomponent.util.g.a(22.5f);
        dp23_5 = com.qzone.proxy.feedcomponent.util.g.a(23.5f);
        dp24 = com.qzone.proxy.feedcomponent.util.g.a(24.0f);
        dp25 = com.qzone.proxy.feedcomponent.util.g.a(25.0f);
        dp26 = com.qzone.proxy.feedcomponent.util.g.a(26.0f);
        dp27 = com.qzone.proxy.feedcomponent.util.g.a(27.0f);
        dp28 = com.qzone.proxy.feedcomponent.util.g.a(28.0f);
        dp29 = com.qzone.proxy.feedcomponent.util.g.a(29.0f);
        dp30 = com.qzone.proxy.feedcomponent.util.g.a(30.0f);
        dp31 = com.qzone.proxy.feedcomponent.util.g.a(31.0f);
        dp32 = com.qzone.proxy.feedcomponent.util.g.a(32.0f);
        dp34 = com.qzone.proxy.feedcomponent.util.g.a(34.0f);
        dp35 = com.qzone.proxy.feedcomponent.util.g.a(35.0f);
        dp36 = com.qzone.proxy.feedcomponent.util.g.a(36.0f);
        dp37 = com.qzone.proxy.feedcomponent.util.g.a(37.0f);
        dp38 = com.qzone.proxy.feedcomponent.util.g.a(38.0f);
        dp39 = com.qzone.proxy.feedcomponent.util.g.a(39.0f);
        dp40 = com.qzone.proxy.feedcomponent.util.g.a(40.0f);
        dp42 = com.qzone.proxy.feedcomponent.util.g.a(42.0f);
        dp43 = com.qzone.proxy.feedcomponent.util.g.a(43.0f);
        dp44 = com.qzone.proxy.feedcomponent.util.g.a(44.0f);
        dp45 = com.qzone.proxy.feedcomponent.util.g.a(45.0f);
        dp47 = com.qzone.proxy.feedcomponent.util.g.a(47.0f);
        dp48 = com.qzone.proxy.feedcomponent.util.g.a(48.0f);
        dp50 = com.qzone.proxy.feedcomponent.util.g.a(50.0f);
        dp51 = com.qzone.proxy.feedcomponent.util.g.a(51.0f);
        dp52 = com.qzone.proxy.feedcomponent.util.g.a(52.0f);
        dp53 = com.qzone.proxy.feedcomponent.util.g.a(53.0f);
        dp54 = com.qzone.proxy.feedcomponent.util.g.a(54.0f);
        dp55 = com.qzone.proxy.feedcomponent.util.g.a(55.0f);
        dp56 = com.qzone.proxy.feedcomponent.util.g.a(56.0f);
        dp57 = com.qzone.proxy.feedcomponent.util.g.a(57.0f);
        dp58 = com.qzone.proxy.feedcomponent.util.g.a(58.0f);
        dp59 = com.qzone.proxy.feedcomponent.util.g.a(59.0f);
        int a46 = com.qzone.proxy.feedcomponent.util.g.a(60.0f);
        dp60 = a46;
        dp64 = com.qzone.proxy.feedcomponent.util.g.a(64.0f);
        int a47 = com.qzone.proxy.feedcomponent.util.g.a(65.0f);
        dp65 = a47;
        dp66 = com.qzone.proxy.feedcomponent.util.g.a(66.0f);
        dp70 = com.qzone.proxy.feedcomponent.util.g.a(70.0f);
        dp72 = com.qzone.proxy.feedcomponent.util.g.a(72.0f);
        dp77 = com.qzone.proxy.feedcomponent.util.g.a(77.0f);
        dp80 = com.qzone.proxy.feedcomponent.util.g.a(80.0f);
        dp83 = com.qzone.proxy.feedcomponent.util.g.a(83.0f);
        dp84 = com.qzone.proxy.feedcomponent.util.g.a(84.0f);
        dp88 = com.qzone.proxy.feedcomponent.util.g.a(88.0f);
        dp90 = com.qzone.proxy.feedcomponent.util.g.a(90.0f);
        dp96 = com.qzone.proxy.feedcomponent.util.g.a(96.0f);
        dp105 = com.qzone.proxy.feedcomponent.util.g.a(105.0f);
        dp158 = com.qzone.proxy.feedcomponent.util.g.a(158.0f);
        dp204 = com.qzone.proxy.feedcomponent.util.g.a(204.0f);
        dp213 = com.qzone.proxy.feedcomponent.util.g.a(213.0f);
        COMMENT_LINE_HEIGHT = com.qzone.proxy.feedcomponent.util.g.a(0.5f);
        AREA_VERTICAL_MARGIN = a38;
        COMMENT_GUIDE_PADDING_TOP = a27;
        FEED_VIEW_TOP_BLACK_AREA = a28;
        FEED_VIEW_BOTTOM_BLACK_AREA = a17;
        FEED_VIEW_LEFT_RIGH_BLACK_AREA = com.qzone.proxy.feedcomponent.util.g.a(0.5f);
        SCROLL_DIRECTION_THRESHHOLD = a29;
        FEED_INTERVAL = a27;
        FEED_AVATAR_DECORATION_LEFT = com.qzone.proxy.feedcomponent.util.g.a(3.0f);
        DEFAULT_COMMENT_PADDING = FEED_INTERVAL;
        DEFAULT_TITLEBAR_HEIGHT = (int) (FeedGlobalEnv.g().getDensity() * 76.0f);
        DEFAULT_HEIGHT = com.qzone.proxy.feedcomponent.util.g.a(80.0f);
        PASSIVE_HEIGHT = com.qzone.proxy.feedcomponent.util.g.a(80.0f);
        DEFAULT_WIDTH = com.qzone.adapter.feedcomponent.b.a();
        DEFAULT_FULL_FEED_WIDTH = com.qzone.adapter.feedcomponent.b.c();
        TIME_LBS_WIDTH = FeedGlobalEnv.g().getScreenWidth() - com.qzone.proxy.feedcomponent.util.g.a(113.0f);
        NICKNAME_MAX_WIDTH = com.qzone.proxy.feedcomponent.util.g.a(80.0f);
        RECOMM_SUMMARY_WIDTH = FeedGlobalEnv.g().getScreenWidth() - com.qzone.proxy.feedcomponent.util.g.a(109.0f);
        TODAY_IN_HISTORY_WIDTH = FeedGlobalEnv.g().getScreenWidth() - com.qzone.proxy.feedcomponent.util.g.a(174.0f);
        DEFAULT_GUIDE_HEIGHT = com.qzone.proxy.feedcomponent.util.g.a(27.0f);
        DEFAULT_PRAISE_WIDTH = FeedGlobalEnv.g().getScreenWidth() - a39;
        MARGIN_LEFT = com.qzone.adapter.feedcomponent.j.f(274);
        MARGIN_RIGHT = com.qzone.adapter.feedcomponent.j.f(275);
        commentWidth = FeedGlobalEnv.g().getScreenWidth() - (FEED_INTERVAL * 2);
        FORWARD_TEXT_WIDTH = FeedGlobalEnv.g().getScreenWidth() - (FEED_INTERVAL * 2);
        feedWidth = FeedGlobalEnv.g().getScreenWidth() - (FEED_INTERVAL * 2);
        normalMaxLines = com.qzone.adapter.feedcomponent.h.b("QZoneSetting", "FeedTextMaxLine", 10);
        packOrUnpackDirect = com.qzone.adapter.feedcomponent.h.b("QZoneSetting", "FeedSummaryExpandDirect", 1);
        maxPack = com.qzone.adapter.feedcomponent.h.b("QZoneSetting", "FeedSummaryMaxMaxLine", 20);
        minPack = com.qzone.adapter.feedcomponent.h.b("QZoneSetting", "FeedSummaryMinMaxLine", 10);
        packShowLine = com.qzone.adapter.feedcomponent.h.b("QZoneSetting", "FeedSummaryShowNumUnExpand", 8);
        titleTextSize = com.qzone.adapter.feedcomponent.j.N("feed");
        RECOMMEND_WIDTH = a46;
        LIKE_LIST_MAX_WIDTH_RIGHT_OFFSET = a47;
        REC_WIDTH_WEIGHT = 0.9028f;
        REC_GAP_WIDTH_WEIGHT = 0.019444f;
        int i3 = a17 + 1;
        CONTAINER_LINE_WIDTH = i3;
        cardContainerGap = a16;
        cardContainerWingPad = a27;
        int screenWidth = ((int) (FeedGlobalEnv.g().getScreenWidth() * REC_WIDTH_WEIGHT)) - a26;
        feedWidth_Rec = screenWidth;
        FBG_WIDTH_WEIGHT = 0.9028f;
        int i16 = screenWidth - (i3 * 2);
        commentWidth_Rec = i16;
        cardContainerWidth = (screenWidth + a26) - (cardContainerGap + cardContainerWingPad);
        commentSummaryWidth_Rec = i16 - ((a16 + i3) + (FEED_INTERVAL * 2));
        REC_FEED_SCREENWIDEHT = i16;
        ADV_CONTAINER_FEED_WIDTH = (((int) (FeedGlobalEnv.g().getScreenWidth() * REC_WIDTH_WEIGHT)) - a26) - a18;
        ADV_CONTAINER_SUMMARY_MAX_LINE = 2;
        DEFAULT_WIDTH_REC = com.qzone.adapter.feedcomponent.b.a() - RECOMMEND_WIDTH;
        fbg_feedWidth_Rec = ((int) (FeedGlobalEnv.g().getScreenWidth() * FBG_WIDTH_WEIGHT)) - a26;
        ADV_RECOMM_HEADER_SIZE = "1080_60";
        ADV_DRESS_HEIGHT = a19;
        TIME_LBS_WIDTH_REC = feedWidth_Rec - ((int) (FeedGlobalEnv.g().getDensity() * 114.0f));
        summaryTextSize = 16.0f;
        ATTACH_PIC_WIDTH_IN_PX = com.qzone.proxy.feedcomponent.util.g.a(100.0f);
        ATTACH_TEXT_MARGIN_TOP_IN_PX = com.qzone.proxy.feedcomponent.util.g.a(15.0f);
        ATTACH_TEXT_SIZIE_IN_PX = a37;
        SQUARE_CARD_CONTAINER_WIDTH_IN_PX = ((((int) (FeedGlobalEnv.g().getScreenWidth() * 0.661f)) - a26) - (i3 * 2)) + a17;
        CARD_RECOMM_ACTION_HEIGHT_IN_PX = a18 * 11;
        float N = com.qzone.adapter.feedcomponent.j.N("feed_left_thumb");
        leftThumbSummarySize = N;
        leftThumbTitleSize = N;
        secondTextSize = 12.0f;
        visitListTextSize = 12.0f;
        praiseListTextSize = 14.0f;
        commentTextSize = 14.0f;
        thirdTextSize = 12.0f;
        FEED_BACKGROUND_PART1_HEIGHT = a36;
    }

    public static int getCommentWidth() {
        return com.qzone.adapter.feedcomponent.b.a();
    }

    public static int getDefaultWidth() {
        return com.qzone.adapter.feedcomponent.b.a();
    }
}
