package com.tencent.mobileqq.profilecard.api;

import com.tencent.mobileqq.qfix.redirect.IPatchRedirector;
import com.tencent.mobileqq.qfix.redirect.PatchRedirectCenter;
import com.tencent.mobileqq.qfix.redirect.utils.ReflectUtils;
import com.tencent.mobileqq.qroute.QRoute;
import com.tencent.mobileqq.studymode.api.IStudyModeManager;
import uq3.c;

/* loaded from: classes16.dex */
public interface IProfileCardConst {
    public static final IPatchRedirector $redirector_ = null;
    public static final String ACTION_AVATAR_FROM_PHOTO_EDIT = "com.tencent.mobileqq.avatar.photo.edit";
    public static final String ACTION_COVER_FROM_PHOTO_EDIT = "com.tencent.mobileqq.cover.photo.edit";
    public static final String ACTION_MODIFY_DETAIL_INFO = "com.tencent.mobileqq.card.modify";
    public static final String ACTION_PROFILE_EDIT_AVATAR_FROM_PHOTO_EDIT = "com.tencent.mobileqq.profileedit.avatar.photo.edit";
    public static final int AIO_ADD_PHONE = 9;
    public static final int AIO_REMARK_GRAY_TIPS = 8;
    public static final int AVATAR_ACTION_SHEET_AIGC_MAGIC_AVATAR = 9;
    public static final int AVATAR_ACTION_SHEET_AI_AVATAR = 10;
    public static final int AVATAR_ACTION_SHEET_ALBUM = 4;
    public static final int AVATAR_ACTION_SHEET_BIG_PIC = 1;
    public static final int AVATAR_ACTION_SHEET_CIRCLE_DYNAMIC = 8;
    public static final int AVATAR_ACTION_SHEET_DIY = 5;
    public static final int AVATAR_ACTION_SHEET_DYNAMIC = 6;
    public static final int AVATAR_ACTION_SHEET_HISTORY = 2;
    public static final String AVATAR_ACTION_SHEET_KEY_ID = "id";
    public static final String AVATAR_ACTION_SHEET_KEY_TITLE = "title";
    public static final String AVATAR_ACTION_SHEET_MALL = "avatarMallScene";
    public static final String AVATAR_ACTION_SHEET_PROFILE = "simpleProfileScene";
    public static final String AVATAR_ACTION_SHEET_PROFILE_EDIT = "simpleProfileEdit";
    public static final int AVATAR_ACTION_SHEET_TAKE_PIC = 3;
    public static final int AVATAR_ACTION_SHEET_ZPLAN = 7;
    public static final String CODE_NO_LIMIT = "0";
    public static final String DEFAULT_COUNTRY_CODE = "1";
    public static final String DRAWER_LEVEL_URL = "https://ti.qq.com/qqlevel/index?_wv=3&_wwv=1&tab=6&source=15";
    public static final String DRAWER_QQXMAN_URL = "https://ti.qq.com/qqdaren/index?_wv=16777219&_wwv=128&ADTAG=draw";
    public static final String HOST_ORIGINAL = "original";
    public static final String HOST_OTHER = "other";
    public static final String HOST_THUMB = "thumb";
    public static final int JUMP_WITH_EMPTY_LABEL = 2;
    public static final int JUMP_WITH_EMPTY_PHOTO = 1;
    public static final int JUMP_WITH_EMPTY_PHOTO_AND_LABEL = 3;
    public static final int JUMP_WITH_NO_EMPTY = 0;
    public static final String KEY_ALL_IN_ONE = "AllInOne";
    public static final String KEY_COVER_PICK_GALLERY = "action_cover_pick_gallery";
    public static final String KEY_DELETE_ABILITY = "delete_ability";
    public static final String KEY_FROM_APP_SHOW_DIALOG = "key_from_app_show_dialog";
    public static final String KEY_FROM_ARK_BABYQ = "key_from_ark_babyq";
    public static final String KEY_FROM_EXTENDS_FRIENDS = "key_from_extends_friend";
    public static final String KEY_FROM_EXTENDS_FRIENDS_LIMIT_CHAT = "key_from_extends_friend_limit_chat";
    public static final String KEY_FROM_LIMIT_CHAT_PLUS = "key_from_limit_chat_plus";
    public static final String KEY_FROM_SET_AVATAR_RESULT = "key_from_sdk_set_avatar_result";
    public static final String KEY_FROM_TYPE = "fromType";
    public static final String KEY_HIDE_MORE_BUTTON = "hide_more_button";
    public static final String KEY_HIDE_OPERATION_BAR = "hide_operation_bar";
    public static final String KEY_PERSONALITY_LABEL_GALLERY_RESULT = "personality_label_gallery";

    @Deprecated
    public static final String KEY_PROFILE_EXTRA = "profile_extra";
    public static final String KEY_PROFILE_ZPLAN_GUIDE = "sp_key_profile_zplan_guide";
    public static final String KEY_SHOW_ACTION_SHEET = "key_show_action_sheet";
    public static final String KEY_URL = "url";
    public static final String KEY_WZRY_DATA = "param_wzry_data";
    public static final int LAST_ACTIVITY_AIO = 2;
    public static final int LAST_ACTIVITY_CHAT_OPTION = 5;
    public static final int LAST_ACTIVITY_MY_PROFILE = 1;
    public static final int LAST_ACTIVITY_NEARBY = 4;
    public static final int LAST_ACTIVITY_SC_QZONE_WIDGET = 100;
    public static final int LAST_ACTIVITY_STRANGER_MANAGE = 101;
    public static final int LAST_ACTIVITY_TROOP = 3;
    public static final int LAST_ACTIVITY_TROOP_ZONE = 6;
    public static final int MENU_ITEM_CALL = 7;
    public static final int MENU_ITEM_CANCEL = 16;
    public static final int MENU_ITEM_SEND_MSG = 8;
    public static final int MENU_ITEM_SET_REMARK = 9;
    public static final String MUSIC_GENE_URL = "https://y.qq.com/m/gene/index.html?uin=%s&_bid=155&_wv=10017";
    public static final String NAME_NO_LIMIT = "\u4e0d\u9650";
    public static final String PARAM_ADD_FRIEND_ID = "param_add_friend_id";
    public static final String PARAM_ADD_FRIEND_SUB_ID = "param_add_friend_sub_id";
    public static final String PARAM_LOCATION_CODE = "param_location";
    public static final String PARAM_SWITCHES_CHANGED = "param_switches_changed";
    public static final int PA_CRM_MAIN = 125;
    public static final int PA_FRIEND_FROM_CONTACT = 30;
    public static final int PA_FRIEND_FROM_DISCUSSION = 45;
    public static final int PA_FRIEND_FROM_NEAR_PEOPLE = 40;
    public static final int PA_FRIEND_FROM_QZONE = 60;
    public static final int PA_FRIEND_FROM_RICHSTATUS = 55;
    public static final int PA_FRIEND_FROM_TROOP = 20;
    public static final int PA_FRIEND_PROFILE = 1;
    public static final int PA_FROM_AV_GAME_SEAT = 118;
    public static final int PA_FROM_FLOCK = 126;
    public static final int PA_FROM_GUILD = 124;
    public static final int PA_FROM_TEAM_WROK = 90;
    public static final int PA_MAYKNOW_FROM_ADDFRIEND = 82;
    public static final int PA_MAYKNOW_FROM_ALL = 83;
    public static final int PA_MAYKNOW_FROM_CONTACT_BANNER = 101;
    public static final int PA_MAYKNOW_FROM_CONTACT_TAB = 103;
    public static final int PA_MAYKNOW_FROM_CONVERSATION = 102;
    public static final int PA_MAYKNOW_FROM_EXTEND_FRIEND_ENTRANCE = 123;
    public static final int PA_MAYKNOW_FROM_FINDNEWFRIEND = 107;
    public static final int PA_MAYKNOW_FROM_NEWFRIEND = 81;
    public static final int PA_MAYKNOW_FROM_QZONE = 84;
    public static final int PA_MAYKNOW_NEWFRIEND_CONNECTIONS = 110;
    public static final int PA_MSGBOX_FEED = 89;
    public static final int PA_MY_PROFILE = 0;
    public static final int PA_NEWFRIEND_VERIFY_BLOCKED = 109;
    public static final int PA_SCHOOL_CLASSMATE = 106;
    public static final int PA_STRANGER_FROM_ADD_VERYFY = 25;
    public static final int PA_STRANGER_FROM_ADD_VERYFY_TROOP = 26;
    public static final int PA_STRANGER_FROM_ADD_VERYFY_UNDECIDED = 28;
    public static final int PA_STRANGER_FROM_ADD_VERYFY_UNDECIDED_SUSPICIOUS = 108;
    public static final int PA_STRANGER_FROM_AUDIOROOM_TEMP_TALK = 117;
    public static final int PA_STRANGER_FROM_BINARYCODE = 3;
    public static final int PA_STRANGER_FROM_BMQQ = 104;
    public static final int PA_STRANGER_FROM_CHECKFRIEND_TEMP_TALK = 27;
    public static final int PA_STRANGER_FROM_COMTACT = 33;
    public static final int PA_STRANGER_FROM_COND_SEARCH = 75;
    public static final int PA_STRANGER_FROM_CONTACT1_6 = 32;
    public static final int PA_STRANGER_FROM_CONTACT_NON_1_6 = 31;
    public static final int PA_STRANGER_FROM_CONTACT_SELF_UNBIND = 29;
    public static final int PA_STRANGER_FROM_CONTACT_SHARE_CARD = 53;
    public static final int PA_STRANGER_FROM_CONTACT_TEMP_TALK = 34;
    public static final int PA_STRANGER_FROM_DATE = 75;
    public static final int PA_STRANGER_FROM_DATE_TEMP_TALK = 76;
    public static final int PA_STRANGER_FROM_DISCUSSION = 46;
    public static final int PA_STRANGER_FROM_DISCUSSION_TEMP_TALK = 47;
    public static final int PA_STRANGER_FROM_EXTEND_FRIEND = 96;
    public static final int PA_STRANGER_FROM_EXTEND_GROUP = 97;
    public static final int PA_STRANGER_FROM_FANS_WEB = 88;
    public static final int PA_STRANGER_FROM_FOLLOW_WEB = 87;
    public static final int PA_STRANGER_FROM_FRESHNEWS = 79;
    public static final int PA_STRANGER_FROM_GROUP_VIDEO_MATCHMAKER = 116;
    public static final int PA_STRANGER_FROM_HOT_CHAT_TROOP = 58;
    public static final int PA_STRANGER_FROM_KANDIAN = 98;
    public static final int PA_STRANGER_FROM_LIGHTALK = 80;
    public static final int PA_STRANGER_FROM_MAYKNOW_NEW = 77;
    public static final int PA_STRANGER_FROM_MAY_KNOWN = 4;
    public static final int PA_STRANGER_FROM_MOVIE_TICKET_TALK = 94;
    public static final int PA_STRANGER_FROM_NEARPEOPLE = 41;
    public static final int PA_STRANGER_FROM_NEARPEOPLE_TEMP_TALK = 42;
    public static final int PA_STRANGER_FROM_NET_SEARCH = 35;
    public static final int PA_STRANGER_FROM_NET_SEARCH_CONTACT = 36;
    public static final int PA_STRANGER_FROM_NET_SEARCH_FROM_ADD_CONTACT = 37;
    public static final int PA_STRANGER_FROM_ONE_SIDE_FRIEND = 70;
    public static final int PA_STRANGER_FROM_PC_QQ_SEARCH = 74;
    public static final int PA_STRANGER_FROM_PERSONALCONN_TEMP_TALK = 72;
    public static final int PA_STRANGER_FROM_QCIRCLE_PERSONAL_DETAIL = 115;
    public static final int PA_STRANGER_FROM_QQSTORY = 59;
    public static final int PA_STRANGER_FROM_QZONE = 61;
    public static final int PA_STRANGER_FROM_RECOMMEND_CONTACT_1_6 = 51;
    public static final int PA_STRANGER_FROM_RECOMMEND_CONTACT_NON_1_6 = 50;
    public static final int PA_STRANGER_FROM_RECOMMEND_MAYKNOW = 52;
    public static final int PA_STRANGER_FROM_RICHSTATUS = 56;
    public static final int PA_STRANGER_FROM_RICHSTATUS_TEMP_TALK = 57;
    public static final int PA_STRANGER_FROM_SEARCH_PERSONALCONN = 71;
    public static final int PA_STRANGER_FROM_SHARE = 111;
    public static final int PA_STRANGER_FROM_SHARE_CARD_SEARCH = 78;
    public static final int PA_STRANGER_FROM_SINGLE_FRIEND_TEMP_TALK = 73;
    public static final int PA_STRANGER_FROM_STICKY_NOTE = 114;
    public static final int PA_STRANGER_FROM_TRIBE_TEMP_TALK = 86;
    public static final int PA_STRANGER_FROM_TROOP = 21;
    public static final int PA_STRANGER_FROM_TROOP_MUTUAL_MARK = 112;
    public static final int PA_STRANGER_FROM_TROOP_TEMP_TALK = 22;
    public static final int PA_STRANGER_FROM_UNKNOWN = 19;
    public static final int PA_STRANGER_FROM_WEB = 105;
    public static final int PA_STRANGER_FROM_WHOLE_PEOPLE = 95;
    public static final int PA_STRANGER_FROM_WPA_TEMP_TALK = 2;
    public static final int PA_STRANGE_FROM_TROOP_OTHER = 120;
    public static final int PA_STRANGE_FROM_TROOP_SEARCH = 23;
    public static final int PA_STRANGE_FROM_TROOP_SYSTEM_NOTICE = 24;
    public static final int PA_TROOP_RECOMMEND = 113;
    public static final String PROFILE_DETAIL_URL = "https://ti.qq.com/qcard/profile?qq=%s&appid=%s&version=%s&_wv=1027&type=1";
    public static final int PROFILE_ENTRY_AIO = 1;
    public static final int PROFILE_ENTRY_AIO_ADD_PHONE = 123;
    public static final int PROFILE_ENTRY_AIO_DISCUSSION = 107;
    public static final int PROFILE_ENTRY_AIO_GRAY_TIPS = 117;
    public static final int PROFILE_ENTRY_AIO_TEMP_TALK = 106;
    public static final int PROFILE_ENTRY_AIO_TROOP = 108;
    public static final int PROFILE_ENTRY_AIO_UIN_SEARCH = 124;
    public static final int PROFILE_ENTRY_CHATOPTION_AVATAR = 57;
    public static final int PROFILE_ENTRY_CHATOPTION_VIEWPROFILE = 61;
    public static final int PROFILE_ENTRY_CIRCLECONN = 84;
    public static final int PROFILE_ENTRY_COND_SEARCH = 87;
    public static final int PROFILE_ENTRY_CONTACTLIST = 59;
    public static final int PROFILE_ENTRY_CONTACT_BINDED_IGNORE = 104;
    public static final int PROFILE_ENTRY_CONTACT_BINDED_NORMAL = 102;
    public static final int PROFILE_ENTRY_CONTACT_BINDED_SEARCH = 103;
    public static final int PROFILE_ENTRY_CONTACT_BINDED_STAR = 101;
    public static final int PROFILE_ENTRY_CONVERSATION = 6;
    public static final int PROFILE_ENTRY_DATING_ADD_FRIEND_MSG = 15;
    public static final int PROFILE_ENTRY_DATING_AIO = 11;
    public static final int PROFILE_ENTRY_DATING_CHAT_SETTING = 13;
    public static final int PROFILE_ENTRY_DATING_DETAIL = 18;
    public static final int PROFILE_ENTRY_DATING_I_APPLIED = 19;
    public static final int PROFILE_ENTRY_DATING_LIST = 17;
    public static final int PROFILE_ENTRY_DEFAULT = 999;
    public static final int PROFILE_ENTRY_FACE2FACE_ADD_CONTACT = 126;
    public static final int PROFILE_ENTRY_FAVORITEL_LIST = 38;
    public static final int PROFILE_ENTRY_FLOCK = 130;
    public static final int PROFILE_ENTRY_FNINFO = 34;
    public static final int PROFILE_ENTRY_FNLIST = 35;
    public static final int PROFILE_ENTRY_FRESHNEWS = 32;
    public static final int PROFILE_ENTRY_HCMLIST = 33;
    public static final int PROFILE_ENTRY_HC_AIO = 31;
    public static final int PROFILE_ENTRY_HOTCHAT = 20;
    public static final int PROFILE_ENTRY_INTEREST_LIST = 99;
    public static final int PROFILE_ENTRY_INTIMATE_SHARE = 118;
    public static final int PROFILE_ENTRY_LIKE_LIST = 16;
    public static final int PROFILE_ENTRY_LOCALSEARCH = 60;
    public static final int PROFILE_ENTRY_MAYKNOW = 64;
    public static final int PROFILE_ENTRY_MAYKNOW_NEW = 88;
    public static final int PROFILE_ENTRY_MYVISITOR = 37;
    public static final int PROFILE_ENTRY_NEARBY = 5;
    public static final int PROFILE_ENTRY_NEARBY_PEOPLE_ADD_FRIEND_MSG = 14;
    public static final int PROFILE_ENTRY_NEARBY_PEOPLE_AIO = 10;
    public static final int PROFILE_ENTRY_NEARBY_PEOPLE_CHAT_SETTING = 12;
    public static final int PROFILE_ENTRY_NET_SEARCH = 98;
    public static final int PROFILE_ENTRY_NET_SEARCH_QID = 129;
    public static final int PROFILE_ENTRY_NEW_FRIEND_DEFAULT = 109;
    public static final int PROFILE_ENTRY_NEW_USER_GUIDE = 100;
    public static final int PROFILE_ENTRY_QAPP_GAME_FRIEND = 115;
    public static final int PROFILE_ENTRY_QCIRCLE_PERSONAL_DETAIL = 128;
    public static final int PROFILE_ENTRY_QQSETTING = 8;
    public static final int PROFILE_ENTRY_QZONE = 7;
    public static final int PROFILE_ENTRY_QZONE_WARM_FEED = 125;
    public static final int PROFILE_ENTRY_RANK_LIST = 21;
    public static final int PROFILE_ENTRY_RICHSTATUS = 68;
    public static final int PROFILE_ENTRY_SINGE_WAY_FRIEND = 127;
    public static final int PROFILE_ENTRY_STRANGER_OTHER = 30;
    public static final int PROFILE_ENTRY_STRUCTMSG_SHARE_CARD = 105;
    public static final int PROFILE_ENTRY_THIRD_PARTY_ADD_FRIEND = 119;
    public static final int PROFILE_ENTRY_TROOPMEMBERLIST = 4;
    public static final int PROFILE_ENTRY_TROOP_RECOMMEND = 122;
    public static final int PROFILE_ENTRY_WECHAT_SHARE = 121;
    public static final int PROFILE_ENTRY_WEREWOLVES = 113;
    public static final String PROFILE_JUMP_WITH_BUBBLE = "profile_jump_with_bubble";
    public static final String PROFILE_JUMP_WITH_ITEM_EMPTY = "profile_jump_with_item_empty";
    public static final String PROFILE_JUMP_WITH_PHOTO_NUM = "profile_jump_with_photo_num";
    public static final String PROFILE_MEDAL_URL = "https://ti.qq.com/qqmedal2/index.html?_wv=1&_bid=2450&_nav_alpha=0&_nav_txtclr=ffffff&_nav_titleclr=ffffff&_nav_anim=true&_wwv=4&from_web=29&tuin=";
    public static final int PROFILE_NEWFRIEND_VERIFY_BLOCKED = 120;
    public static final String PROFILE_QQXMAN_URL = "https://ti.qq.com/qqdaren/index?_wv=16777219&_wwv=128&ADTAG=card";
    public static final String PROFILE_SCROLL_TO_ACHIEVEMENT = "profile_scroll_to_achievement";
    public static final String PROFILE_SCROLL_TO_PHOTO_WALL = "profile_scroll_to_photo_wall";
    public static final String PROTOCOL_QZONE_COVER = "qzone_cover";
    public static final int REQUEST_FOR_ADD_FRIEND = 99000;
    public static final int REQUEST_FOR_ADD_REQUEST = 1018;
    public static final int REQUEST_FOR_BIND_PHONE = 1032;
    public static final int REQUEST_FOR_BUSINESSCARD_DISPAY = 1016;
    public static final int REQUEST_FOR_BUY_STOCK = 1028;
    public static final int REQUEST_FOR_COVER_PICK_GALLERY = 1025;
    public static final int REQUEST_FOR_COVER_PICK_QZONE = 1020;
    public static final int REQUEST_FOR_COVER_TAKE_PHOTO = 1021;
    public static final int REQUEST_FOR_CREATE_MINI_HOME = 1040;
    public static final int REQUEST_FOR_CUSTOM_COVER = 1024;
    public static final int REQUEST_FOR_DIY_EDIT_PAGE = 1036;
    public static final int REQUEST_FOR_EDIT_BEIZHU = 1003;
    public static final int REQUEST_FOR_EDIT_NICK = 1034;
    public static final int REQUEST_FOR_EDIT_TAG = 1004;
    public static final int REQUEST_FOR_EXTEND_FRIEND_SEARCH = 1033;
    public static final int REQUEST_FOR_EXTEND_FRIEND_SQUARE = 1031;
    public static final int REQUEST_FOR_MORE_INFO = 1022;
    public static final int REQUEST_FOR_MORE_V2 = 1038;
    public static final int REQUEST_FOR_ONE_SIDE_FRIEND_AIO = 1010;
    public static final int REQUEST_FOR_PERSONALITY_LABEL_GALLERY = 1029;
    public static final int REQUEST_FOR_PICTURE_VIEWER = 1014;
    public static final int REQUEST_FOR_PROFILECARD_MORE = 1012;
    public static final int REQUEST_FOR_SDK_SETAVATAR = 1035;
    public static final int REQUEST_FOR_START_AUTOREMARK = 1017;
    public static final int REQUEST_FOR_VAS_DRESSUP = 1039;
    public static final int REQUEST_FOR_WRITE_MOOD = 1037;
    public static final int REQUEST_FROM_VOTE_LIST = 1023;
    public static final int REQUEST_FRO_MYPROFILE = 1009;
    public static final String SHARE_TO_QZONE_ICON_URL = "https://downv6.qq.com/qq_relation/ask_anonymously/ask_anonymously_invite_icon_to_qzone_v2.png";
    public static final int SHARE_TYPE_INVITE = 1;
    public static final int SIMPLE_SOURCE_AVATAR_ACTION_SHEET_EDIT = 2;
    public static final int SIMPLE_SOURCE_AVATAR_ACTION_SHEET_SHOW = 1;
    public static final int SP_VALUE_PROFILE_ZPLAN_GUIDED = 1;
    public static final int SP_VALUE_PROFILE_ZPLAN_GUIDE_DEFAULT = 0;
    public static final String URL_PHOTO_WALL;
    public static final String VIP_QQ_FROM_DISCUSS = "mvip.pingtai.mobileqq.androidziliaoka.fromtaolunzu";
    public static final String VIP_QQ_FROM_DRAWER = "mvip.pingtai.mobileqq.androidziliaoka.fromdrawer";
    public static final String VIP_QQ_FROM_NEARBY = "mvip.pingtai.mobileqq.androidziliaoka.fromfujinderen";
    public static final String VIP_QQ_FROM_OTHER = "mvip.pingtai.mobileqq.androidziliaoka.fromqita";
    public static final String VIP_QQ_FROM_TEMPTALK = "mvip.pingtai.mobileqq.androidziliaoka.fromlinshihuihua";
    public static final String VIP_QQ_FROM_TROOP = "mvip.pingtai.mobileqq.androidziliaoka.fromqqqun";

    static {
        String str;
        ReflectUtils.setStaticField(PatchRedirectCenter.getRedirector(32921), (Class<?>) IProfileCardConst.class, "$redirector_");
        IPatchRedirector iPatchRedirector = $redirector_;
        if (iPatchRedirector != null && iPatchRedirector.hasPatch((short) 1)) {
            iPatchRedirector.redirect((short) 1);
            return;
        }
        if (!((IStudyModeManager) QRoute.api(IStudyModeManager.class)).getStudyModeSwitch() && c.s6()) {
            str = "https://ti.qq.com/photowall/index.html?_wv=1027&redirect=1&show_video_publish=1";
        } else {
            str = "https://ti.qq.com/photowall/index.html?_wv=1027";
        }
        URL_PHOTO_WALL = str;
    }
}
