package tencent.im.cs.longconn;

import com.heytap.databaseengine.type.DataTableNameType;
import com.qzone.proxy.covercomponent.QzoneCoverConst;
import com.tencent.ad.tangram.protocol.gdt_analysis_event;
import com.tencent.ad.tangram.statistics.AdReporterForEffect;
import com.tencent.biz.qqcircle.immersive.constants.QFSNumberConstants;
import com.tencent.biz.qqcircle.immersive.feed.event.QFSBottomDynamicGuideEvent;
import com.tencent.ecommerce.repo.consumer.resp.PlayUI;
import com.tencent.luggage.wxa.fe.a;
import com.tencent.luggage.wxa.gf.y;
import com.tencent.luggage.wxa.ig.w;
import com.tencent.luggage.wxa.rf.g;
import com.tencent.luggage.wxa.sm.e;
import com.tencent.luggage.wxa.uf.l;
import com.tencent.luggage.wxa.uf.n;
import com.tencent.luggage.wxa.v6.d;
import com.tencent.luggage.wxa.wh.b;
import com.tencent.luggage.wxa.yf.x;
import com.tencent.mm.plugin.appbrand.jsapi.sensor.JsApiEnableDeviceOrientation;
import com.tencent.mobileqq.activity.SubAccountBindActivity;
import com.tencent.mobileqq.cardcontainer.api.impl.CardContainerDataServiceImpl;
import com.tencent.mobileqq.data.troop.TroopInfo;
import com.tencent.mobileqq.microapp.sdk.LaunchParam;
import com.tencent.mobileqq.pb.ByteStringMicro;
import com.tencent.mobileqq.pb.MessageMicro;
import com.tencent.mobileqq.pb.PBBoolField;
import com.tencent.mobileqq.pb.PBBytesField;
import com.tencent.mobileqq.pb.PBEnumField;
import com.tencent.mobileqq.pb.PBField;
import com.tencent.mobileqq.pb.PBFixed32Field;
import com.tencent.mobileqq.pb.PBRepeatField;
import com.tencent.mobileqq.pb.PBRepeatMessageField;
import com.tencent.mobileqq.pb.PBStringField;
import com.tencent.mobileqq.pb.PBUInt32Field;
import com.tencent.mobileqq.pb.PBUInt64Field;
import com.tencent.mobileqq.qzoneplayer.ui.common.PlayerResources;
import com.tencent.mobileqq.startup.step.InitSkin;
import com.tencent.qqlive.tvkplayer.qqliveasset.player.message.TVKQQLiveAssetPlayerMsg;
import com.tencent.qqlive.tvkplayer.tpplayer.tools.TVKTPCapability;
import com.tencent.qqnt.kernel.nativeinterface.MsgConstant;
import com.tencent.tmassistantbase.common.TMAssistantDownloadErrorCode;
import com.tencent.util.notification.NotificationController;
import com.tencent.view.FilterEnum;
import cooperation.qzone.report.lp.LpReportInfoConfig;

/* compiled from: P */
/* loaded from: classes29.dex */
public final class hd_video$ReqBody extends MessageMicro<hd_video$ReqBody> {
    static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90}, new String[]{"msg_video_head", "msg_create_room_body", "msg_invite_body", "msg_accept_body", "msg_refuse_body", "msg_ignore_body", "msg_logout_body", "msg_query_info_body", "msg_sdk_stat_body", "msg_update_body", "msg_sdk_info_body"}, new Object[]{null, null, null, null, null, null, null, null, null, null, null}, hd_video$ReqBody.class);
    public hd_video$VideoHead msg_video_head = new hd_video$VideoHead();
    public hd_video$CmdCreateRoomReqBody msg_create_room_body = new MessageMicro<hd_video$CmdCreateRoomReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdCreateRoomReqBody
        static final MessageMicro.FieldMap __fieldMap__;
        public final PBBytesField bytes_dc_report_buf;
        public final PBBytesField bytes_interface_ipv6;
        public final PBUInt32Field client_ip_stack;
        public final PBUInt32Field uint32_invite_scene;
        public final PBUInt32Field uint32_retry_times;
        public final PBUInt32Field uint32_watch_video_flag;
        public final PBEnumField enum_business_type = PBField.initEnum(1);
        public final PBUInt64Field uint64_business_id = PBField.initUInt64(0);
        public final PBUInt32Field uint32_business_flag = PBField.initUInt32(0);
        public final PBFixed32Field fixed32_client_seq = PBField.initFixed32(0);
        public final PBUInt32Field uint32_flag = PBField.initUInt32(0);
        public final PBFixed32Field fixed32_interface_ip = PBField.initFixed32(0);
        public final PBRepeatMessageField<hd_video$UinRelationship> rpt_msg_uin_list = PBField.initRepeatMessage(hd_video$UinRelationship.class);
        public final PBBoolField bool_terminal_switch_flag = PBField.initBool(false);
        public final PBUInt64Field uint64_old_room_id = PBField.initUInt64(0);

        static {
            ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
            __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16, 24, 37, 40, 53, 58, 64, 72, 82, 90, 96, 104, 112, 120}, new String[]{"enum_business_type", "uint64_business_id", "uint32_business_flag", "fixed32_client_seq", "uint32_flag", "fixed32_interface_ip", "rpt_msg_uin_list", "bool_terminal_switch_flag", "uint64_old_room_id", "bytes_dc_report_buf", "bytes_interface_ipv6", "uint32_watch_video_flag", "client_ip_stack", "uint32_invite_scene", "uint32_retry_times"}, new Object[]{1, 0L, 0, 0, 0, 0, null, Boolean.FALSE, 0L, byteStringMicro, byteStringMicro, 0, 0, 0, 0}, hd_video$CmdCreateRoomReqBody.class);
        }

        {
            ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
            this.bytes_dc_report_buf = PBField.initBytes(byteStringMicro);
            this.bytes_interface_ipv6 = PBField.initBytes(byteStringMicro);
            this.uint32_watch_video_flag = PBField.initUInt32(0);
            this.client_ip_stack = PBField.initUInt32(0);
            this.uint32_invite_scene = PBField.initUInt32(0);
            this.uint32_retry_times = PBField.initUInt32(0);
        }
    };
    public hd_video$CmdInviteUsersReqBody msg_invite_body = new MessageMicro<hd_video$CmdInviteUsersReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdInviteUsersReqBody
        static final MessageMicro.FieldMap __fieldMap__;
        public hd_video$InviteTempSessionData msg_temp_session = new hd_video$InviteTempSessionData();
        public final PBFixed32Field fixed32_interface_ip = PBField.initFixed32(0);
        public final PBEnumField enum_termtype = PBField.initEnum(1);
        public final PBUInt32Field uint32_client_ver = PBField.initUInt32(0);
        public final PBBoolField bool_terminal_switch_flag = PBField.initBool(false);
        public final PBUInt64Field uint64_old_room_id = PBField.initUInt64(0);
        public final PBBoolField bool_chat_with_anyone = PBField.initBool(false);
        public final PBStringField str_interesting_chat_buf = PBField.initString("");
        public final PBRepeatMessageField<hd_video$UinRelationship> rpt_msg_uin_list = PBField.initRepeatMessage(hd_video$UinRelationship.class);
        public final PBUInt32Field uint32_recovery_room_flag = PBField.initUInt32(0);
        public final PBBytesField bytes_interface_ipv6 = PBField.initBytes(ByteStringMicro.EMPTY);
        public final PBUInt32Field uint32_watch_video_flag = PBField.initUInt32(0);
        public final PBUInt32Field uint32_invite_scene = PBField.initUInt32(0);

        static {
            Boolean bool = Boolean.FALSE;
            __fieldMap__ = MessageMicro.initFieldMap(new int[]{10, 21, 24, 32, 40, 48, 56, 66, 74, 80, 90, 96, 104}, new String[]{"msg_temp_session", "fixed32_interface_ip", "enum_termtype", "uint32_client_ver", "bool_terminal_switch_flag", "uint64_old_room_id", "bool_chat_with_anyone", "str_interesting_chat_buf", "rpt_msg_uin_list", "uint32_recovery_room_flag", "bytes_interface_ipv6", "uint32_watch_video_flag", "uint32_invite_scene"}, new Object[]{null, 0, 1, 0, bool, 0L, bool, "", null, 0, ByteStringMicro.EMPTY, 0, 0}, hd_video$CmdInviteUsersReqBody.class);
        }
    };
    public hd_video$CmdAcceptInviteReqBody msg_accept_body = new MessageMicro<hd_video$CmdAcceptInviteReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdAcceptInviteReqBody
        static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16, 24, 34, 40, 50, 58, 66, 72}, new String[]{"uint32_app_id", "enum_termtype", "uint32_voip_flag", "rpt_msg_voip_media_addr_list", "uint32_sip_cmd_type", "msg_audio_proto", "sip_server", "msg_local_audio_proto", "client_ip_stack"}, new Object[]{0, 1, 0, null, 0, null, null, null, 0}, hd_video$CmdAcceptInviteReqBody.class);
        public final PBUInt32Field uint32_app_id = PBField.initUInt32(0);
        public final PBEnumField enum_termtype = PBField.initEnum(1);
        public final PBUInt32Field uint32_voip_flag = PBField.initUInt32(0);
        public final PBRepeatMessageField<hd_video_comm$NetAddr> rpt_msg_voip_media_addr_list = PBField.initRepeatMessage(hd_video_comm$NetAddr.class);
        public final PBUInt32Field uint32_sip_cmd_type = PBField.initUInt32(0);
        public hd_video_comm$PstnAudioProto msg_audio_proto = new hd_video_comm$PstnAudioProto();
        public hd_video_comm$SipServerInfo sip_server = new MessageMicro<hd_video_comm$SipServerInfo>() { // from class: tencent.im.cs.longconn.hd_video_comm$SipServerInfo
            static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{10, 16, 26, 32, 40, 50, 56, 64}, new String[]{"msg_sip_addr", "uint32_provider_id", "msg_caller_phone", "uint32_encode_type", "uint32_tls_flag", "bytes_domain", "uint32_srtp_flag", "rpt_uint32_dtmf_mode"}, new Object[]{null, 0, null, 0, 0, ByteStringMicro.EMPTY, 0, 0}, hd_video_comm$SipServerInfo.class);
            public hd_video_comm$NetAddr msg_sip_addr = new hd_video_comm$NetAddr();
            public final PBUInt32Field uint32_provider_id = PBField.initUInt32(0);
            public hd_video_comm$PstnMobileInfo msg_caller_phone = new MessageMicro<hd_video_comm$PstnMobileInfo>() { // from class: tencent.im.cs.longconn.hd_video_comm$PstnMobileInfo
                static final MessageMicro.FieldMap __fieldMap__;
                public final PBBytesField bytes_mobile;
                public final PBBytesField bytes_nation;
                public final PBBytesField bytes_prefix;
                public final PBUInt32Field uint32_provider_id;

                static {
                    ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
                    __fieldMap__ = MessageMicro.initFieldMap(new int[]{10, 18, 26, 32}, new String[]{"bytes_nation", "bytes_prefix", "bytes_mobile", "uint32_provider_id"}, new Object[]{byteStringMicro, byteStringMicro, byteStringMicro, 0}, hd_video_comm$PstnMobileInfo.class);
                }

                {
                    ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
                    this.bytes_nation = PBField.initBytes(byteStringMicro);
                    this.bytes_prefix = PBField.initBytes(byteStringMicro);
                    this.bytes_mobile = PBField.initBytes(byteStringMicro);
                    this.uint32_provider_id = PBField.initUInt32(0);
                }
            };
            public final PBUInt32Field uint32_encode_type = PBField.initUInt32(0);
            public final PBUInt32Field uint32_tls_flag = PBField.initUInt32(0);
            public final PBBytesField bytes_domain = PBField.initBytes(ByteStringMicro.EMPTY);
            public final PBUInt32Field uint32_srtp_flag = PBField.initUInt32(0);
            public final PBRepeatField<Integer> rpt_uint32_dtmf_mode = PBField.initRepeat(PBUInt32Field.__repeatHelper__);
        };
        public hd_video_comm$PstnAudioProto msg_local_audio_proto = new hd_video_comm$PstnAudioProto();
        public final PBUInt32Field client_ip_stack = PBField.initUInt32(0);
    };
    public hd_video$CmdRefuseInviteReqBody msg_refuse_body = new MessageMicro<hd_video$CmdRefuseInviteReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdRefuseInviteReqBody
        static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16, 24, 32}, new String[]{"uint32_app_id", "enum_termtype", "uint32_refuse_reason", "uint32_voip_flag"}, new Object[]{0, 1, 0, 0}, hd_video$CmdRefuseInviteReqBody.class);
        public final PBUInt32Field uint32_app_id = PBField.initUInt32(0);
        public final PBEnumField enum_termtype = PBField.initEnum(1);
        public final PBUInt32Field uint32_refuse_reason = PBField.initUInt32(0);
        public final PBUInt32Field uint32_voip_flag = PBField.initUInt32(0);
    };
    public hd_video$CmdIgnoreInviteReqBody msg_ignore_body = new MessageMicro<hd_video$CmdIgnoreInviteReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdIgnoreInviteReqBody
        static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[0], new String[0], new Object[0], hd_video$CmdIgnoreInviteReqBody.class);
    };
    public hd_video$CmdLogoutReqBody msg_logout_body = new MessageMicro<hd_video$CmdLogoutReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdLogoutReqBody
        static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16}, new String[]{"uint32_logout_code", "uint32_voip_flag"}, new Object[]{0, 0}, hd_video$CmdLogoutReqBody.class);
        public final PBUInt32Field uint32_logout_code = PBField.initUInt32(0);
        public final PBUInt32Field uint32_voip_flag = PBField.initUInt32(0);
    };
    public hd_video$CmdQueryInfoReqBody msg_query_info_body = new MessageMicro<hd_video$CmdQueryInfoReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdQueryInfoReqBody
        static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 18, 24, 32, 40, 48, 56}, new String[]{"uint64_dial_no", "str_ticket", "enum_business_type", "uint64_business_id", "uint32_business_flag", "uint32_flag", "client_ip_stack"}, new Object[]{0L, "", 1, 0L, 0, 0, 0}, hd_video$CmdQueryInfoReqBody.class);
        public final PBUInt64Field uint64_dial_no = PBField.initUInt64(0);
        public final PBStringField str_ticket = PBField.initString("");
        public final PBEnumField enum_business_type = PBField.initEnum(1);
        public final PBUInt64Field uint64_business_id = PBField.initUInt64(0);
        public final PBUInt32Field uint32_business_flag = PBField.initUInt32(0);
        public final PBUInt32Field uint32_flag = PBField.initUInt32(0);
        public final PBUInt32Field client_ip_stack = PBField.initUInt32(0);
    };
    public hd_video$CmdSDKReportReqBody msg_sdk_stat_body = new MessageMicro<hd_video$CmdSDKReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdSDKReportReqBody
        static final MessageMicro.FieldMap __fieldMap__;
        public final PBBoolField bool_lt_stat_bind_qq;
        public final PBBytesField bytes_cpu_name;
        public final PBBytesField bytes_data_chn_ipv6;
        public final PBBytesField bytes_fingerprint;
        public final PBBytesField bytes_login_wan_ipv6;
        public final PBBytesField bytes_manufacturer;
        public final PBBytesField bytes_model;
        public final PBBytesField bytes_peer_punch_ipv6;
        public final PBBytesField bytes_product;
        public final PBBytesField bytes_sdkversion;
        public final PBBytesField bytes_self_punch_ipv6;
        public final PBBytesField bytes_signal_chn_ipv6;
        public final PBUInt32Field uint32_avaibw_initbr_scene_downflag;
        public final PBUInt32Field uint32_avg_cap_rnd_diff;
        public final PBUInt32Field uint32_avgjitter_lossrate_degree;
        public final PBUInt32Field uint32_capacityup;
        public final PBUInt32Field uint32_client_net_type;
        public final PBUInt32Field uint32_conti_lost0;
        public final PBUInt32Field uint32_conti_lost1;
        public final PBUInt32Field uint32_cpu_score;
        public final PBUInt32Field uint32_device_sw_cnt;
        public final PBUInt32Field uint32_echo_leak_ms;
        public final PBUInt32Field uint32_enabled_hw_dec_mjpg;
        public final PBUInt32Field uint32_eva_qp_enable;
        public final PBUInt32Field uint32_fec_percent;
        public final PBUInt32Field uint32_frm_fec_percent;
        public final PBUInt32Field uint32_hw_720P_time;
        public final PBUInt32Field uint32_hw_decTime;
        public final PBUInt32Field uint32_hw_dec_error;
        public final PBUInt32Field uint32_hw_dec_mjpg_err;
        public final PBUInt32Field uint32_hw_enc_error;
        public final PBUInt32Field uint32_hw_ratedistortion;
        public final PBUInt32Field uint32_hw_vag_time;
        public final PBUInt32Field uint32_idrfrmnum_all;
        public final PBUInt32Field uint32_lost_num;
        public final PBUInt32Field uint32_lost_peak_time;
        public final PBUInt32Field uint32_lt_chat_type;
        public final PBUInt32Field uint32_max_minbr_aboveratio;
        public final PBUInt32Field uint32_pkgsize_lost_fail;
        public final PBUInt32Field uint32_punch_predict;
        public final PBUInt32Field uint32_wave_bitrate;
        public final PBUInt64Field uint64_aec_delay_distributing;
        public final PBUInt64Field uint64_avgcpurate_enc;
        public final PBUInt64Field uint64_avgfps_enc;
        public final PBUInt64Field uint64_avgfps_sever;
        public final PBUInt64Field uint64_avgqp_enc;
        public final PBUInt64Field uint64_avgrate_enc;
        public final PBUInt64Field uint64_avgrate_sever;
        public final PBUInt64Field uint64_avgtruefps_enc;
        public final PBUInt64Field uint64_codectype_enc;
        public final PBUInt64Field uint64_idravgqp_enc;
        public final PBUInt64Field uint64_idrfrmrate_enc;
        public final PBUInt64Field uint64_p2c_audio_loss_rate;
        public final PBUInt64Field uint64_p2c_video_loss_rate;
        public final PBUInt64Field uint64_quality1_enc;
        public final PBUInt64Field uint64_quality_enc;
        public final PBUInt64Field uint64_relay_audio_loss_rate;
        public final PBUInt64Field uint64_relay_video_loss_rate;
        public final PBUInt64Field uint64_video_quality;
        public final PBUInt64Field uint64_whole_audio_loss_rate;
        public final PBUInt64Field uint64_whole_video_loss_rate;
        public final PBFixed32Field fixed32_login_wan_ip = PBField.initFixed32(0);
        public final PBUInt32Field uint32_net_type = PBField.initUInt32(0);
        public final PBStringField str_device_name = PBField.initString("");
        public final PBUInt64Field uint64_roomid = PBField.initUInt64(0);
        public final PBUInt32Field uint32_business_type = PBField.initUInt32(0);
        public final PBUInt32Field uint32_business_flag = PBField.initUInt32(0);
        public final PBUInt64Field uint64_self_uin = PBField.initUInt64(0);
        public final PBUInt64Field uint64_peer_uin = PBField.initUInt64(0);
        public final PBUInt32Field uint32_self_version = PBField.initUInt32(0);
        public final PBUInt32Field uint32_peer_version = PBField.initUInt32(0);
        public final PBUInt32Field uint32_self_type = PBField.initUInt32(0);
        public final PBUInt32Field uint32_peer_type = PBField.initUInt32(0);
        public final PBUInt32Field uint32_active = PBField.initUInt32(0);
        public final PBUInt32Field uint32_connected = PBField.initUInt32(0);
        public final PBUInt32Field uint32_end_result = PBField.initUInt32(0);
        public final PBUInt32Field uint32_connect_error_code = PBField.initUInt32(0);
        public final PBUInt32Field uint32_punch_code = PBField.initUInt32(0);
        public final PBFixed32Field fixed32_self_punch_ip = PBField.initFixed32(0);
        public final PBFixed32Field fixed32_peer_punch_ip = PBField.initFixed32(0);
        public final PBUInt32Field uint32_relayAndP2CScale = PBField.initUInt32(0);
        public final PBUInt32Field uint32_signal_chn_type = PBField.initUInt32(0);
        public final PBFixed32Field fixed32_signal_chn_ip = PBField.initFixed32(0);
        public final PBUInt32Field uint32_data_chn_type = PBField.initUInt32(0);
        public final PBFixed32Field fixed32_data_chn_ip = PBField.initFixed32(0);
        public final PBUInt32Field uint32_start_time = PBField.initUInt32(0);
        public final PBUInt32Field uint32_end_time = PBField.initUInt32(0);
        public final PBUInt32Field uint32_connected_time = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_video_recv_rate = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_video_send_rate = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_video_recv_fps = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_video_send_fps = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_video_recv_loss = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_video_send_loss = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_send_resolution = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_audio_recv_rate = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_audio_send_rate = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_audio_recv_loss = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_audio_send_loss = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_up_delay = PBField.initUInt64(0);
        public final PBUInt32Field uint32_avg_video_quality = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_audio_quality = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_video_recv_rate = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_video_send_rate = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_video_recv_fps = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_video_send_fps = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_video_recv_loss = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_video_send_loss = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_audio_recv_rate = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_audio_send_rate = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_audio_recv_loss = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_audio_send_loss = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_up_delay = PBField.initUInt32(0);
        public final PBStringField str_apn_name = PBField.initString("");
        public final PBUInt32Field uint32_use_arq_sacle = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_after_arq_loss_video = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_after_arq_loss_audio = PBField.initUInt32(0);
        public final PBUInt32Field uint32_avg_kalman_bandwith = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_after_arq_loss_video = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_after_arq_loss_audio = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_kalman_recv_rate = PBField.initUInt64(0);
        public final PBUInt32Field uint32_avg_audio_quality_ex = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_jitter_distributing = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_jitter_adapt_rate = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_jitter_plc_rate = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_jitter_loss_rate = PBField.initUInt64(0);
        public final PBUInt32Field uint32_avg_video_quality_ver1 = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_hwacc_state = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_agc_level = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_agc_pesv = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_agc_conf = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_agc_exp = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_fec_ok_rate = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_fec_use_rate = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_fec_loss_before = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_fec_loss_after = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_fec_cons_losscnt = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_fec_jitter_value = PBField.initUInt64(0);
        public final PBUInt32Field uint32_cp0_avg_vfe_score = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cp1_avg_vfe_score = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cp2_avg_vfe_score = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cp3_avg_vfe_score = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cp4_avg_vfe_score = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cp5_avg_vfe_score = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cp6_avg_vfe_score = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cp7_avg_vfe_score = PBField.initUInt32(0);
        public final PBUInt32Field uint32_ppd_enable = PBField.initUInt32(0);
        public final PBUInt32Field uint32_ppd_speed = PBField.initUInt32(0);
        public final PBUInt32Field uint32_ppd_init_bitrate = PBField.initUInt32(0);
        public final PBUInt32Field uint32_ppd_step_interval = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_aud_quality_low = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_vid_quality_low = PBField.initUInt64(0);
        public final PBUInt32Field uint32_call_type = PBField.initUInt32(0);
        public final PBUInt32Field uint32_from_app_id = PBField.initUInt32(0);
        public final PBUInt32Field uint32_app_type = PBField.initUInt32(0);
        public final PBUInt32Field uint32_chat_type = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_audio_quality = PBField.initUInt64(0);
        public final PBUInt64Field uint64_stat_video_quality = PBField.initUInt64(0);
        public final PBUInt32Field uint32_avg_audio_bandwith = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_audio_bandwith = PBField.initUInt64(0);
        public final PBUInt32Field uint32_avg_audio_jitter = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_audio_jitter = PBField.initUInt64(0);
        public final PBUInt32Field uint32_avg_video_jitter = PBField.initUInt32(0);
        public final PBUInt64Field uint64_stat_video_jitter = PBField.initUInt64(0);
        public final PBUInt32Field uint32_cpu_level = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cpu_clock = PBField.initUInt32(0);
        public final PBUInt64Field uint64_cpu_family = PBField.initUInt64(0);
        public final PBUInt32Field uint32_cpu_number = PBField.initUInt32(0);
        public final PBUInt64Field uint64_cpu_instructionset = PBField.initUInt64(0);
        public final PBUInt32Field uint32_cpu_l2_cache = PBField.initUInt32(0);
        public final PBUInt32Field uint32_cpu_l3_cache = PBField.initUInt32(0);

        static {
            ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
            __fieldMap__ = MessageMicro.initFieldMap(new int[]{13, 16, 26, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 149, 157, 160, 168, 181, 184, 197, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, FilterEnum.MIC_PTU_TRANS_XINXIAN, 288, 296, 304, 312, 320, AdReporterForEffect.ACTION_MOBILEAPP_QUICKAPP_OPEN_FAILURE, 336, a.CTRL_INDEX, g.CTRL_INDEX, 360, 368, 376, MsgConstant.KRMFILETHUMBSIZE384, QFSBottomDynamicGuideEvent.DYNAMIC_GUIDE_BUTTON_TYPE, 400, 408, 416, PlayUI.UIType.BIG_CARD_SHAPED_PIC, 432, 440, TroopInfo.PAY_PRIVILEGE_ALL, QFSNumberConstants.Int.NUM_456, 464, JsApiEnableDeviceOrientation.CTRL_INDEX, 480, 488, w.CTRL_INDEX, 504, 512, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_CGI_REQUEST, 528, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_REFRESH_PLAYER_WITH_REOPEN_START, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_QUICK_PLAY_WITH_OFFLINE_RESOURCE, 552, PlayerResources.ViewId.GET_MORE_TOGGLE_AREA, PlayerResources.ViewId.EXTENDED_VIEW_BTN_NORMAL_BUTTON, PlayerResources.ViewId.CANVAS_VIDEO_TOTAL_TRAFFIC_TEXT, 584, d.CTRL_INDEX, 600, 608, 616, 624, 632, 640, 648, 656, LpReportInfoConfig.ACTION_VIDEO_EDITOR, 672, 680, 688, 696, 704, TMAssistantDownloadErrorCode.DOWNLOAD_ERR_KNOWN_LENGTH_CHECK_ERROR, 720, 728, b.CTRL_INDEX, 744, e.P, 760, 768, 776, 784, l.CTRL_INDEX, 800, 808, 816, 824, 832, 840, TVKTPCapability.HD_WIDTH, 856, 864, 872, x.CTRL_INDEX, y.CTRL_INDEX, 896, 904, 912, 920, 928, 936, 944, 952, 962, 970, 978, 986, 994, 1000, 1008, 1016, 1024, 1032, 1040, 1048, 1056, DataTableNameType.TABLE_WRIST_TEMPERATURE_STAT, 1072, 1080, 1088, 1096, 1104, 1112, 1120, 1128, 1136, 1144, gdt_analysis_event.EVENT_GET_SYSTEM_CHROME_VERSION, gdt_analysis_event.EVENT_GET_MANUFACTURER, 1168, 1176, com.tencent.luggage.wxa.kf.a.CTRL_INDEX, QzoneCoverConst.MSG_COVER_INVALIDATE, 1200, 1208, LaunchParam.SCENE_ABOUT, gdt_analysis_event.EVENT_VIDEO_FIRST_FRAME_RENDERED, SubAccountBindActivity.ERROR_ACCOUNT_FREEDOM, SubAccountBindActivity.ERROR_ACCOUNT_LOGIN_FAILED, 1248, 1256, InitSkin.COLOR_COUNT, 1272, 1280, 1288, 1296, 1304, gdt_analysis_event.EVENT_MOTIVE_HIPPY_LOAD_HIPPY_FAILED, gdt_analysis_event.EVENT_FEEDBACK_CLICK, 1330, 1338, 1346, CardContainerDataServiceImpl.CARD_CONTAINER_POS_ID, 1360, 1368}, new String[]{"fixed32_login_wan_ip", "uint32_net_type", "str_device_name", "uint64_roomid", "uint32_business_type", "uint32_business_flag", "uint64_self_uin", "uint64_peer_uin", "uint32_self_version", "uint32_peer_version", "uint32_self_type", "uint32_peer_type", "uint32_active", "uint32_connected", "uint32_end_result", "uint32_connect_error_code", "uint32_punch_code", "fixed32_self_punch_ip", "fixed32_peer_punch_ip", "uint32_relayAndP2CScale", "uint32_signal_chn_type", "fixed32_signal_chn_ip", "uint32_data_chn_type", "fixed32_data_chn_ip", "uint32_start_time", "uint32_end_time", "uint32_connected_time", "uint64_stat_video_recv_rate", "uint64_stat_video_send_rate", "uint64_stat_video_recv_fps", "uint64_stat_video_send_fps", "uint64_stat_video_recv_loss", "uint64_stat_video_send_loss", "uint64_stat_send_resolution", "uint64_stat_audio_recv_rate", "uint64_stat_audio_send_rate", "uint64_stat_audio_recv_loss", "uint64_stat_audio_send_loss", "uint64_stat_up_delay", "uint32_avg_video_quality", "uint32_avg_audio_quality", "uint32_avg_video_recv_rate", "uint32_avg_video_send_rate", "uint32_avg_video_recv_fps", "uint32_avg_video_send_fps", "uint32_avg_video_recv_loss", "uint32_avg_video_send_loss", "uint32_avg_audio_recv_rate", "uint32_avg_audio_send_rate", "uint32_avg_audio_recv_loss", "uint32_avg_audio_send_loss", "uint32_avg_up_delay", "str_apn_name", "uint32_use_arq_sacle", "uint32_avg_after_arq_loss_video", "uint32_avg_after_arq_loss_audio", "uint32_avg_kalman_bandwith", "uint64_stat_after_arq_loss_video", "uint64_stat_after_arq_loss_audio", "uint64_stat_kalman_recv_rate", "uint32_avg_audio_quality_ex", "uint64_stat_jitter_distributing", "uint64_stat_jitter_adapt_rate", "uint64_stat_jitter_plc_rate", "uint64_stat_jitter_loss_rate", "uint32_avg_video_quality_ver1", "uint64_stat_agc_level", "uint64_stat_agc_pesv", "uint64_stat_agc_conf", "uint64_stat_hwacc_state", "uint64_stat_agc_exp", "uint64_stat_fec_ok_rate", "uint64_stat_fec_use_rate", "uint64_stat_fec_loss_before", "uint64_stat_fec_loss_after", "uint64_stat_fec_cons_losscnt", "uint64_stat_fec_jitter_value", "uint32_cp0_avg_vfe_score", "uint32_cp1_avg_vfe_score", "uint32_cp2_avg_vfe_score", "uint32_cp3_avg_vfe_score", "uint32_cp4_avg_vfe_score", "uint32_cp5_avg_vfe_score", "uint32_cp6_avg_vfe_score", "uint32_cp7_avg_vfe_score", "uint32_ppd_enable", "uint32_ppd_speed", "uint32_ppd_init_bitrate", "uint32_ppd_step_interval", "uint64_stat_aud_quality_low", "uint64_stat_vid_quality_low", "uint32_call_type", "uint32_from_app_id", "uint32_app_type", "uint32_chat_type", "uint64_stat_audio_quality", "uint64_stat_video_quality", "uint32_avg_audio_bandwith", "uint64_stat_audio_bandwith", "uint32_avg_audio_jitter", "uint64_stat_audio_jitter", "uint32_avg_video_jitter", "uint64_stat_video_jitter", "uint32_cpu_level", "uint32_cpu_clock", "uint64_cpu_family", "uint32_cpu_number", "uint64_cpu_instructionset", "uint32_cpu_l2_cache", "uint32_cpu_l3_cache", "bytes_cpu_name", "uint32_eva_qp_enable", "uint32_cpu_score", "uint32_hw_vag_time", "uint32_hw_720P_time", "uint32_hw_enc_error", "uint32_hw_ratedistortion", "uint32_hw_decTime", "uint32_hw_dec_error", "bytes_manufacturer", "bytes_product", "bytes_model", "bytes_fingerprint", "bytes_sdkversion", "uint32_lost_num", "uint32_conti_lost0", "uint32_conti_lost1", "uint32_lost_peak_time", "uint32_pkgsize_lost_fail", "uint32_fec_percent", "uint32_frm_fec_percent", "uint32_wave_bitrate", "uint64_whole_video_loss_rate", "uint64_whole_audio_loss_rate", "uint64_relay_video_loss_rate", "uint64_relay_audio_loss_rate", "uint64_p2c_video_loss_rate", "uint64_p2c_audio_loss_rate", "bool_lt_stat_bind_qq", "uint32_lt_chat_type", "uint32_idrfrmnum_all", "uint64_idrfrmrate_enc", "uint64_avgqp_enc", "uint64_idravgqp_enc", "uint64_quality_enc", "uint64_avgrate_enc", "uint64_avgrate_sever", "uint64_avgfps_sever", "uint64_avgfps_enc", "uint64_avgtruefps_enc", "uint64_avgcpurate_enc", "uint64_codectype_enc", "uint64_video_quality", "uint64_quality1_enc", "uint32_capacityup", "uint32_avaibw_initbr_scene_downflag", "uint32_avgjitter_lossrate_degree", "uint32_max_minbr_aboveratio", "uint32_punch_predict", "uint32_avg_cap_rnd_diff", "uint32_echo_leak_ms", "uint32_device_sw_cnt", "uint64_aec_delay_distributing", "bytes_login_wan_ipv6", "bytes_self_punch_ipv6", "bytes_peer_punch_ipv6", "bytes_signal_chn_ipv6", "bytes_data_chn_ipv6", "uint32_enabled_hw_dec_mjpg", "uint32_hw_dec_mjpg_err", "uint32_client_net_type"}, new Object[]{0, 0, "", 0L, 0, 0, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0L, 0L, 0L, 0, 0L, 0L, 0L, 0L, 0, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0L, 0L, 0, 0, 0, 0, 0L, 0L, 0, 0L, 0, 0L, 0, 0L, 0, 0, 0L, 0, 0L, 0, 0, byteStringMicro, 0, 0, 0, 0, 0, 0, 0, 0, byteStringMicro, byteStringMicro, byteStringMicro, byteStringMicro, byteStringMicro, 0, 0, 0, 0, 0, 0, 0, 0, 0L, 0L, 0L, 0L, 0L, 0L, Boolean.FALSE, 0, 0, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, 0, 0L, byteStringMicro, byteStringMicro, byteStringMicro, byteStringMicro, byteStringMicro, 0, 0, 0}, hd_video$CmdSDKReportReqBody.class);
        }

        {
            ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
            this.bytes_cpu_name = PBField.initBytes(byteStringMicro);
            this.uint32_eva_qp_enable = PBField.initUInt32(0);
            this.uint32_cpu_score = PBField.initUInt32(0);
            this.uint32_hw_vag_time = PBField.initUInt32(0);
            this.uint32_hw_720P_time = PBField.initUInt32(0);
            this.uint32_hw_enc_error = PBField.initUInt32(0);
            this.uint32_hw_ratedistortion = PBField.initUInt32(0);
            this.uint32_hw_decTime = PBField.initUInt32(0);
            this.uint32_hw_dec_error = PBField.initUInt32(0);
            this.bytes_manufacturer = PBField.initBytes(byteStringMicro);
            this.bytes_product = PBField.initBytes(byteStringMicro);
            this.bytes_model = PBField.initBytes(byteStringMicro);
            this.bytes_fingerprint = PBField.initBytes(byteStringMicro);
            this.bytes_sdkversion = PBField.initBytes(byteStringMicro);
            this.uint32_lost_num = PBField.initUInt32(0);
            this.uint32_conti_lost0 = PBField.initUInt32(0);
            this.uint32_conti_lost1 = PBField.initUInt32(0);
            this.uint32_lost_peak_time = PBField.initUInt32(0);
            this.uint32_pkgsize_lost_fail = PBField.initUInt32(0);
            this.uint32_fec_percent = PBField.initUInt32(0);
            this.uint32_frm_fec_percent = PBField.initUInt32(0);
            this.uint32_wave_bitrate = PBField.initUInt32(0);
            this.uint64_whole_video_loss_rate = PBField.initUInt64(0L);
            this.uint64_whole_audio_loss_rate = PBField.initUInt64(0L);
            this.uint64_relay_video_loss_rate = PBField.initUInt64(0L);
            this.uint64_relay_audio_loss_rate = PBField.initUInt64(0L);
            this.uint64_p2c_video_loss_rate = PBField.initUInt64(0L);
            this.uint64_p2c_audio_loss_rate = PBField.initUInt64(0L);
            this.bool_lt_stat_bind_qq = PBField.initBool(false);
            this.uint32_lt_chat_type = PBField.initUInt32(0);
            this.uint32_idrfrmnum_all = PBField.initUInt32(0);
            this.uint64_idrfrmrate_enc = PBField.initUInt64(0L);
            this.uint64_avgqp_enc = PBField.initUInt64(0L);
            this.uint64_idravgqp_enc = PBField.initUInt64(0L);
            this.uint64_quality_enc = PBField.initUInt64(0L);
            this.uint64_avgrate_enc = PBField.initUInt64(0L);
            this.uint64_avgrate_sever = PBField.initUInt64(0L);
            this.uint64_avgfps_sever = PBField.initUInt64(0L);
            this.uint64_avgfps_enc = PBField.initUInt64(0L);
            this.uint64_avgtruefps_enc = PBField.initUInt64(0L);
            this.uint64_avgcpurate_enc = PBField.initUInt64(0L);
            this.uint64_codectype_enc = PBField.initUInt64(0L);
            this.uint64_video_quality = PBField.initUInt64(0L);
            this.uint64_quality1_enc = PBField.initUInt64(0L);
            this.uint32_capacityup = PBField.initUInt32(0);
            this.uint32_avaibw_initbr_scene_downflag = PBField.initUInt32(0);
            this.uint32_avgjitter_lossrate_degree = PBField.initUInt32(0);
            this.uint32_max_minbr_aboveratio = PBField.initUInt32(0);
            this.uint32_punch_predict = PBField.initUInt32(0);
            this.uint32_avg_cap_rnd_diff = PBField.initUInt32(0);
            this.uint32_echo_leak_ms = PBField.initUInt32(0);
            this.uint32_device_sw_cnt = PBField.initUInt32(0);
            this.uint64_aec_delay_distributing = PBField.initUInt64(0L);
            this.bytes_login_wan_ipv6 = PBField.initBytes(byteStringMicro);
            this.bytes_self_punch_ipv6 = PBField.initBytes(byteStringMicro);
            this.bytes_peer_punch_ipv6 = PBField.initBytes(byteStringMicro);
            this.bytes_signal_chn_ipv6 = PBField.initBytes(byteStringMicro);
            this.bytes_data_chn_ipv6 = PBField.initBytes(byteStringMicro);
            this.uint32_enabled_hw_dec_mjpg = PBField.initUInt32(0);
            this.uint32_hw_dec_mjpg_err = PBField.initUInt32(0);
            this.uint32_client_net_type = PBField.initUInt32(0);
        }
    };
    public hd_video$CmdUpdateInviteReqBody msg_update_body = new MessageMicro<hd_video$CmdUpdateInviteReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdUpdateInviteReqBody
        static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 18, 26, 34}, new String[]{"uint32_app_id", "rpt_msg_update_media_addr_list", "msg_audio_proto", "msg_local_audio_proto"}, new Object[]{0, null, null, null}, hd_video$CmdUpdateInviteReqBody.class);
        public final PBUInt32Field uint32_app_id = PBField.initUInt32(0);
        public final PBRepeatMessageField<hd_video_comm$NetAddr> rpt_msg_update_media_addr_list = PBField.initRepeatMessage(hd_video_comm$NetAddr.class);
        public hd_video_comm$PstnAudioProto msg_audio_proto = new hd_video_comm$PstnAudioProto();
        public hd_video_comm$PstnAudioProto msg_local_audio_proto = new hd_video_comm$PstnAudioProto();
    };
    public hd_video$CmdSdkInfoReportReqBody msg_sdk_info_body = new MessageMicro<hd_video$CmdSdkInfoReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdSdkInfoReportReqBody
        static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{10, 18, 26, 34, 42}, new String[]{"msg_sdk_av_info_body", "msg_sdk_net_info_body", "msg_audio_info_body", "msg_video_info_body", "msg_local_flow_ctrl_info_body"}, new Object[]{null, null, null, null, null}, hd_video$CmdSdkInfoReportReqBody.class);
        public hd_video$CmdSdkAvInfoReportReqBody msg_sdk_av_info_body = new MessageMicro<hd_video$CmdSdkAvInfoReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdSdkAvInfoReportReqBody
            static final MessageMicro.FieldMap __fieldMap__;
            public final PBBoolField bool_lt_stat_bind_qq;
            public final PBBytesField bytes_cpu_name;
            public final PBBytesField bytes_hardware_chip_name;
            public final PBBytesField bytes_login_wan_ipv6;
            public final PBUInt64Field multipath_abtest_exp_id;
            public final PBStringField str_peer_uid;
            public final PBStringField str_qq_full_version;
            public final PBStringField str_self_uid;
            public final PBUInt32Field uint32_ai_predict_model_id;
            public final PBUInt32Field uint32_avg_pss;
            public final PBUInt32Field uint32_c2c_chat_type;
            public final PBUInt32Field uint32_cpu_score;
            public final PBUInt32Field uint32_hw_ability;
            public final PBUInt32Field uint32_loss_qos_packet_count;
            public final PBUInt32Field uint32_lt_chat_type;
            public final PBUInt32Field uint32_max_pss;
            public final PBUInt32Field uint32_min_pss;
            public final PBUInt32Field uint32_real_qos_packet_count;
            public final PBUInt32Field uint32_total_ram;
            public final PBUInt64Field uint64_local_abtest_exp_reserve1;
            public final PBUInt64Field uint64_local_abtest_exp_reserve2;
            public final PBUInt64Field uint64_max_qos_seq;
            public final PBUInt64Field uint64_peer_abtest_exp_reserve1;
            public final PBUInt64Field uint64_peer_abtest_exp_reserve2;
            public final PBFixed32Field fixed32_login_wan_ip = PBField.initFixed32(0);
            public final PBUInt32Field uint32_net_type = PBField.initUInt32(0);
            public final PBStringField str_device_name = PBField.initString("");
            public final PBUInt64Field uint64_roomid = PBField.initUInt64(0);
            public final PBUInt32Field uint32_business_type = PBField.initUInt32(0);
            public final PBUInt32Field uint32_business_flag = PBField.initUInt32(0);
            public final PBUInt64Field uint64_self_uin = PBField.initUInt64(0);
            public final PBUInt64Field uint64_peer_uin = PBField.initUInt64(0);
            public final PBUInt32Field uint32_self_version = PBField.initUInt32(0);
            public final PBUInt32Field uint32_peer_version = PBField.initUInt32(0);
            public final PBUInt32Field uint32_self_type = PBField.initUInt32(0);
            public final PBUInt32Field uint32_peer_type = PBField.initUInt32(0);
            public final PBUInt32Field uint32_active = PBField.initUInt32(0);
            public final PBUInt32Field uint32_connected = PBField.initUInt32(0);
            public final PBUInt32Field uint32_end_result = PBField.initUInt32(0);
            public final PBUInt32Field uint32_connect_error_code = PBField.initUInt32(0);
            public final PBUInt32Field uint32_start_time = PBField.initUInt32(0);
            public final PBUInt32Field uint32_end_time = PBField.initUInt32(0);
            public final PBUInt32Field uint32_connected_time = PBField.initUInt32(0);
            public final PBUInt32Field uint32_call_type = PBField.initUInt32(0);
            public final PBUInt32Field uint32_from_app_id = PBField.initUInt32(0);
            public final PBUInt32Field uint32_app_type = PBField.initUInt32(0);
            public final PBUInt32Field uint32_chat_type = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cpu_level = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cpu_clock = PBField.initUInt32(0);
            public final PBUInt64Field uint64_cpu_family = PBField.initUInt64(0);
            public final PBUInt32Field uint32_cpu_number = PBField.initUInt32(0);
            public final PBUInt64Field uint64_cpu_instructionset = PBField.initUInt64(0);
            public final PBUInt32Field uint32_cpu_l2_cache = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cpu_l3_cache = PBField.initUInt32(0);

            static {
                ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
                __fieldMap__ = MessageMicro.initFieldMap(new int[]{13, 16, 26, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 250, 256, 264, 272, FilterEnum.MIC_PTU_BAIXI, 290, 296, 304, 312, 320, AdReporterForEffect.ACTION_MOBILEAPP_QUICKAPP_OPEN_FAILURE, 336, a.CTRL_INDEX, g.CTRL_INDEX, 362, 368, 376, MsgConstant.KRMFILETHUMBSIZE384, QFSBottomDynamicGuideEvent.DYNAMIC_GUIDE_BUTTON_TYPE, 400, 410, 418, 424, 432}, new String[]{"fixed32_login_wan_ip", "uint32_net_type", "str_device_name", "uint64_roomid", "uint32_business_type", "uint32_business_flag", "uint64_self_uin", "uint64_peer_uin", "uint32_self_version", "uint32_peer_version", "uint32_self_type", "uint32_peer_type", "uint32_active", "uint32_connected", "uint32_end_result", "uint32_connect_error_code", "uint32_start_time", "uint32_end_time", "uint32_connected_time", "uint32_call_type", "uint32_from_app_id", "uint32_app_type", "uint32_chat_type", "uint32_cpu_level", "uint32_cpu_clock", "uint64_cpu_family", "uint32_cpu_number", "uint64_cpu_instructionset", "uint32_cpu_l2_cache", "uint32_cpu_l3_cache", "bytes_cpu_name", "uint32_cpu_score", "bool_lt_stat_bind_qq", "uint32_lt_chat_type", "bytes_login_wan_ipv6", "str_qq_full_version", "uint32_loss_qos_packet_count", "uint32_real_qos_packet_count", "uint64_max_qos_seq", "uint32_total_ram", "uint32_max_pss", "uint32_min_pss", "uint32_avg_pss", "uint32_c2c_chat_type", "bytes_hardware_chip_name", "uint32_hw_ability", "uint64_local_abtest_exp_reserve1", "uint64_local_abtest_exp_reserve2", "uint64_peer_abtest_exp_reserve1", "uint64_peer_abtest_exp_reserve2", "str_self_uid", "str_peer_uid", "multipath_abtest_exp_id", "uint32_ai_predict_model_id"}, new Object[]{0, 0, "", 0L, 0, 0, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0L, 0, 0L, 0, 0, byteStringMicro, 0, Boolean.FALSE, 0, byteStringMicro, "", 0, 0, 0L, 0, 0, 0, 0, 0, byteStringMicro, 0, 0L, 0L, 0L, 0L, "", "", 0L, 0}, hd_video$CmdSdkAvInfoReportReqBody.class);
            }

            {
                ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
                this.bytes_cpu_name = PBField.initBytes(byteStringMicro);
                this.uint32_cpu_score = PBField.initUInt32(0);
                this.bool_lt_stat_bind_qq = PBField.initBool(false);
                this.uint32_lt_chat_type = PBField.initUInt32(0);
                this.bytes_login_wan_ipv6 = PBField.initBytes(byteStringMicro);
                this.str_qq_full_version = PBField.initString("");
                this.uint32_loss_qos_packet_count = PBField.initUInt32(0);
                this.uint32_real_qos_packet_count = PBField.initUInt32(0);
                this.uint64_max_qos_seq = PBField.initUInt64(0L);
                this.uint32_total_ram = PBField.initUInt32(0);
                this.uint32_max_pss = PBField.initUInt32(0);
                this.uint32_min_pss = PBField.initUInt32(0);
                this.uint32_avg_pss = PBField.initUInt32(0);
                this.uint32_c2c_chat_type = PBField.initUInt32(0);
                this.bytes_hardware_chip_name = PBField.initBytes(byteStringMicro);
                this.uint32_hw_ability = PBField.initUInt32(0);
                this.uint64_local_abtest_exp_reserve1 = PBField.initUInt64(0L);
                this.uint64_local_abtest_exp_reserve2 = PBField.initUInt64(0L);
                this.uint64_peer_abtest_exp_reserve1 = PBField.initUInt64(0L);
                this.uint64_peer_abtest_exp_reserve2 = PBField.initUInt64(0L);
                this.str_self_uid = PBField.initString("");
                this.str_peer_uid = PBField.initString("");
                this.multipath_abtest_exp_id = PBField.initUInt64(0L);
                this.uint32_ai_predict_model_id = PBField.initUInt32(0);
            }
        };
        public hd_video$CmdSdkNetInfoReportReqBody msg_sdk_net_info_body = new MessageMicro<hd_video$CmdSdkNetInfoReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdSdkNetInfoReportReqBody
            static final MessageMicro.FieldMap __fieldMap__;
            public final PBBytesField bytes_data_chn_ipv6;
            public final PBBytesField bytes_peer_punch_ipv6;
            public final PBBytesField bytes_self_punch_ipv6;
            public final PBBytesField bytes_signal_chn_ipv6;
            public final PBUInt32Field cellular1_ip_stack_type;
            public final PBUInt32Field nic_state_at_the_beginning;
            public final PBUInt32Field nic_state_at_the_end;
            public final PBUInt32Field only_cellular1_enabled_total_seconds;
            public final PBUInt32Field only_wifi1_enabled_total_seconds;
            public final PBUInt32Field uint32_client_net_type;
            public final PBUInt32Field uint32_normal_net_num;
            public final PBUInt32Field uint32_pkg_pacer_avg_time_cost;
            public final PBUInt32Field uint32_pkg_recv_loss_count;
            public final PBUInt32Field uint32_pkg_send_loss_count;
            public final PBUInt32Field uint32_ptcapacitydetect_lowlevel_recover;
            public final PBUInt32Field uint32_ptcapacitydetect_lowlevel_recover_time;
            public final PBUInt32Field uint32_try_connect_times;
            public final PBUInt32Field uint32_use_itf_idx;
            public final PBUInt32Field uint32_use_ptcapacity_flag;
            public final PBUInt32Field uint32_weak_net_level;
            public final PBUInt32Field uint32_weak_net_level1_num;
            public final PBUInt32Field uint32_weak_net_level2_num;
            public final PBUInt32Field uint32_weak_net_level3_num;
            public final PBUInt32Field wifi1_cellular1_enabled_total_seconds;
            public final PBUInt32Field wifi1_ip_stack_type;
            public final PBUInt32Field uint32_punch_code = PBField.initUInt32(0);
            public final PBFixed32Field fixed32_self_punch_ip = PBField.initFixed32(0);
            public final PBFixed32Field fixed32_peer_punch_ip = PBField.initFixed32(0);
            public final PBUInt32Field uint32_relayAndP2CScale = PBField.initUInt32(0);
            public final PBUInt32Field uint32_signal_chn_type = PBField.initUInt32(0);
            public final PBFixed32Field fixed32_signal_chn_ip = PBField.initFixed32(0);
            public final PBUInt32Field uint32_data_chn_type = PBField.initUInt32(0);
            public final PBFixed32Field fixed32_data_chn_ip = PBField.initFixed32(0);
            public final PBUInt64Field uint64_stat_up_delay = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_video_quality = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_audio_quality = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_up_delay = PBField.initUInt32(0);
            public final PBStringField str_apn_name = PBField.initString("");
            public final PBUInt32Field uint32_use_arq_sacle = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_after_arq_loss_video = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_after_arq_loss_audio = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_kalman_bandwith = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_after_arq_loss_video = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_after_arq_loss_audio = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_kalman_recv_rate = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_audio_quality_ex = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_video_quality_ver1 = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_hwacc_state = PBField.initUInt64(0);
            public final PBUInt32Field uint32_ppd_enable = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ppd_speed = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ppd_init_bitrate = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ppd_step_interval = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_aud_quality_low = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_vid_quality_low = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_quality = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_video_quality = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_audio_bandwith = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_audio_bandwith = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_audio_jitter = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_audio_jitter = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_video_jitter = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_video_jitter = PBField.initUInt64(0);
            public final PBUInt64Field uint64_whole_video_loss_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_whole_audio_loss_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_relay_video_loss_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_relay_audio_loss_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_p2c_video_loss_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_p2c_audio_loss_rate = PBField.initUInt64(0);
            public final PBUInt32Field uint32_punch_predict = PBField.initUInt32(0);
            public final PBUInt32Field uint32_capacityup = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avaibw_initbr_scene_downflag = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avgjitter_lossrate_degree = PBField.initUInt32(0);
            public final PBUInt32Field uint32_max_minbr_aboveratio = PBField.initUInt32(0);
            public final PBUInt32Field uint32_net_getin_time_cost = PBField.initUInt32(0);

            static {
                ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
                __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 21, 29, 32, 40, 53, 56, 69, 72, 80, 88, 96, 106, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, FilterEnum.MIC_PTU_TRANS_XINXIAN, 288, 296, 304, 312, 320, AdReporterForEffect.ACTION_MOBILEAPP_QUICKAPP_OPEN_FAILURE, 336, a.CTRL_INDEX, g.CTRL_INDEX, 360, 368, 376, MsgConstant.KRMFILETHUMBSIZE384, QFSBottomDynamicGuideEvent.DYNAMIC_GUIDE_BUTTON_TYPE, 402, 410, 418, PlayUI.UIType.BIG_CARD_SHAPED_PIC, 432, 440, TroopInfo.PAY_PRIVILEGE_ALL, QFSNumberConstants.Int.NUM_456, 464, JsApiEnableDeviceOrientation.CTRL_INDEX, 480, 488, w.CTRL_INDEX, 504, 512, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_CGI_REQUEST, 528, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_REFRESH_PLAYER_WITH_REOPEN_START, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_QUICK_PLAY_WITH_OFFLINE_RESOURCE, 552, PlayerResources.ViewId.GET_MORE_TOGGLE_AREA, PlayerResources.ViewId.EXTENDED_VIEW_BTN_NORMAL_BUTTON, PlayerResources.ViewId.CANVAS_VIDEO_TOTAL_TRAFFIC_TEXT, 584, d.CTRL_INDEX}, new String[]{"uint32_punch_code", "fixed32_self_punch_ip", "fixed32_peer_punch_ip", "uint32_relayAndP2CScale", "uint32_signal_chn_type", "fixed32_signal_chn_ip", "uint32_data_chn_type", "fixed32_data_chn_ip", "uint64_stat_up_delay", "uint32_avg_video_quality", "uint32_avg_audio_quality", "uint32_avg_up_delay", "str_apn_name", "uint32_use_arq_sacle", "uint32_avg_after_arq_loss_video", "uint32_avg_after_arq_loss_audio", "uint32_avg_kalman_bandwith", "uint64_stat_after_arq_loss_video", "uint64_stat_after_arq_loss_audio", "uint64_stat_kalman_recv_rate", "uint32_avg_audio_quality_ex", "uint32_avg_video_quality_ver1", "uint64_stat_hwacc_state", "uint32_ppd_enable", "uint32_ppd_speed", "uint32_ppd_init_bitrate", "uint32_ppd_step_interval", "uint64_stat_aud_quality_low", "uint64_stat_vid_quality_low", "uint64_stat_audio_quality", "uint64_stat_video_quality", "uint32_avg_audio_bandwith", "uint64_stat_audio_bandwith", "uint32_avg_audio_jitter", "uint64_stat_audio_jitter", "uint32_avg_video_jitter", "uint64_stat_video_jitter", "uint64_whole_video_loss_rate", "uint64_whole_audio_loss_rate", "uint64_relay_video_loss_rate", "uint64_relay_audio_loss_rate", "uint64_p2c_video_loss_rate", "uint64_p2c_audio_loss_rate", "uint32_punch_predict", "uint32_capacityup", "uint32_avaibw_initbr_scene_downflag", "uint32_avgjitter_lossrate_degree", "uint32_max_minbr_aboveratio", "uint32_net_getin_time_cost", "bytes_self_punch_ipv6", "bytes_peer_punch_ipv6", "bytes_signal_chn_ipv6", "bytes_data_chn_ipv6", "uint32_ptcapacitydetect_lowlevel_recover", "uint32_try_connect_times", "uint32_use_itf_idx", "uint32_use_ptcapacity_flag", "uint32_pkg_send_loss_count", "uint32_pkg_recv_loss_count", "uint32_pkg_pacer_avg_time_cost", "uint32_ptcapacitydetect_lowlevel_recover_time", "uint32_client_net_type", "nic_state_at_the_beginning", "nic_state_at_the_end", "only_wifi1_enabled_total_seconds", "only_cellular1_enabled_total_seconds", "wifi1_cellular1_enabled_total_seconds", "uint32_weak_net_level", "wifi1_ip_stack_type", "cellular1_ip_stack_type", "uint32_normal_net_num", "uint32_weak_net_level1_num", "uint32_weak_net_level2_num", "uint32_weak_net_level3_num"}, new Object[]{0, 0, 0, 0, 0, 0, 0, 0, 0L, 0, 0, 0, "", 0, 0, 0, 0, 0L, 0L, 0L, 0, 0, 0L, 0, 0, 0, 0, 0L, 0L, 0L, 0L, 0, 0L, 0, 0L, 0, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0, byteStringMicro, byteStringMicro, byteStringMicro, byteStringMicro, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, hd_video$CmdSdkNetInfoReportReqBody.class);
            }

            {
                ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
                this.bytes_self_punch_ipv6 = PBField.initBytes(byteStringMicro);
                this.bytes_peer_punch_ipv6 = PBField.initBytes(byteStringMicro);
                this.bytes_signal_chn_ipv6 = PBField.initBytes(byteStringMicro);
                this.bytes_data_chn_ipv6 = PBField.initBytes(byteStringMicro);
                this.uint32_ptcapacitydetect_lowlevel_recover = PBField.initUInt32(0);
                this.uint32_try_connect_times = PBField.initUInt32(0);
                this.uint32_use_itf_idx = PBField.initUInt32(0);
                this.uint32_use_ptcapacity_flag = PBField.initUInt32(0);
                this.uint32_pkg_send_loss_count = PBField.initUInt32(0);
                this.uint32_pkg_recv_loss_count = PBField.initUInt32(0);
                this.uint32_pkg_pacer_avg_time_cost = PBField.initUInt32(0);
                this.uint32_ptcapacitydetect_lowlevel_recover_time = PBField.initUInt32(0);
                this.uint32_client_net_type = PBField.initUInt32(0);
                this.nic_state_at_the_beginning = PBField.initUInt32(0);
                this.nic_state_at_the_end = PBField.initUInt32(0);
                this.only_wifi1_enabled_total_seconds = PBField.initUInt32(0);
                this.only_cellular1_enabled_total_seconds = PBField.initUInt32(0);
                this.wifi1_cellular1_enabled_total_seconds = PBField.initUInt32(0);
                this.uint32_weak_net_level = PBField.initUInt32(0);
                this.wifi1_ip_stack_type = PBField.initUInt32(0);
                this.cellular1_ip_stack_type = PBField.initUInt32(0);
                this.uint32_normal_net_num = PBField.initUInt32(0);
                this.uint32_weak_net_level1_num = PBField.initUInt32(0);
                this.uint32_weak_net_level2_num = PBField.initUInt32(0);
                this.uint32_weak_net_level3_num = PBField.initUInt32(0);
            }
        };
        public hd_video$CmdAudioInfoReportReqBody msg_audio_info_body = new MessageMicro<hd_video$CmdAudioInfoReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdAudioInfoReportReqBody
            static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, FilterEnum.MIC_PTU_TRANS_XINXIAN, 288, 296, 304, 312, 320, AdReporterForEffect.ACTION_MOBILEAPP_QUICKAPP_OPEN_FAILURE, 336, a.CTRL_INDEX, g.CTRL_INDEX, 360, 368, 376, MsgConstant.KRMFILETHUMBSIZE384, QFSBottomDynamicGuideEvent.DYNAMIC_GUIDE_BUTTON_TYPE, 400, 408, 416, 424, 432, 440, TroopInfo.PAY_PRIVILEGE_ALL, QFSNumberConstants.Int.NUM_456, 464, JsApiEnableDeviceOrientation.CTRL_INDEX, 480, 488, w.CTRL_INDEX, 504, 512, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_CGI_REQUEST, 528, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_REFRESH_PLAYER_WITH_REOPEN_START, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_QUICK_PLAY_WITH_OFFLINE_RESOURCE, 552, PlayerResources.ViewId.GET_MORE_TOGGLE_AREA, PlayerResources.ViewId.EXTENDED_VIEW_BTN_NORMAL_BUTTON, PlayerResources.ViewId.CANVAS_VIDEO_TOTAL_TRAFFIC_TEXT, 584, d.CTRL_INDEX, 600, 608, 616, 624, 632, 640, 648, 656, LpReportInfoConfig.ACTION_VIDEO_EDITOR, 672, 680, 688, 696, 704, 714, 720, 728, b.CTRL_INDEX, 744, e.P, 760, 768, 776, 784, l.CTRL_INDEX, 800, 808, 816, 824}, new String[]{"uint64_stat_audio_recv_rate", "uint64_stat_audio_send_rate", "uint64_stat_audio_recv_loss", "uint64_stat_audio_send_loss", "uint32_avg_audio_recv_rate", "uint32_avg_audio_send_rate", "uint32_avg_audio_recv_loss", "uint32_avg_audio_send_loss", "uint64_stat_jitter_distributing", "uint64_stat_jitter_adapt_rate", "uint64_stat_jitter_plc_rate", "uint64_stat_jitter_loss_rate", "uint64_stat_agc_level", "uint64_stat_agc_pesv", "uint64_stat_agc_conf", "uint64_stat_agc_exp", "uint64_stat_fec_ok_rate", "uint64_stat_fec_use_rate", "uint64_stat_fec_loss_before", "uint64_stat_fec_loss_after", "uint64_stat_fec_cons_losscnt", "uint64_stat_fec_jitter_value", "uint32_avg_cap_rnd_diff", "uint32_echo_leak_ms", "uint32_device_sw_cnt", "uint64_aec_delay_distributing", "uint64_audio_stat_bandwidth", "uint32_audio_avg_bandwidth", "uint32_audio_stat_netstatus", "uint32_max_cap_amplitude_value", "uint32_audio_first_frame_time_cost", "uint32_audio_big_lag_num", "uint32_audio_small_lag_num", "uint32_ec_soft_enabled", "uint32_ns_enabled", "uint32_ns_snr", "uint32_ns_echo_energy", "uint32_ns_noise_energy", "uint32_ns_echo_near_ratio", "uint32_agc_enabled", "uint32_agc_before_db", "uint32_agc_after_db", "uint32_agc_cliped_ratio", "uint32_vad_enabled", "uint32_vad_used_ratio", "uint32_cng_enabled", "uint32_cng_used_ratio", "uint32_indevMeterVal", "uint32_audio_session_mode", "uint32_audio_session_category", "uint32_audio_session_category_option", "uint32_audio_unit_type", "uint32_audio_unit_iobuffer", "uint64_audio_session_errorcode", "uint64_audio_unit_errorcode", "uint64_media_server_errorcode", "uint64_errCode", "uint32_mode", "uint32_audioSource", "uint32_streamType", "uint32_device_initializing_time", "uint32_device_starting_time", "uint32_device_total_time", "uint64_network_stat_signalstrength", "uint64_network_stat_pingvalue", "uint32_IsVirtualMachine", "uint32_CapErrorCode", "uint32_RndErrorCode", "uint32_ai_denoise_mode", "uint32_support_ai_denoise", "uint64_stat_audio_estimated_jitter", "uint64_stat_audio_buffer", "uint32_avg_audio_buffer", "uint32_audio_codec_type", "uint64_stat_audio_enc_core_br", "uint32_stat_audio_inband_fec_level", "uint64_stat_audio_inband_fec_lossrate", "uint64_stat_audio_outband_fec_m", "uint64_stat_audio_lossrate_before_dec", "uint64_stat_audio_lossrate_after_dec", "uint32_avg_audio_burst_len_before_dec", "uint32_avg_audio_interburst_len_before_dec", "uint32_avg_audio_lossrate_before_dec", "uint32_avg_audio_rand_lossrate_before_dec", "uint64_stat_audio_sending_end_time", "uint64_stat_audio_jitter_delay_time", "uint64_stat_audio_total_time", "uint32_avg_audio_total_time", "str_net_eq_version", "uint64_speech_continuous_loss_cnt_dist_before_fec", "uint64_speech_continuous_loss_cnt_dist_after_fec", "uint64_audio_continuous_loss_cnt_dist_before_dec", "uint64_audio_continuous_loss_cnt_dist_after_dec", "uint64_dec_loss_cnt_dist_and_dec_continuous_plc_cnt_dist", "uint64_apb_plc_cnt_dist_and_apb_continuous_plc_cnt_dist", "uint64_play_acc_factor_dist_and_play_dec_factor_dist", "uint64_big_brk_branch_dist_and_small_brk_branch_dist", "send_duplicate_pkgs_total_seconds", "avg_audio_quality_based_on_vad_break", "send_bytes_by_redundant_paths", "recv_bytes_by_redundant_paths", "send_bytes_by_redundant_paths_using_cellular", "recv_bytes_by_redundant_paths_using_cellular"}, new Object[]{0L, 0L, 0L, 0L, 0, 0, 0, 0, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0, 0, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0, 0L, 0L, 0, 0, 0, 0, 0, 0L, 0L, 0, 0, 0L, 0, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0L, 0L, 0L, 0L, "", 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0}, hd_video$CmdAudioInfoReportReqBody.class);
            public final PBUInt64Field uint64_stat_audio_recv_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_send_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_recv_loss = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_send_loss = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_audio_recv_rate = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_audio_send_rate = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_audio_recv_loss = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_audio_send_loss = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_jitter_distributing = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_jitter_adapt_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_jitter_plc_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_jitter_loss_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_agc_level = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_agc_pesv = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_agc_conf = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_agc_exp = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_fec_ok_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_fec_use_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_fec_loss_before = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_fec_loss_after = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_fec_cons_losscnt = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_fec_jitter_value = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_cap_rnd_diff = PBField.initUInt32(0);
            public final PBUInt32Field uint32_echo_leak_ms = PBField.initUInt32(0);
            public final PBUInt32Field uint32_device_sw_cnt = PBField.initUInt32(0);
            public final PBUInt64Field uint64_aec_delay_distributing = PBField.initUInt64(0);
            public final PBUInt64Field uint64_audio_stat_bandwidth = PBField.initUInt64(0);
            public final PBUInt32Field uint32_audio_avg_bandwidth = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_stat_netstatus = PBField.initUInt32(0);
            public final PBUInt32Field uint32_max_cap_amplitude_value = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_first_frame_time_cost = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_big_lag_num = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_small_lag_num = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ec_soft_enabled = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ns_enabled = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ns_snr = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ns_echo_energy = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ns_noise_energy = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ns_echo_near_ratio = PBField.initUInt32(0);
            public final PBUInt32Field uint32_agc_enabled = PBField.initUInt32(0);
            public final PBUInt32Field uint32_agc_before_db = PBField.initUInt32(0);
            public final PBUInt32Field uint32_agc_after_db = PBField.initUInt32(0);
            public final PBUInt32Field uint32_agc_cliped_ratio = PBField.initUInt32(0);
            public final PBUInt32Field uint32_vad_enabled = PBField.initUInt32(0);
            public final PBUInt32Field uint32_vad_used_ratio = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cng_enabled = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cng_used_ratio = PBField.initUInt32(0);
            public final PBUInt32Field uint32_indevMeterVal = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_session_mode = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_session_category = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_session_category_option = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_unit_type = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_unit_iobuffer = PBField.initUInt32(0);
            public final PBUInt64Field uint64_audio_session_errorcode = PBField.initUInt64(0);
            public final PBUInt64Field uint64_audio_unit_errorcode = PBField.initUInt64(0);
            public final PBUInt64Field uint64_media_server_errorcode = PBField.initUInt64(0);
            public final PBUInt64Field uint64_errCode = PBField.initUInt64(0);
            public final PBUInt32Field uint32_mode = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audioSource = PBField.initUInt32(0);
            public final PBUInt32Field uint32_streamType = PBField.initUInt32(0);
            public final PBUInt32Field uint32_device_initializing_time = PBField.initUInt32(0);
            public final PBUInt32Field uint32_device_starting_time = PBField.initUInt32(0);
            public final PBUInt32Field uint32_device_total_time = PBField.initUInt32(0);
            public final PBUInt64Field uint64_network_stat_signalstrength = PBField.initUInt64(0);
            public final PBUInt64Field uint64_network_stat_pingvalue = PBField.initUInt64(0);
            public final PBUInt32Field uint32_IsVirtualMachine = PBField.initUInt32(0);
            public final PBUInt32Field uint32_CapErrorCode = PBField.initUInt32(0);
            public final PBUInt32Field uint32_RndErrorCode = PBField.initUInt32(0);
            public final PBUInt32Field uint32_ai_denoise_mode = PBField.initUInt32(0);
            public final PBUInt32Field uint32_support_ai_denoise = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_audio_estimated_jitter = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_buffer = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_audio_buffer = PBField.initUInt32(0);
            public final PBUInt32Field uint32_audio_codec_type = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_audio_enc_core_br = PBField.initUInt64(0);
            public final PBUInt32Field uint32_stat_audio_inband_fec_level = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_audio_inband_fec_lossrate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_outband_fec_m = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_lossrate_before_dec = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_lossrate_after_dec = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_audio_burst_len_before_dec = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_audio_interburst_len_before_dec = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_audio_lossrate_before_dec = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_audio_rand_lossrate_before_dec = PBField.initUInt32(0);
            public final PBUInt64Field uint64_stat_audio_sending_end_time = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_jitter_delay_time = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_audio_total_time = PBField.initUInt64(0);
            public final PBUInt64Field uint32_avg_audio_total_time = PBField.initUInt64(0);
            public final PBStringField str_net_eq_version = PBField.initString("");
            public final PBUInt64Field uint64_speech_continuous_loss_cnt_dist_before_fec = PBField.initUInt64(0);
            public final PBUInt64Field uint64_speech_continuous_loss_cnt_dist_after_fec = PBField.initUInt64(0);
            public final PBUInt64Field uint64_audio_continuous_loss_cnt_dist_before_dec = PBField.initUInt64(0);
            public final PBUInt64Field uint64_audio_continuous_loss_cnt_dist_after_dec = PBField.initUInt64(0);
            public final PBUInt64Field uint64_dec_loss_cnt_dist_and_dec_continuous_plc_cnt_dist = PBField.initUInt64(0);
            public final PBUInt64Field uint64_apb_plc_cnt_dist_and_apb_continuous_plc_cnt_dist = PBField.initUInt64(0);
            public final PBUInt64Field uint64_play_acc_factor_dist_and_play_dec_factor_dist = PBField.initUInt64(0);
            public final PBUInt64Field uint64_big_brk_branch_dist_and_small_brk_branch_dist = PBField.initUInt64(0);
            public final PBUInt32Field send_duplicate_pkgs_total_seconds = PBField.initUInt32(0);
            public final PBUInt32Field avg_audio_quality_based_on_vad_break = PBField.initUInt32(0);
            public final PBUInt32Field send_bytes_by_redundant_paths = PBField.initUInt32(0);
            public final PBUInt32Field recv_bytes_by_redundant_paths = PBField.initUInt32(0);
            public final PBUInt32Field send_bytes_by_redundant_paths_using_cellular = PBField.initUInt32(0);
            public final PBUInt32Field recv_bytes_by_redundant_paths_using_cellular = PBField.initUInt32(0);
        };
        public hd_video$CmdVideoInfoReportReqBody msg_video_info_body = new MessageMicro<hd_video$CmdVideoInfoReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdVideoInfoReportReqBody
            static final MessageMicro.FieldMap __fieldMap__;
            public final PBBytesField bytes_fingerprint;
            public final PBBytesField bytes_manufacturer;
            public final PBBytesField bytes_model;
            public final PBBytesField bytes_product;
            public final PBBytesField bytes_sdkversion;
            public final PBStringField str_capture_fps_dist;
            public final PBUInt32Field uint32_avg_de_jitter;
            public final PBUInt32Field uint32_avg_fec_frame_time_diff;
            public final PBUInt32Field uint32_avg_jitter_delay;
            public final PBUInt32Field uint32_avg_out_frame_time_diff;
            public final PBUInt32Field uint32_avg_out_jitter;
            public final PBUInt32Field uint32_c2c_video_dec_total_time;
            public final PBUInt32Field uint32_c2c_video_enc_total_time;
            public final PBUInt32Field uint32_conti_lost0;
            public final PBUInt32Field uint32_conti_lost1;
            public final PBUInt32Field uint32_enable_aadsdejitter_max_jdelay;
            public final PBUInt32Field uint32_fec_percent;
            public final PBUInt32Field uint32_frame_freeze_rate;
            public final PBUInt32Field uint32_frm_fec_percent;
            public final PBUInt32Field uint32_high_sharpness_info;
            public final PBUInt32Field uint32_hw_1080P_time;
            public final PBUInt32Field uint32_idrfrmnum_all;
            public final PBUInt32Field uint32_lost_num;
            public final PBUInt32Field uint32_lost_peak_time;
            public final PBUInt32Field uint32_pkgsize_lost_fail;
            public final PBUInt32Field uint32_total_dec_frame_num;
            public final PBUInt32Field uint32_total_enc_frame_num;
            public final PBUInt32Field uint32_use_new_de_jitter_algorithm;
            public final PBUInt32Field uint32_video_break_time_rate;
            public final PBUInt32Field uint32_video_drop_num_per_minute;
            public final PBUInt32Field uint32_video_first_frame_time_cost;
            public final PBUInt32Field uint32_video_freeze_reason;
            public final PBUInt32Field uint32_video_jank_num_per_minute;
            public final PBUInt32Field uint32_video_jank_time_rate;
            public final PBUInt32Field uint32_video_lag_num;
            public final PBUInt32Field uint32_video_preprocess_type;
            public final PBUInt32Field uint32_video_process_lowlight_opentimes;
            public final PBUInt32Field uint32_video_process_lowlight_time;
            public final PBUInt32Field uint32_video_process_videodenoise_opentimes;
            public final PBUInt32Field uint32_video_process_videodenoise_time;
            public final PBUInt32Field uint32_video_super_resolution;
            public final PBUInt32Field uint32_wave_bitrate;
            public final PBUInt64Field uint64_avgcpurate_enc;
            public final PBUInt64Field uint64_avgfps_enc;
            public final PBUInt64Field uint64_avgfps_sever;
            public final PBUInt64Field uint64_avgqp_enc;
            public final PBUInt64Field uint64_avgrate_enc;
            public final PBUInt64Field uint64_avgrate_sever;
            public final PBUInt64Field uint64_avgtruefps_enc;
            public final PBUInt64Field uint64_codectype_dec;
            public final PBUInt64Field uint64_codectype_enc;
            public final PBUInt64Field uint64_de_jitter_dist;
            public final PBUInt64Field uint64_fec_frame_time_diff_dist;
            public final PBUInt64Field uint64_idravgqp_enc;
            public final PBUInt64Field uint64_idrfrmrate_enc;
            public final PBUInt64Field uint64_jitter_delay_dist;
            public final PBUInt64Field uint64_out_frame_time_diff_dist;
            public final PBUInt64Field uint64_out_jitter_dist;
            public final PBUInt64Field uint64_quality1_enc;
            public final PBUInt64Field uint64_quality_enc;
            public final PBUInt64Field uint64_stat_video_qp_dis;
            public final PBUInt64Field uint64_stat_video_qp_rate;
            public final PBUInt64Field uint64_stat_video_quality_rate;
            public final PBUInt64Field uint64_video_break_cnt;
            public final PBUInt64Field uint64_video_break_time_rates;
            public final PBUInt64Field uint64_video_decode_time;
            public final PBUInt64Field uint64_video_encode_time;
            public final PBUInt64Field uint64_video_jitter_time;
            public final PBUInt64Field uint64_video_preprocess_time;
            public final PBUInt64Field uint64_video_quality;
            public final PBUInt64Field uint64_video_render_time;
            public final PBUInt64Field uint64_video_rtt_time;
            public final PBUInt64Field uint64_video_svr_enc_rate;
            public final PBUInt64Field uint64_video_total_time;
            public final PBUInt64Field uint64_video_transport_time;
            public final PBUInt64Field uint64_stat_video_recv_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_video_send_rate = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_video_recv_fps = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_video_send_fps = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_video_recv_loss = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_video_send_loss = PBField.initUInt64(0);
            public final PBUInt64Field uint64_stat_send_resolution = PBField.initUInt64(0);
            public final PBUInt32Field uint32_avg_video_recv_rate = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_video_send_rate = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_video_recv_fps = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_video_send_fps = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_video_recv_loss = PBField.initUInt32(0);
            public final PBUInt32Field uint32_avg_video_send_loss = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cp0_avg_vfe_score = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cp1_avg_vfe_score = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cp2_avg_vfe_score = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cp3_avg_vfe_score = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cp4_avg_vfe_score = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cp5_avg_vfe_score = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cp6_avg_vfe_score = PBField.initUInt32(0);
            public final PBUInt32Field uint32_cp7_avg_vfe_score = PBField.initUInt32(0);
            public final PBUInt32Field uint32_eva_qp_enable = PBField.initUInt32(0);
            public final PBUInt32Field uint32_hw_vag_time = PBField.initUInt32(0);
            public final PBUInt32Field uint32_hw_720P_time = PBField.initUInt32(0);
            public final PBUInt32Field uint32_hw_enc_error = PBField.initUInt32(0);
            public final PBUInt32Field uint32_hw_ratedistortion = PBField.initUInt32(0);
            public final PBUInt32Field uint32_hw_decTime = PBField.initUInt32(0);
            public final PBUInt32Field uint32_hw_dec_error = PBField.initUInt32(0);

            static {
                ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
                __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 234, 242, 250, 258, 266, 272, FilterEnum.MIC_PTU_TRANS_XINXIAN, 288, 296, 304, 312, 320, AdReporterForEffect.ACTION_MOBILEAPP_QUICKAPP_OPEN_FAILURE, 336, a.CTRL_INDEX, g.CTRL_INDEX, 360, 368, 376, MsgConstant.KRMFILETHUMBSIZE384, QFSBottomDynamicGuideEvent.DYNAMIC_GUIDE_BUTTON_TYPE, 400, 408, 416, 424, 432, 440, TroopInfo.PAY_PRIVILEGE_ALL, QFSNumberConstants.Int.NUM_456, 464, JsApiEnableDeviceOrientation.CTRL_INDEX, 480, 488, w.CTRL_INDEX, 504, 512, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_CGI_REQUEST, 528, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_REFRESH_PLAYER_WITH_REOPEN_START, TVKQQLiveAssetPlayerMsg.PLAYER_INFO_QUICK_PLAY_WITH_OFFLINE_RESOURCE, 552, PlayerResources.ViewId.GET_MORE_TOGGLE_AREA, PlayerResources.ViewId.EXTENDED_VIEW_BTN_NORMAL_BUTTON, PlayerResources.ViewId.CANVAS_VIDEO_TOTAL_TRAFFIC_TEXT, 584, d.CTRL_INDEX, 600, 608, 616, 624, 632, 640, 648, 656, LpReportInfoConfig.ACTION_VIDEO_EDITOR, 672, 680, 688, 696, 704, TMAssistantDownloadErrorCode.DOWNLOAD_ERR_KNOWN_LENGTH_CHECK_ERROR, 720, 728, b.CTRL_INDEX, 744, e.P, 760, 768, 776, 784, n.CTRL_INDEX, 800, 808, 816, 824}, new String[]{"uint64_stat_video_recv_rate", "uint64_stat_video_send_rate", "uint64_stat_video_recv_fps", "uint64_stat_video_send_fps", "uint64_stat_video_recv_loss", "uint64_stat_video_send_loss", "uint64_stat_send_resolution", "uint32_avg_video_recv_rate", "uint32_avg_video_send_rate", "uint32_avg_video_recv_fps", "uint32_avg_video_send_fps", "uint32_avg_video_recv_loss", "uint32_avg_video_send_loss", "uint32_cp0_avg_vfe_score", "uint32_cp1_avg_vfe_score", "uint32_cp2_avg_vfe_score", "uint32_cp3_avg_vfe_score", "uint32_cp4_avg_vfe_score", "uint32_cp5_avg_vfe_score", "uint32_cp6_avg_vfe_score", "uint32_cp7_avg_vfe_score", "uint32_eva_qp_enable", "uint32_hw_vag_time", "uint32_hw_720P_time", "uint32_hw_enc_error", "uint32_hw_ratedistortion", "uint32_hw_decTime", "uint32_hw_dec_error", "bytes_manufacturer", "bytes_product", "bytes_model", "bytes_fingerprint", "bytes_sdkversion", "uint32_lost_num", "uint32_conti_lost0", "uint32_conti_lost1", "uint32_lost_peak_time", "uint32_pkgsize_lost_fail", "uint32_fec_percent", "uint32_frm_fec_percent", "uint32_wave_bitrate", "uint32_idrfrmnum_all", "uint64_idrfrmrate_enc", "uint64_avgqp_enc", "uint64_idravgqp_enc", "uint64_quality_enc", "uint64_avgrate_enc", "uint64_avgrate_sever", "uint64_avgfps_sever", "uint64_avgfps_enc", "uint64_avgtruefps_enc", "uint64_avgcpurate_enc", "uint64_codectype_enc", "uint64_video_quality", "uint64_quality1_enc", "uint32_video_first_frame_time_cost", "uint32_video_lag_num", "uint32_video_super_resolution", "uint32_video_process_lowlight_opentimes", "uint32_video_process_lowlight_time", "uint32_video_process_videodenoise_opentimes", "uint32_video_process_videodenoise_time", "uint64_video_preprocess_time", "uint64_video_encode_time", "uint64_video_transport_time", "uint64_video_decode_time", "uint64_video_render_time", "uint64_video_total_time", "uint32_video_preprocess_type", "uint64_video_rtt_time", "uint64_video_jitter_time", "uint64_video_break_cnt", "uint32_video_break_time_rate", "uint64_video_break_time_rates", "uint64_stat_video_qp_dis", "uint64_stat_video_qp_rate", "uint64_stat_video_quality_rate", "uint32_use_new_de_jitter_algorithm", "uint32_avg_de_jitter", "uint32_avg_jitter_delay", "uint32_high_sharpness_info", "uint64_video_svr_enc_rate", "uint64_de_jitter_dist", "uint32_avg_out_jitter", "uint64_out_jitter_dist", "uint32_avg_fec_frame_time_diff", "uint64_fec_frame_time_diff_dist", "uint32_avg_out_frame_time_diff", "uint64_out_frame_time_diff_dist", "uint64_jitter_delay_dist", "uint32_enable_aadsdejitter_max_jdelay", "uint64_codectype_dec", "uint32_hw_1080P_time", "uint32_video_jank_time_rate", "uint32_video_jank_num_per_minute", "uint32_video_drop_num_per_minute", "uint32_c2c_video_enc_total_time", "uint32_c2c_video_dec_total_time", "str_capture_fps_dist", "uint32_total_enc_frame_num", "uint32_total_dec_frame_num", "uint32_frame_freeze_rate", "uint32_video_freeze_reason"}, new Object[]{0L, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, byteStringMicro, byteStringMicro, byteStringMicro, byteStringMicro, byteStringMicro, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0, 0, 0, 0L, 0L, 0L, 0L, 0L, 0L, 0, 0L, 0L, 0L, 0, 0L, 0L, 0L, 0L, 0, 0, 0, 0, 0L, 0L, 0, 0L, 0, 0L, 0, 0L, 0L, 0, 0L, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0}, hd_video$CmdVideoInfoReportReqBody.class);
            }

            {
                ByteStringMicro byteStringMicro = ByteStringMicro.EMPTY;
                this.bytes_manufacturer = PBField.initBytes(byteStringMicro);
                this.bytes_product = PBField.initBytes(byteStringMicro);
                this.bytes_model = PBField.initBytes(byteStringMicro);
                this.bytes_fingerprint = PBField.initBytes(byteStringMicro);
                this.bytes_sdkversion = PBField.initBytes(byteStringMicro);
                this.uint32_lost_num = PBField.initUInt32(0);
                this.uint32_conti_lost0 = PBField.initUInt32(0);
                this.uint32_conti_lost1 = PBField.initUInt32(0);
                this.uint32_lost_peak_time = PBField.initUInt32(0);
                this.uint32_pkgsize_lost_fail = PBField.initUInt32(0);
                this.uint32_fec_percent = PBField.initUInt32(0);
                this.uint32_frm_fec_percent = PBField.initUInt32(0);
                this.uint32_wave_bitrate = PBField.initUInt32(0);
                this.uint32_idrfrmnum_all = PBField.initUInt32(0);
                this.uint64_idrfrmrate_enc = PBField.initUInt64(0L);
                this.uint64_avgqp_enc = PBField.initUInt64(0L);
                this.uint64_idravgqp_enc = PBField.initUInt64(0L);
                this.uint64_quality_enc = PBField.initUInt64(0L);
                this.uint64_avgrate_enc = PBField.initUInt64(0L);
                this.uint64_avgrate_sever = PBField.initUInt64(0L);
                this.uint64_avgfps_sever = PBField.initUInt64(0L);
                this.uint64_avgfps_enc = PBField.initUInt64(0L);
                this.uint64_avgtruefps_enc = PBField.initUInt64(0L);
                this.uint64_avgcpurate_enc = PBField.initUInt64(0L);
                this.uint64_codectype_enc = PBField.initUInt64(0L);
                this.uint64_video_quality = PBField.initUInt64(0L);
                this.uint64_quality1_enc = PBField.initUInt64(0L);
                this.uint32_video_first_frame_time_cost = PBField.initUInt32(0);
                this.uint32_video_lag_num = PBField.initUInt32(0);
                this.uint32_video_super_resolution = PBField.initUInt32(0);
                this.uint32_video_process_lowlight_opentimes = PBField.initUInt32(0);
                this.uint32_video_process_lowlight_time = PBField.initUInt32(0);
                this.uint32_video_process_videodenoise_opentimes = PBField.initUInt32(0);
                this.uint32_video_process_videodenoise_time = PBField.initUInt32(0);
                this.uint64_video_preprocess_time = PBField.initUInt64(0L);
                this.uint64_video_encode_time = PBField.initUInt64(0L);
                this.uint64_video_transport_time = PBField.initUInt64(0L);
                this.uint64_video_decode_time = PBField.initUInt64(0L);
                this.uint64_video_render_time = PBField.initUInt64(0L);
                this.uint64_video_total_time = PBField.initUInt64(0L);
                this.uint32_video_preprocess_type = PBField.initUInt32(0);
                this.uint64_video_rtt_time = PBField.initUInt64(0L);
                this.uint64_video_jitter_time = PBField.initUInt64(0L);
                this.uint64_video_break_cnt = PBField.initUInt64(0L);
                this.uint32_video_break_time_rate = PBField.initUInt32(0);
                this.uint64_video_break_time_rates = PBField.initUInt64(0L);
                this.uint64_stat_video_qp_dis = PBField.initUInt64(0L);
                this.uint64_stat_video_qp_rate = PBField.initUInt64(0L);
                this.uint64_stat_video_quality_rate = PBField.initUInt64(0L);
                this.uint32_use_new_de_jitter_algorithm = PBField.initUInt32(0);
                this.uint32_avg_de_jitter = PBField.initUInt32(0);
                this.uint32_avg_jitter_delay = PBField.initUInt32(0);
                this.uint32_high_sharpness_info = PBField.initUInt32(0);
                this.uint64_video_svr_enc_rate = PBField.initUInt64(0L);
                this.uint64_de_jitter_dist = PBField.initUInt64(0L);
                this.uint32_avg_out_jitter = PBField.initUInt32(0);
                this.uint64_out_jitter_dist = PBField.initUInt64(0L);
                this.uint32_avg_fec_frame_time_diff = PBField.initUInt32(0);
                this.uint64_fec_frame_time_diff_dist = PBField.initUInt64(0L);
                this.uint32_avg_out_frame_time_diff = PBField.initUInt32(0);
                this.uint64_out_frame_time_diff_dist = PBField.initUInt64(0L);
                this.uint64_jitter_delay_dist = PBField.initUInt64(0L);
                this.uint32_enable_aadsdejitter_max_jdelay = PBField.initUInt32(0);
                this.uint64_codectype_dec = PBField.initUInt64(0L);
                this.uint32_hw_1080P_time = PBField.initUInt32(0);
                this.uint32_video_jank_time_rate = PBField.initUInt32(0);
                this.uint32_video_jank_num_per_minute = PBField.initUInt32(0);
                this.uint32_video_drop_num_per_minute = PBField.initUInt32(0);
                this.uint32_c2c_video_enc_total_time = PBField.initUInt32(0);
                this.uint32_c2c_video_dec_total_time = PBField.initUInt32(0);
                this.str_capture_fps_dist = PBField.initString("");
                this.uint32_total_enc_frame_num = PBField.initUInt32(0);
                this.uint32_total_dec_frame_num = PBField.initUInt32(0);
                this.uint32_frame_freeze_rate = PBField.initUInt32(0);
                this.uint32_video_freeze_reason = PBField.initUInt32(0);
            }
        };
        public hd_video$CmdLocalFlowCtrlInfoReportReqBody msg_local_flow_ctrl_info_body = new MessageMicro<hd_video$CmdLocalFlowCtrlInfoReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdLocalFlowCtrlInfoReportReqBody
            static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{10, 18, 24, 34, 42, 50, 56, 64, 72}, new String[]{"audio_info", "video_info", "enabled_info", NotificationController.Constants.CONFIG_VERSION, "audio_config_version", "video_config_version", "uint32_up_delay_avg", "uint64_up_delay_dist", "multipath_enabled"}, new Object[]{null, null, 0, "", "", "", 0, 0L, Boolean.FALSE}, hd_video$CmdLocalFlowCtrlInfoReportReqBody.class);
            public hd_video$CmdLocalAudioFlowCtrlInfoReportReqBody audio_info = new MessageMicro<hd_video$CmdLocalAudioFlowCtrlInfoReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdLocalAudioFlowCtrlInfoReportReqBody
                static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16, 24, 32}, new String[]{"bandwidth_dist", "core_br_dist", "outband_fec_m_dist", "inband_fec_level_dist_and_fec_mode_dist"}, new Object[]{0L, 0L, 0L, 0L}, hd_video$CmdLocalAudioFlowCtrlInfoReportReqBody.class);
                public final PBUInt64Field bandwidth_dist = PBField.initUInt64(0);
                public final PBUInt64Field core_br_dist = PBField.initUInt64(0);
                public final PBUInt64Field outband_fec_m_dist = PBField.initUInt64(0);
                public final PBUInt64Field inband_fec_level_dist_and_fec_mode_dist = PBField.initUInt64(0);
            };
            public hd_video$CmdLocalVideoFlowCtrlInfoReportReqBody video_info = new MessageMicro<hd_video$CmdLocalVideoFlowCtrlInfoReportReqBody>() { // from class: tencent.im.cs.longconn.hd_video$CmdLocalVideoFlowCtrlInfoReportReqBody
                static final MessageMicro.FieldMap __fieldMap__ = MessageMicro.initFieldMap(new int[]{8, 16, 24}, new String[]{"uint32_avg_video_enc_core_rate", "uint64_stat_video_enc_core_rate", "video_enabled_info"}, new Object[]{0, 0L, 0}, hd_video$CmdLocalVideoFlowCtrlInfoReportReqBody.class);
                public final PBUInt32Field uint32_avg_video_enc_core_rate = PBField.initUInt32(0);
                public final PBUInt64Field uint64_stat_video_enc_core_rate = PBField.initUInt64(0);
                public final PBUInt32Field video_enabled_info = PBField.initUInt32(0);
            };
            public final PBUInt32Field enabled_info = PBField.initUInt32(0);
            public final PBStringField config_version = PBField.initString("");
            public final PBStringField audio_config_version = PBField.initString("");
            public final PBStringField video_config_version = PBField.initString("");
            public final PBUInt32Field uint32_up_delay_avg = PBField.initUInt32(0);
            public final PBUInt64Field uint64_up_delay_dist = PBField.initUInt64(0);
            public final PBBoolField multipath_enabled = PBField.initBool(false);
        };
    };
}
