package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum BannerMaterial {
    KBANNERMATERIALNONE,
    KBANNERMATERIALFAMILYNORMAL,
    KBANNERMATERIALFAMILYANNIVERSARY,
    KBANNERMATERIALLOVERSNORMAL,
    KBANNERMATERIALLOVERSANNIVERSARY,
    KBANNERMATERIALTRAVELNORMAL,
    KBANNERMATERIALFAMILYPREGNANCY
}
