package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum BatchUploadTaskStatus {
    KBATCHUPLOADTASKSTATUSWAITING,
    KBATCHUPLOADTASKSTATUSRUNING,
    KBATCHUPLOADTASKSTATUSSUSPENDED,
    KBATCHUPLOADTASKSTATUSCANCELED,
    KBATCHUPLOADTASKSTATUSFAILED,
    KBATCHUPLOADTASKSTATUSSUCCESS
}
