package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum FamilyRole {
    KFAMILYROLENONE,
    KFAMILYROLEMOTHER,
    KFAMILYROLEFATHER,
    KFAMILYROLEGRANDFATHER,
    KFAMILYROLEGRANDMOTHER,
    KFAMILYROLEMATERNALGRANDMOTHER,
    KFAMILYROLEMATERNALGRANDFATHER,
    KFAMILYROLEAUNT,
    KFAMILYROLEUNCLE,
    KFAMILYROLEYOUNGERAUNT,
    KFAMILYROLEYOUNGERUNCLE,
    KFAMILYROLESISTER,
    KFAMILYROLEBROTHER
}
