package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum FlashTransferFileType {
    KFILETYPEUNSPECIFIED,
    KFILETYPEMUSIC,
    KFILETYPEVIDEO,
    KFILETYPEDOC,
    KFILETYPEZIP,
    KFILETYPEAPK,
    KFILETYPEXLS,
    KFILETYPEPPT,
    KFILETYPEHTML,
    KFILETYPEPDF,
    KFILETYPETEXT,
    KFILETYPEOTHER,
    KFILETYPEPSD,
    KFILETYPETDDOC,
    KFILETYPETROOPMEMBER,
    KFILETYPEAI,
    KFILETYPEFONT,
    KFILETYPEIPA,
    KFILETYPEKEYNOTE,
    KFILETYPENOTE,
    KFILETYPENUMBERS,
    KFILETYPEPAGES,
    KFILETYPESKETCH,
    KFILETYPEDMG,
    KFILETYPEPKG,
    KFILETYPEFOLDER,
    KFILETYPEIMAGE,
    KFILETYPEEXE
}
