package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum FlashTransferFileDownLoadStatus {
    KFLASHTRANSFERFILEDOWNLOADSTATUSWAITING,
    KFLASHTRANSFERFILEDOWNLOADSTATUSRUNNING,
    KFLASHTRANSFERFILEDOWNLOADSTATUSSUSPENDED,
    KFLASHTRANSFERFILEDOWNLOADSTATUSCANCELED,
    KFLASHTRANSFERFILEDOWNLOADSTATUSFAILED,
    KFLASHTRANSFERFILEDOWNLOADSTATUSSUCCESS
}
