package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum FlashTransferSceneType {
    KSCENETYPEUNKNOWN,
    KSCENETYPEC2C,
    KSCENETYPEGROUP,
    KSCENETYPECHANNEL,
    KSCENETYPEMINIWORLD,
    KSCENETYPETEMPCHAT,
    KSCENETYPEONLYLOGIC,
    KSCENETYPETRANSFERCENTER,
    KSCENETYPESCAN,
    KSCENETYPEH5LAUNCHCLIENT,
    KSCENETYPEDOWNLOAD,
    KSCENETYPETOPBANNER,
    KSCENETYPECOLLECT
}
