package com.tencent.qqnt.kernel.nativeinterface;

/* loaded from: classes24.dex */
public enum PersonalAlbumModifyType {
    KPERSONALALBUMMODIFYTYPENONE,
    KPERSONALALBUMMODIFYTYPENAME,
    KPERSONALALBUMMODIFYTYPEDESC,
    KPERSONALALBUMMODIFYTYPEPRIV,
    KPERSONALALBUMMODIFYTYPECOVER,
    KPERSONALALBUMMODIFYTYPEBABYBIRTHEVENT,
    KPERSONALALBUMMODIFYTYPELOVETIME,
    KPERSONALALBUMMODIFYTYPEALBUMTYPE,
    KPERSONALALBUMMODIFYTYPETOPFLAG,
    KPERSONALALBUMMODIFYTYPEAUTOJOIN,
    KPERSONALALBUMMODIFYTYPEEND
}
