package com.tencent.qqnt.kernel.nativeinterface;

/* loaded from: classes24.dex */
public enum PictureFormat {
    KPICTUREFORMATUNKNOWN,
    KPICTUREFORMATBMP,
    KPICTUREFORMATPNG,
    KPICTUREFORMATGIF,
    KPICTUREFORMATJPG,
    KPICTUREFORMATJPEG,
    KPICTUREFORMATWEBP,
    KPICTUREFORMATNEWJPEG,
    KPICTUREFORMATNEWPNG,
    KPICTUREFORMATNEWWEBP,
    KPICTUREFORMATNEWPROJPEG,
    KPICTUREFORMATNEWSHARPP,
    KPICTUREFORMATNEWBMP,
    KPCITUREFORMATNEWAVIF,
    KPICTUREFORMATNEWGIF,
    KPICTUREFORMATNEWAPNG
}
