package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum QunMediaRightEnum {
    KQUNMEDIARIGHTENUMNONE,
    KQUNMEDIARIGHTENUMADDALBUM,
    KQUNMEDIARIGHTENUMMODIFYALBUM,
    KQUNMEDIARIGHTENUMUPLOADMEDIA,
    KQUNMEDIARIGHTENUMDELETEMEDIA,
    KQUNMEDIARIGHTENUMTOPALBUM,
    KQUNMEDIARIGHTENUMDELETEALBUM
}
