package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum RichMediaAppType {
    KAPPTYPEQQAIOCHAT,
    KAPPTYPECHANNELAIOCHAT,
    KAPPTYPEM86AIOCHAT,
    KAPPTYPEM86EMOJICOLLECTION,
    KAPPTYPEM86PHOTOS,
    KAPPTYPEM86PLAZA,
    KAPPTYPEARKSHARE,
    KAPPTYPEACGAIOCHAT,
    KAPPTYPEACGEMOJICOLLECTION,
    KAPPTYPEACGPHOTOS,
    KAPPTYPEACGPLAZA,
    KAPPTYPEQQLPLAN,
    KAPPTYPEM86AIGC,
    KAPPTYPEQQEMOJIAIGC,
    KAPPTYPEQZONEPHOTOS,
    KAPPTYPEQZONEINTIMATESPACEPHOTOS,
    KAPPTYPEQZONESHUOSHUOCOMMENT,
    KAPPTYPEQZONEINTIMATESPACEARKSHARE
}
