package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum RichMediaAgentType {
    KAGENTTYPEUNKNOWN,
    KAGENTTYPEQQ,
    KAGENTTYPENT,
    KAGENTTYPETIM,
    KAGENTTYPEWEB,
    KAGENTTYPESAFE,
    KAGENTTYPEBIGDATA,
    KAGENTTYPEQIDIAN,
    KAGENTTYPEQQLOGIC,
    KAGENTTYPEQIDIANTRACK,
    KAGENTTYPEM86PHOTOSVR,
    KAGENTTYPEM86COLLECTIONSVR,
    KAGENTTYPEM86MSGSVR,
    KAGENTTYPEROBOTAPISVR,
    KAGENTTYPEQQGROUPSERVER,
    KAGENTTYPEM86PLAZASERVER,
    KAGENTTYPEQIDIANB2BNLPSERVER,
    KAGENTTYPEQIDIANMSGSERVER,
    KAGENTTYPEARKSHARESERVER,
    KAGENTTYPEQIDIANB2BPCHATMSGSERVER,
    KAGENTTYPEQIDIANB2BMSGSERVER,
    KAGENTTYPELPLANSERVER,
    KAGENTTYPEM86PROXYSERVER,
    KAGENTTYPECHANNELHTTPGATEWAYSERVER,
    KAGENTTYPEGROUPDIGESTSERVER,
    KAGENTTYPEGROUPTODOREADERSERVER,
    KAGENTTYPEGROUPMANAGERROBOTSERVER,
    KAGENTTYPEQIDIANB2BQDGROUPMSGSERVER,
    KAGENTTYPEQZONEQUNPSA,
    KAGENTTYPEMSGSVR
}
