package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum SearchLocalBusinessType {
    KSEARCHLOCALBUSINESSTYPEUNKNOWN,
    KSEARCHLOCALBUSINESSTYPEALL,
    KSEARCHLOCALBUSINESSTYPECREATEGROUP,
    KSEARCHLOCALBUSINESSTYPEFORWARD,
    KSEARCHLOCALBUSINESSTYPEDESKTOPALL,
    KSEARCHLOCALBUSINESSTYPEDESKTOPBUDDY,
    KSEARCHLOCALBUSINESSTYPEDESKTOPGROUP,
    KSEARCHLOCALBUSINESSTYPEMQQALL
}
