package com.tencent.qqnt.kernel.nativeinterface;

/* compiled from: P */
/* loaded from: classes24.dex */
public enum TaskStatus {
    KTASKSTATUSWAITBUILDFILETREE,
    KTASKSTATUSBUILDINGFILETREE,
    KTASKSTATUSBUILDEDFILETREE,
    KTASKSTATUSUPLOADING,
    KTASKSTATUSUSERCANCELUPLOAD,
    KTASKSTATUSUSERCANCELPARTIALUPLOAD,
    KTASKSTATUSUPLOADSUCC,
    KTASKSTATUSUPLOADFAIL
}
